### PR TITLE
LUCENE-10425：PostingsEnum supports to return current index of postings

### PR DESCRIPTION
**Pull request by wjp719**
PostingsEnum supports to return current index of postings

As we known, the docId list in .doc is like an array of integer, every element of this array is a docId, when we call nextDoc or advance method, it will move to another element of this array. this pr support to return current index of the element in the posting list. We can use this method to find the diff value when we call advance method continuously, the diff value means we skip how many doc in this docId list.

#11461

### CODE REVIEW

**Comment by msokolov** [comment]
I'm concerned exposing this could limit future implementations by requiring them to support it. Do you have a proposed use case that would justify needing to add this? Maybe post to java-user@lucene.apache.org explaining the use case?

**Comment by wjp719** [comment]
@msokolov Hi, I describe a use case in this issue https://issues.apache.org/jira/browse/LUCENE-10425 , thanks a lot

**Comment by jpountz** [comment]
The use-case makes sense to me, but like @msokolov I'm worried that this could limit future implementations. For instance if we were to encode postings as a bitset, we wouldn't be able to get the current index in constant time like the current postings can, we'd have to count all one bits.

**Comment by jpountz** [comment]
Thinking through this a bit more, I imagine that this is the reason why you made this API optional. We still like the set the bar quite high to add new APIs to PostingsEnum so I'd like to think a bit more about what problems this would be solving. I'll leave some thoughts on the JIRA issue.

**Comment by mikemccand** [comment]
Thanks @wjp719.

It looks like this is a nice opto for narrow use cases and the concern is adding a new API, especially to such a hot class as `PostingsEnum`, needs to meet a high bar for helping many uses cases, and maybe this change doesn't?  Please reopen if you feel strongly @wjp719?

**Pull request closed without merging**
