### PR TITLE
LUCENE-9969:TaxoArrays, a member variable of the DirectoryTaxonomyReader class, i…

### PR DESCRIPTION
**Pull request by bybyset**
https://issues.apache.org/jira/browse/LUCENE-9969

#11008

### CODE REVIEW

**Comment by dweiss** [comment]
Just a note from the side (I'm not familiar with this code): somehow I don't believe switching to a soft reference here is solving anything - it just shoves the problem under the rug at the cost of potentially recreating that value over and over in adverse heap conditions... if you're low on memory, it's sometimes better to hit an OOM... this way you're aware your heap is insufficient. A soft reference here and there will make everything trudge forward but may lead to dire runtime performance (a vicious cycle when the GC is freeing references, code keeps recreating them).

**Comment by rmuir** [comment]
Yeah, SoftReference is never the solution. We should add this class to our forbidden apis list.

**Comment by mikemccand** [comment]
Do you know how large your Taxonomy index is (how many unique `FacetLabel`s)?

In your application, are all three arrays being allocated (`parents`, `siblings` and `children`)?  That triples the memory cost, but if you are not really needing full hierarchical facets, you should only need to allocate one of those arrays.  Or you could explore `SortedSetDocValues` faceting.

**Comment by mikemccand** [comment]
These arrays are in general a crazy costly part of using taxonomy facets ... we should explore more efficient alternatives.  E.g. if the Lucene user is only using a single level hierarchy (field `foo` and value `bar`), maybe we could pre-allocate slices of ordinal space to each field `foo` which could be stored much more compactly (e.g. an interval tree) than the full `int[] parents` array we use today.

**Comment by JavaCoderCff** [comment]
Parents, siblings and children. I'm not sure why.

I also think SoftRefrence is not the optimal solution, but it should be an urgent solution, at least our app will not crash frequently due to OOM.

I really hope to have a better solution, thank you very much!!

**Comment by rmuir** [comment]
could we look at storing this stuff as docvalues instead of as payloads that are read into heap memory? It is just integers or list of integers right?

**Pull request closed without merging**
