### PR TITLE
Avoid allocating redundant Strings

### PR DESCRIPTION
**Pull request by sabi0**
Removed unnecessary `toString()` / `substring()` calls to avoid extra Strings being allocated

### CODE REVIEW

**Review by dweiss — APPROVED** [review]
Some terrible cruft in there, thank you. Please add the changes entry and credit yourself.

**Comment by sabi0** [comment]
Done.
I keep forgetting about this, sorry.

**Review by stefanvodita — APPROVED** [review]
Thank you for the changes @sabi0 and @dweiss for reviewing. This should be ready to merge.

**Comment by stefanvodita** [comment]
Done. I just had to move the CHANGES entry up.
@sabi0 - the clean-up [work you've been doing](https://githubsearch.mikemccandless.com/search.py?sort=recentlyUpdated&dd=all_users%3Asabi0) is really appreciated!

**Comment by sabi0** [comment]
Thank you, @stefanvodita

**Pull request merged**
