### PR TITLE
Run spotless after javac (#12012)

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

**Comment by rmuir** [comment]
thank you @dweiss

**Comment by rmuir** [comment]
@dweiss do you mind pushing to 9.x, otherwise i will do it for you. I just hit this again in 9.x :)

**Comment by dweiss** [comment]
You have?! Well, that's strange - I've pushed it to 9x... Can you reproduce it with the head?

**Comment by rmuir** [comment]
Thanks again, it really helps make the backporting process less painful for me.

**Pull request merged**
