### PR TITLE
Change StringHelper from abstract to final.

### PR DESCRIPTION
**Pull request by vsop-479**

### CODE REVIEW

**Comment by jpountz** [comment]
I believe that the abstract modifier aimed at preventing instantiation. Can you add a private constructor then?

**Comment by vsop-479** [comment]
> Can you add a private constructor then?

There already is a private constructor in it (line 66).

**Comment by vsop-479** [comment]
I moved the private constructor to the beginning place.

**Comment by uschindler** [comment]
I am not sure if this change is needed at all. There are multiple patterns to make static only classes. The most important one is to add a private ctor. The final or not doesn't really matter.

**Comment by vsop-479** [comment]
Thanks @uschindler — Do you think it is necessary that just remove the abstract modifier?

**Comment by uschindler** [comment]
If you really want to change it, make it final. But it's not necessary.

**Comment by vsop-479** [comment]
> it's not necessary.

I will close it.

**Pull request closed without merging**
