### PR TITLE
LUCENE-10461: fix windows launch script for luke so that it works with ITs

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

**Comment by dweiss** [comment]
@uschindler would you have a look as a fellow Windows user? cmd and start are crazy but I verified it works manually and from within the test, so we should be ok this time.

**Review by mocobeta — APPROVED** [review]
I'm not familiar with Windows commands so can't review it - I confirmed this works on Windows 10 (including whitespaces in the path) and passes the distribution tests on Windows.

**Comment by dweiss** [comment]
Thanks @mocobeta ! I'll merge and backport this later today.

**Comment by mocobeta** [comment]
@dweiss if you don't mind, I can merge and backport it to branch_9x and branch_9_1.

**Review by uschindler — APPROVED** [review]
Script works. I haven't tested the testing part. If the env var is correctly set, it should work.

**Comment by mocobeta** [comment]
Okay, then let me commit this in...

**Comment by uschindler** [comment]
Thanks!

**Comment by dweiss** [comment]
Thank you both.

**Comment by mocobeta** [comment]
No problem, thanks for taking care of this.
Though I can't review Windows scripts (there are too many pitfalls), feel free to ping me if a manual test or double-check for the start scripts is needed. I'm always keeping major three operating systems (Windows, MacOS, and Linux) because of Luke and other reasons.

**Pull request merged**
