### PR TITLE
Update github hunspell regression test to use JDK 17

### PR DESCRIPTION
**Pull request by gsmiller**
Not entirely sure how to test this outside of opening a PR with the change, so apologies if I have to iterate a bit to get this right in the PR.

### CODE REVIEW

**Comment by mocobeta** [comment]
I cherry-picked this in https://github.com/apache/lucene/pull/643 and it started to work, thanks!
Screenshot from 2022-02-06 12-28-32

**Comment by mocobeta** [comment]
I wonder we could create a custom composite action to share the JDK set up between workflows.
I have not tried but noticed custom action recently supports "use" to combine other actions in it. I will check if it works for us when I have spare time.
https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/

**Review by mocobeta — APPROVED** [review]

**Review by dweiss — APPROVED** [review]
yep, this will do it, I think.

**Comment by dweiss** [comment]
> Or, it could be better to have only one large CI workflow that executes all checks/tests just like we do so in the Jenkins servers, instead of multiple ones.

This workflow check is specific to hunspell - I don't think it makes sense to run it for all the pull requests. Yes, some parts of these workflows could be pulled into a reusable action; I'm not too familiar with these though.

**Comment by gsmiller** [comment]
Ah, great! Thanks @mocobeta and @dweiss. I had cherry-picked this over in #644 as well but was having trouble getting the checks to actually run. Maybe there was a github delay in the checks firing or something, but it looks like eventually ran over there as well.

I'll go ahead and merge this to get hunspell checks unblocked. Thanks again!

**Pull request merged**
