### PR TITLE
GITHUB-11761: Move minimum TieredMergePolicy delete percentage from 2…

### PR DESCRIPTION
**Pull request by mdmarshmallow**
…0% to 5%

### CODE REVIEW

**Review by zhaih — APPROVED** [review]
Please add an entry in CHANGES.txt :)

**Review by uschindler — APPROVED** [review]

**Comment by zhaih** [comment]
Thanks @mdmarshmallow! I merged and backported it!

**Comment by jpountz** [comment]
E.g. maybe it would be better to add more documents in `testNRTIsCurrentAfterDelete` in order for the single delete not to introduce more than 20% deletes, and keep the `TieredMergePolicy` defaults?

**Comment by mdmarshmallow** [comment]
These new tests did fail, I created a new PR (tied to the same issue as this one) to more cleanly fix the unit tests without having to change the default percentage: https://github.com/apache/lucene/pull/11841.

**Pull request merged**
