### PR TITLE
draft pr

### PR DESCRIPTION
**Pull request by wjp719**
draft pr

### CODE REVIEW

**Comment by wjp719** [comment]
@jpountz Hi, can you help to review this pr, thanks a lot

**Comment by jpountz** [comment]
Thanks for the explanation of what this PR does. I'm not comfortable with the fact that with your change, stored fields are no longer stored in doc ID order. It's probably a good trade-off in your case and maybe something you can do in a custom codec, but I don't like doing it in the default codec as it would also mean that users can no longer leverage index sorting to improve data locality within stored fields, and that feeding this stored fields reader into another writer for a merge would trigger lots of random access.

While it certainly wouldn't result in speedup that is as good, I'll point out that using a merge policy that only merges adjacent segments like LogByteMergePolicy should help better take advantage of https://github.com/apache/lucene/pull/134 and get slightly better merging performance when an index sort on timestamp is configured.

**Comment by wjp719** [comment]
> It's probably a good trade-off in your case and maybe something you can do in a custom codec

Thanks for your reply,  does that mean   I can add a new custom codec in Lucene?

**Comment by jpountz** [comment]
> Thanks for your reply, does that mean I can add a new custom codec in Lucene?

I was more thinking you could maintain a codec with your own stored fields format in your own codebase and take advantage of the fact that codecs are pluggable in Lucene.

**Pull request closed without merging**
