### PR TITLE
enable errorprone for github check action

### LINKED ISSUE #11943: try to re-enable error-prone checks to happen more often?
### Description

Currently this is enabled nightly-only, and it is very slow compared to java compiler. I wonder if we could enable it "more often" somehow. Besides being slow it also has some compatibility issues with different JDK versions I think, or at least it has in the past. So this could be a problem to an actual end-user of lucene...

We sped it up with #11937 and it no longer dominates the whole machine in such a way that you can't move the mouse pointer when it runs.

Maybe it could be sped up more if we disabled additional checks. I feel like the way we denylist checks, new checks sneak in that we may not want on upgrading it, making it slower.

Maybe a compromise would be to enable it just for github actions?

### PR DESCRIPTION
**Pull request by rmuir**
The idea is to fail faster, prevent new violations from failing nightly builds. If it becomes a hindrance to contributions or an annoyance, we can disable it.

Closes #11943

### CODE REVIEW

**Comment by risdenk** [comment]
Looking at the last main github actions run: https://github.com/apache/lucene/actions/runs/3481009561/jobs/5821544088 The gradle check without tests was `6m 32s`. The same step for this github actions run: https://github.com/apache/lucene/actions/runs/3481792417/jobs/5823331065 was `6m 37s`

So 5s added from what I can tell now. Based on the compile times doesn't look like the 5 seconds was from compile either.

**Comment by dweiss** [comment]
Well, it was definitely slower before the patch ()?
https://github.com/apache/lucene/actions/runs/3473485571/jobs/5805548845

**Comment by rmuir** [comment]
hmm... so did it actually run? :)

fwiw, my biggest concern for this is annoying contributors. if they do the right thing and `gradle check` fails, then make a contribution and the build fails here, it could bother them. Especially if they have to play whack-a-mole because error-prone feeds them one violation at a time :(

At the same time, we don't have a lot of crazy error-prone checks turned on... they are selective... so hopefully it would be more of a rare event.

**Comment by dweiss** [comment]
> hmm... so did it actually run? :)

You could try to revert the commit with offending code - then we'd see. :)

**Comment by rmuir** [comment]
i will add a violation

**Comment by rmuir** [comment]
If it works, build should fail and look like this:
```
> Task :lucene:core:compileTestJava FAILED
/home/rmuir/workspace/lucene/lucene/core/src/test/org/apache/lucene/TestDemo.java:76: warning: [ConstantOverflow] Compile-time constant expression overflows
        long x = Integer.MAX_VALUE * Integer.MAX_VALUE;
                                   ^
    (see https://errorprone.info/bugpattern/ConstantOverflow)
error: warnings found and -Werror specified
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
1 warning

FAILURE: Build failed with an exception.
```

**Comment by rmuir** [comment]
It worked... even for the `gradle test` task which didn't turn it on. So now i'm wondering if it has been enabled here all along because of `isCIBuild` which has a "CI-detector" that looks at env vars.

**Comment by rmuir** [comment]
yeah, nothing to do here apparently. errorprone is already on via magical CI detection: `isCIBuild = System.getenv().keySet().find { it ==~ /(?i)((JENKINS|HUDSON)(_\w+)?|CI)/ } != null`

**Pull request closed without merging**
