### PR TITLE
LUCENE-10100: same as 10091  Fix some old errors in the main branch

### PR DESCRIPTION
**Pull request by xiaoshi2013**
Fix the stale code of the createAnalyzer method of the NewAnalyzerTask class.
Change some configuration items that don't work, and make it work.

#11138

### CODE REVIEW

**Comment by xiaoshi2013** [comment]
There was an error in the previous pr request, I resubmitted it.

 Hi @mikemccand,  I fixed some obsolete config items and code in the main branch.

**Comment by xiaoshi2013** [comment]
Hi @mikemccand,  I fixed some obsolete config items and code in the main branch.

**Comment by xiaoshi2013** [comment]
Hi @jpountz, can you review this pr?
Thanks.

**Comment by xiaoshi2013** [comment]
Hi @mikemccand , Do you have time to look at this pr?

**Review by mikemccand — APPROVED** [review]
Woops, sorry for the long delay, and thank you @xiaoshi2013!  These changes look good -- thanks for cracking the rust off these benchmarking `.alg` files.  I'll merge soon.

**Pull request merged**
