### PR TITLE
Speedup sandbox/DocValuesTermsQuery

### PR DESCRIPTION
**Pull request by rmuir**
* Optimize the common case that docs only have single values for the field
* In the multivalued case, terminate reading docvalues if they are > maximum set ordinal
* Implement ScorerSupplier, so that (potentially large) number of ordinal lookups aren't performed just to get the cost()

### CODE REVIEW

**Comment by rmuir** [comment]
moved this thing to `Sorted(Set)DocValuesField.newSlowSetQuery` as it is a much better API to document its slowness safe;y and to encapsulate the guts.

it does not yet claim to help or work with `TermInSetQuery`, only suggests using along with `BinaryPoint#newSetQuery` just like the other slow methods here. There's no estimation issues for the points use-case.

**Comment by rmuir** [comment]
Another use-case this works with is for the IP address types, which is really just some sugar over `BinaryPoint`: `IndexOrDocValuesQuery(InetAddressPoint.newSetQuery(..), SortedSetDocValuesField.newSlowSetQuery(...))`

**Comment by rmuir** [comment]
btw as followup we should investigate fixing the SortedSetDocValuesRangeQuery to use ScorerSupplier too. It is bad to do a bunch of costly `lookupTerm` operations per-segment that may be unnecessary, just to expose `cost()` (see IndexOrDocValues). Even if its only 2 lookups: we can think of these lookups as binary-searching the entire terms dict, causing random accesses, page faults, etc.

**Comment by gsmiller** [comment]
Good catch on the lack of `scoreSupplier` resulting in all the ordinal lookups. The multivalued optimization is nice as well. The change looks good to me. I'll see if I can repurpose the benchmarking methodology I've been using for term-in-set query stuff tomorrow to see how this change helps there (I've confirmed with profiling that the ordinal lookups are contributing significantly to the cost of the `IndexOrDV` approach in some of the tasks, so this will help there)

**Comment by rmuir** [comment]
yeah my problem with these dv queries that look up ordinals, indexdocvaluesquery might decide based on cost() to just use points... but without scorersupplier, you've wastefully looked up a ton of ordinals in the DV, useless work.

**Review by jpountz — APPROVED** [review]

**Pull request merged**
