### PR TITLE
Remove direct dependency of NodeHash to FST

### PR DESCRIPTION
**Pull request by dungba88**
### Description

Follow-up of https://github.com/apache/lucene/pull/12646. NodeHash still depends on both FSTCompiler and FST. With the current method signature, one can create the NodeHash with a FST and call addNode with different FSTCompiler. This PR simplifies the signature and allow a consistent behavior.

### CODE REVIEW

**Review by mikemccand — APPROVED** [review]
This looks great!  I love the baby step decoupling of NodeHash from FST.  This will conflict with the "bounded RAM usage by NodeHash for prefixes" PR, but it should be quick to resolve the conflicts so I think we can push this one first.

**Comment by mikemccand** [comment]
Actually, I'm nervous about my git merging skills!  Let's try to review/push the [RAM limited FST building PR](https://github.com/apache/lucene/pull/12633) first?

**Comment by dungba88** [comment]
That's ok for me too! I'll rebase after the other PR is merged

**Comment by dungba88** [comment]
As the other PR has been merged, I have rebased and resolved the conflict

**Comment by mikemccand** [comment]
Thanks @dungba88 -- looks great, I'll merge soon!

**Comment by mikemccand** [comment]
Thanks @dungba88 -- I'll wait to backport this until after backporting https://github.com/apache/lucene/pull/12633

**Pull request merged**
