### PR TITLE
Make CombinedFieldQuery eligible for WAND/MAXSCORE.

### PR DESCRIPTION
**Pull request by jpountz**
`CombinedFieldQuery` currently returns an infinite maximum score. We can do better by returning the maximum score that the sim scorer can return, which in the case of BM25 is bounded by the IDF. This makes CombinedFieldQuery eligible for WAND/MAXSCORE (not their block-max variants though, since we return the same score upper bound for the whole index).

### CODE REVIEW

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by jpountz** [comment]
Interestingly, it looks like this change caused a significant regression to top-level disjunctions, see e.g. https://benchmarks.mikemccandless.com/OrHighHigh.html.

It seems to me that this is due to the fact that `MaxScoreBulkScorer#scoreInnerWindowAsConjunction` now sometimes runs with iterators implemented as `DisjunctionDISIApproximation` while it only ran with iterators implemented as `BlockImpactsDocsEnum` before this change. So `nextDoc()` / `advance()` become bimorphic (or maybe even polymorthic I'm not 100% sure if we went from 1 to 2 or from 2 to 3).

I won't revert since it's a pre-existing issue, we would have seen the same earlier if we ran more disjunctions of <something else than term queries> in nightly benchmarks. It would be interesting to look into mitigating this sort of slowdown though.

**Comment by jpountz** [comment]
So it went from bimorphic to polymorphic indeed, we had 2 iterator impls: `Lucene101PostingsReader$BlockImpactsDocsEnum` and `SlowImpactsEnum` and we added `DisjunctionDISIApproximation`. Removing `SlowImpactsEnum` should be easy, I'll look into it.

**Comment by jpountz** [comment]
I opened #14017.

**Pull request merged**
