### PR TITLE
Make `static final Map` constants immutable

### PR DESCRIPTION
**Pull request by sabi0**

### CODE REVIEW

**Review by kkmr — APPROVED** [review]

**Review by dweiss — APPROVED** [review]
LGTM. Changes entry? :)

**Comment by sabi0** [comment]
I see that `BackwardsCompatibilityTestBase` is failing after switching to the fresh 'main':
```
AssertionError: Version: 9.11.0 missing [in thread "Test worker"]
                at junit@4.13.1/org.junit.Assert.fail(Assert.java:89)
                at junit@4.13.1/org.junit.Assert.assertTrue(Assert.java:42)
                at org.apache.lucene.backward_index.BackwardsCompatibilityTestBase.<clinit>(BackwardsCompatibilityTestBase.java:81)
```

Should I fix it? Or should I wait until it's fixed in 'main'?

**Comment by dweiss** [comment]
Wait until this is fixed, merge with main and then we'll take it from there. Thanks.

**Review by dweiss — APPROVED** [review]

**Comment by dweiss** [comment]
I've applied this to main but it didn't backport cleanly to branch_9x. Would you have some time to go through the conflicts and create another PR that targets branch_9x, please? These are cosmetic changes but they're worth backporting, I think. Thank you (and sorry for not doing it myself).

**Comment by sabi0** [comment]
I will happily do that. No problem.
(Just need to figure out how to get the 9x branch into my fork..)

**Comment by dweiss** [comment]
Your fork should contain all the branches of the original repository. You should typically have two remotes - one to your fork (origin), one to lucene's upstream git. Let's say the upstream is called "upstream". This process should work to create a local branch_9x
```
git fetch upstream
git checkout upstream/branch_9x -b my_fix_on_9x
# make changes
git push origin HEAD -u
```
then create a PR against branch_9x in Lucene. :)

**Comment by sabi0** [comment]
PR#13100

**Comment by uschindler** [comment]
Hi this won't go into 9.10 because the branch is already cut and the release started. Please move the entry to 9.11.

I don't think we will have a 9.11 release anymore, as we want to go for 10.0, so I am not sure if it is worth to backport the changes.

**Comment by dweiss** [comment]
If the backport has been done already, I think it's good to merge it in. I'm sure something will pop up to warrant 9.11...

**Comment by dweiss** [comment]
I'll move the changes entry, my bad.

**Pull request merged**
