### PR TITLE
Fix StoredFieldsConsumer finish

### PR DESCRIPTION
**Pull request by linfn**
### Description

The `lastDoc` has already invoked `startDocument`, and the next `startDocument` docId should be `lastDoc + 1`.
Additionally, the `lastDoc` will increment automatically within `startDocument`

### CODE REVIEW

**Comment by jpountz** [comment]
Ouch, thanks for finding it and fixing it. Can you add a test?

**Comment by linfn** [comment]
> Ouch, thanks for finding it and fixing it. Can you add a test?

Test added. Let me know if anything else is needed.

**Review by jpountz — APPROVED** [review]
Thanks, this looks good to me. Can you add an entry to `lucene/CHANGES.txt` under 10.1.0?

**Comment by linfn** [comment]
@jpountz Done. Thanks!

**Pull request merged**
