### PR TITLE
LUCENE-10532: remove @Slow annotation

### PR DESCRIPTION
**Pull request by rmuir**
This annotation is such an antipattern, it is so harmful to our codebase.
* gives the impression that "slow tests are ok"
* it is like "support for slow tests"
* allows certain privileged ppl to skip slow tests (those that know the gradle magic)
* probably same people are the ones writing slow tests, not having to live with consequences
* causes differences across runs of different devs for no good reason

we don't need this annotation. we can work together to keep the tests fast. if tests are slow we can all share the pain until we fix the test to be fast.

this thing is a real antipattern, i think the idea came from solr, but well, look at their tests. let's not be like them.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]

**Comment by dweiss** [comment]
I'm fine with this. Reasons for Slow (and other test groups) are various. I use Slow in projects where certain tests are indeed slow by nature - have to unpack the distribution/ fork processes or start networking layers. These are typically integration tests. They run on the CI but they're not mandatory for local developer runs. I don't think this is needed in Lucene either.

**Review by mocobeta — APPROVED** [review]
+1. As far as I measure the test execution time with or without slow tests, this will not bring critical pain points to the development routine. 
And having both `@Slow` and `@Nightly` is simply a bit confusing to me (I couldn't see the difference between them).

**Comment by rmuir** [comment]
Thanks @cpoerschke for correcting my dyslexia :)

**Comment by rmuir** [comment]
> I'm fine with this. Reasons for Slow (and other test groups) are various. I use Slow in projects where certain tests are indeed slow by nature - have to unpack the distribution/ fork processes or start networking layers. These are typically integration tests. They run on the CI but they're not mandatory for local developer runs. I don't think this is needed in Lucene either.

I like the idea of the test groups actually, it came up on another PR: https://github.com/apache/lucene/pull/633 . I just think lucene would do better with different test groups to better test what we need (e.g. something like suggested `@Concurrent`.  The `@Slow` doesn't help us IMO.

**Pull request merged**
