### PR TITLE
LUCENE-10125: Optimize primitive writes in OutputStreamIndexOutput

### PR DESCRIPTION
**Pull request by uschindler**
https://issues.apache.org/jira/browse/LUCENE-10125

### CODE REVIEW

**Review by rmuir — APPROVED** [review]
This looks great, very clean. If the benchmark checks out, let's merge it.

**Review by jpountz — APPROVED** [review]
LGTM. I'm seeing 18% faster merges of points with this change, on par with how it was before #102.

**Comment by uschindler** [comment]
Thanks Adrien.

About the API change: Instead of throwing IAE, I can also round up the buffer size in ctor if it is <8.
What do you think?

Uwe

**Comment by jpountz** [comment]
My guess is that such a small buffer size would always be a mistake, so better fail than silently round?

**Comment by uschindler** [comment]
OK, then let's keep it like that.

Do you think we should add a test (more or less a clone of TestByteArrayDataOutput)? I have one ready already (it just writes some primitives and checks output size and reads again from an array.

**Comment by jpountz** [comment]
+1 to add a test for ints/longs written on boundaries

**Comment by uschindler** [comment]
I added a simple test that should catch all boundaries.

**Review by jpountz — APPROVED** [review]

**Pull request merged**
