### PR TITLE
Fix NPE for when fields are missing in `searchNearestVectors`

### PR DESCRIPTION
**Pull request by benwtrent**
Related to: https://github.com/apache/lucene/pull/13162

Since this is unreleased, no changelog entry is necessary.

### CODE REVIEW

**Review by mayya-sharipova — APPROVED** [review]
Thanks

**Comment by ChrisHegarty** [comment]
Was this behaviour regressed by https://github.com/apache/lucene/pull/13162? I wonder if a test would be warranted to ensure that it does not reoccur.  Also, in some areas `fi.getVectorDimension() == 0` was also checked at the same time.

**Comment by benwtrent** [comment]
@ChrisHegarty added a test :)

**Review by ChrisHegarty — APPROVED** [review]
Thanks @benwtrent. LGTM

**Pull request merged**
