### PR TITLE
Document why we need `lastPosBlockOffset`

### PR DESCRIPTION
**Pull request by Tony-X**

### CODE REVIEW

**Review by mikemccand — APPROVED** [review]
Thanks @Tony-X!

**Comment by mikemccand** [comment]
Oh, it looks like `tidy` is angry -- can you run `./gradlew tidy` @Tony-X?  This will re-style your new comment to match the required styling.  Thanks!

**Comment by Tony-X** [comment]
@mikemccand sure. Thanks for pointing out the useful `tidy` target :) I got it fixed

**Review by slow-J — APPROVED** [review]

**Comment by mikemccand** [comment]
I backported to 9.x as well ... annoying that GitHub doesn't state in summary that the above push was to 9.x (it's only reflected here because it referenced this PR).  It does reflect that the first push was to `apache:main`.

Is there a quick way via the GitHub UI to merge back to 9.x after passing all tests for simple (non-conflict) merges?  I fallback to command-line but maybe I'm "holding it wrong", thus losing the 9.x backport transparency here?

**Pull request merged**
