### PR TITLE
Lucene-10188: Give SortedSetDocValues a docValueCount()?

### PR DESCRIPTION
**Pull request by spike-liu**
https://issues.apache.org/jira/browse/LUCENE-10188

### CODE REVIEW

**Comment by mikemccand** [comment]
This change looks good to me, except why did we need to resurrect `DirectDocValuesFormat`?  Was it an accident to include that in this PR maybe?

**Comment by spike-liu** [comment]
> This change looks good to me, except why did we need to resurrect `DirectDocValuesFormat`? Was it an accident to include that in this PR maybe?

Thanks for you review, Michael. "DirectDocValueFormat' was my mistake and removed from commits.

**Comment by mikemccand** [comment]
Thanks @spike-liu -- this looks great to me!  I'll leave it open for at least 48 hours to see if anyone else wants to approve/comment, else lazy consensus kicks in!

**Comment by mikemccand** [comment]
Thanks @spike-liu -- I pushed this to `main`  and will backport to 9.x shortly.

**Comment by spike-liu** [comment]
> Thanks @spike-liu -- I pushed this to `main` and will backport to 9.x shortly.

It is my pleasure, Michael.

**Pull request merged**
