### PR TITLE
LUCENE-10129: Add RamUsageEstimator.shallowSizeOf() for primitive arrays

### PR DESCRIPTION
**Pull request by stefanvodita**
# Description

`shallowSizeOf(long[])` would call `shallowSizeOf(Object)`, which is slower, but leads to the same result as `sizeOf(long[])`. The same applies to all primitive types.

# Solution

Overload call to `shallowSizeOf()` for primitive arrays so it would not default to `shallowSizeOf(Object)`.

# Tests

Unit test calls `shallowSizeOf()` for primitive arrays and checks that result is the same as calling `sizeOf()`.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/lucene/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Lucene maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.

### CODE REVIEW

**Review by mikemccand — APPROVED** [review]
This looks good to me!  But maybe @dweiss or @uschindler could weigh in?

**Comment by uschindler** [comment]
adding @rmuir

**Review by uschindler — APPROVED** [review]
The pull request is correct, exactly as expected. Thanks.

The problem with the static imports in the test (RamUsageTester - a more thorough class in test framework vs. RamUsageEstimator)should really be sorted out, but that's a test issue unrelated to this PR.

Thanks for mentioning it!

**Comment by uschindler** [comment]
If you could prepare a changes.txt entry in the pr you could make work for me easier. Please also add @rmuir there.
I will merge it then.

**Comment by stefanvodita** [comment]
I added the entry in changes.txt. Let me know if it’s not done correctly as I’m not familiar with the process. Thanks!

**Comment by uschindler** [comment]
Great, I will merge in a moment after workflow ran.

**Pull request merged**
