### PR TITLE
fix wrong serialization by ShapeDocValues

### LINKED ISSUE #11973: ShapeDocValues wrong serialization
### Description

Found by error-prone, looks rather serious to me since it impacts how the shape is serialized to disk. How come no tests fail?

```
/home/rmuir/workspace/lucene/lucene/core/src/java/org/apache/lucene/document/ShapeDocValues.java:553: warning: [LogicalAssignment] Assignment where a boolean expression was expected; use == if this assignment wasn't expected or add parentheses for clarity.
      if (node.triangle.ca = true) {
```

With more context:
```
      // write edge member of original shape
      if (node.triangle.ab == true) {
        header |= 0x10;
      }
      if (node.triangle.bc == true) {
        header |= 0x20;
      }
      if (node.triangle.ca = true) {                        // <-- bug
        header |= 0x40;
      }

      output.writeVInt(header);
```

After fixing this issue, we may enable error-prone `LogicalAssignment` check, since it is the only such issue across the entire codebase: https://errorprone.info/bugpattern/LogicalAssignment

### Version and environment details

_No response_

### PR DESCRIPTION
**Pull request by rmuir**
Here's a fix, and also enabling the error-prone check. But I feel like some sort of testcase should have been failing here all along?

Closes #11973

### CODE REVIEW

**Comment by dweiss** [comment]
Wow. Nice catch.

**Comment by rmuir** [comment]
@nknize any thoughts? sorry i haven't had time to dig into the guts of this, but would be good to get this check enabled

**Comment by nknize** [comment]
Yeah, nice catch @rmuir!!  Thanks for enabling the logical assignment error-prone check. I had no idea that was disabled! 

> I feel like some sort of testcase should have been failing here all along?

💯!  

No test cases failed here because the edge membership boolean is only used in `CONTAINS` queries, which [isn't yet supported](https://github.com/apache/lucene/blob/0a9bb6e2ace2e07512d67dc346ca5d19d473c538/lucene/core/src/java/org/apache/lucene/document/BaseShapeDocValuesQuery.java#L48). Either way, I agree w/ you that we should have an explicit check that the serialization matches what's expected from the original shape. I'll write up a simple one to ensure coverage here. Thanks for catching this!

**Review by nknize — APPROVED** [review]
Nice catch!

**Comment by rmuir** [comment]
@nknize thank you for looking. 

one other related suggestion i have for this code in the future would be to change code such as this:
```
header |= 0x01;
```

to something like this:
```
// named constants grouped together which kinda documents the "format" so it is a bit easier
// these names are just examples and might not be the best ones :)
static final int HAS_LEFT_SUBTREE = 1 << 0;
static final int HAS_RIGHT_SUBTREE = 1 << 1;
... 
header |= HAS_LEFT_SUBTREE;
```

**Pull request merged**
