### PR TITLE
Modernize LineFileDocs.

### PR DESCRIPTION
**Pull request by jpountz**
This replaces `StringField`/`SortedDocValuesField` with `KeywordField` and `IntPoint`/`NumericDocValuesField` with `IntField`.

### CODE REVIEW

**Review by mikemccand — APPROVED** [review]
Thanks @jpountz.  I wonder if luceneutil's hard fork of this source file is also rusty in the same way?

**Comment by jpountz** [comment]
@mikemccand luceneutil is better at remaining up-to-date with Lucene than Lucene itself :) https://github.com/mikemccand/luceneutil/commit/76ff349499fe6226c9ea74c37dd2fa9db3a46272 https://github.com/mikemccand/luceneutil/commit/bb071f72044c5c2ce5df427b45a97820bc4d9be4

**Comment by mikemccand** [comment]
> @mikemccand luceneutil is better at remaining up-to-date with Lucene than Lucene itself :) [mikemccand/luceneutil@76ff349](https://github.com/mikemccand/luceneutil/commit/76ff349499fe6226c9ea74c37dd2fa9db3a46272) [mikemccand/luceneutil@bb071f7](https://github.com/mikemccand/luceneutil/commit/bb071f72044c5c2ce5df427b45a97820bc4d9be4)

Ha!  Wild :)

Maybe we should unfork?  Why does luceneutil need a hard fork here ... couldn't it just depend on Lucene's `test-framework` to pull this dep in?

**Comment by jpountz** [comment]
From a quick check, the luceneutil version has much more complexity around indexing facets, doc values, etc. It's not entirely obvious to me if sharing the code would help or hurt.

**Comment by s1monw** [comment]
I was working on adding some new BWC tests for the parent field and it seems BWC index creation and testing is relying on some things that changed here. Just flagging this for now while I work on a fix.

**Pull request merged**
