### PR TITLE
Check uptTo before score in ReqExclBulkScorer#score.

### PR DESCRIPTION
**Pull request by vsop-479**

### CODE REVIEW

**Comment by jpountz** [comment]
It's not clear to me what problem this is fixing as it is legal to call `bulkScorer.score(collector, acceptDocs, NO_MORE_DOCS, NO_MORE_DOCS)`.

**Comment by vsop-479** [comment]
> it is legal to call bulkScorer.score(collector, acceptDocs, NO_MORE_DOCS, NO_MORE_DOCS).

Thanks for reviewing @jpountz . Do you think we can return `NO_MORE_DOCS` immediately when `min` is NO_MORE_DOCS in `BulkScorer#score`?

**Comment by jpountz** [comment]
This would be correct, but I don't think we should do it. If there is a `DocIdSetIterator` that is slow at `advance(NO_MORE_DOCS)`, this is where we should add a special check.

**Comment by vsop-479** [comment]
I added this check in `ReqExclBulkScorer#score` because i found `upTo` would be `NO_MORE_DOCS` after the loop in some case, e.g: `max` is `NO_MORE_DOCS`, and result in call `req.score(collector, acceptDocs, NO_MORE_DOCS, NO_MORE_DOCS)`.

Maybe it is useless, I will close it.

**Pull request closed without merging**
