### PR TITLE
NeighborQueue set incomplemete false when call clear

### PR DESCRIPTION
**Pull request by tang-hi**
### Description
solve the bug that @msokolov mentioned in [PR](https://github.com/apache/lucene/pull/12255#issuecomment-1553088549)

### CODE REVIEW

**Review by zhaih — APPROVED** [review]

**Comment by tang-hi** [comment]
@zhaih Hi,may be we could merge this PR?

**Comment by zhaih** [comment]
Ah sorry! Almost forgot this PR, I'll merge and backport it now

**Comment by tang-hi** [comment]
> Ah sorry! Almost forgot this PR, I'll merge and backport it now

thanks! 😄

**Comment by zhaih** [comment]
Oh just realized @msokolov has already made the very same change 2 weeks ago LOL https://github.com/apache/lucene/commit/6b51cce0b8404d79468dfee0c80d9992d5234960 
Wonder why doesn't github show the correct diff hmmm..

**Pull request merged**
