### PR TITLE
LUCENE-9997 Second pass smoketester fixes for 9.0

### PR DESCRIPTION
**Pull request by janhoy**
https://issues.apache.org/jira/browse/LUCENE-9997

This is the second pass of changes to smoketester for the new gradle build.

* Adapt to the new source-tgz file layout
* Tested gradlew commands
* Change `--test-java12` with `--test-java17`
* Make Lucene Demo work with new `-Dsmoketester=true`

### CODE REVIEW

**Comment by janhoy** [comment]
The smoketester is tested locally and currently stops at **verify maven artifact sigs**
```
command "gpg --homedir /tmp/smoke_lucene_9.0.0_537d435f5ee7c884221371a59673b878d82f6ffa_18/lucene.gpg --verify /tmp/smoke_lucene_9.0.0_537d435f5ee7c884221371a59673b878d82f6ffa_18/maven/org/apache/lucene/lucene-analysis-common/9.0.0/lucene-analysis-common-9.0.0-javadoc.jar.asc /tmp/smoke_lucene_9.0.0_537d435f5ee7c884221371a59673b878d82f6ffa_18/maven/org/apache/lucene/lucene-analysis-common/9.0.0/lucene-analysis-common-9.0.0-javadoc.jar" failed:
gpg: can't open '/tmp/smoke_lucene_9.0.0_537d435f5ee7c884221371a59673b878d82f6ffa_18/maven/org/apache/lucene/lucene-analysis-common/9.0.0/lucene-analysis-common-9.0.0-javadoc.jar.asc': No such file or directory
gpg: verify signatures failed: No such file or directory
```
Looks like the gradle build does not sign the maven artifacts? @dweiss do you know?

**Comment by janhoy** [comment]
Reporoduce like this
```
git checkout -b janhoy-lucene9997-smoketester-part-2 main
git pull https://github.com/janhoy/lucene.git lucene9997-smoketester-part-2

python3 -u dev-tools/scripts/buildAndPushRelease.py \
      --push-local "/tmp/lucene-release" \
      --rc-num 1 \
      --sign YOUR-KEY-ID \
      --gpg-pass-noprompt \
      --dev-mode 
```
Then run the smoketester command line provided.

**Review by mocobeta — APPROVED** [review]
Looks good to me (I haven't run this yet, I'll find the time... please go ahead).

**Comment by dweiss** [comment]
I merged with main where the artifact-signing changes landed. The buildAndPushRelease.py works for me (although it does create that stray file so I suspect it won't run properly unless in dev mode).

**Comment by janhoy** [comment]
> I merged with main where the artifact-signing changes landed. The buildAndPushRelease.py works for me (although it does create that stray file so I suspect it won't run properly unless in dev mode).

Thanks. I get the `gpg: signing failed: Cannot allocate memory` error with gpg, caused by gpg daemon running out of mem during many parallell signing commands. I found a workaround by adding `auto-expand-secmem` to `~/.gnupg/gpg-agent.conf` and then running `gpg-connect-agent killagent /bye` to restart the agent, and it works. This could perhaps be documented as a prerequisite for using gpg, if you don't want to run serially. Or the script could run the main build in parallel and then run just the signing serially.

**Comment by janhoy** [comment]
@mocobeta I got the same as you - looks like LICENSE and NOTICE are not copied into the maven jars. Strange, since they exist in the binary-release jars. Looks like maven task re-build the jars.. Could not the maven task use the pre-built jars that already have NOTICE and LICENSE?

I also notice that `MANIFEST.MF` is empty in the maven jars, simply one line, which is also wrong:
```
Manifest-Version: 1.0
```
I created https://issues.apache.org/jira/browse/LUCENE-10186 for maven artifacts.
Re-opened LUCENE-10174 for the buildAndPushRelease changes.

**Comment by dweiss** [comment]
I use Windows - these scripts are not compatible. I don't think we have to make it a priority to make them compatible. Too many variables to think of.

**Pull request merged**
