### PR TITLE
Remove broken .toArray from Long/CharObjectHashMap entirely

### LINKED ISSUE #13761: IntObjectHashMap.values().toArray() method throws ClassCastException
### Description

The ClassCastEx is thrown when the `IntObjectHashMap.values().toArray()` method is called with a type other than `Object`, and of course the same exception occurs with `CharObjectHashMap` and `LongObjectHashMap`. The issue can be reproduced with the following test.
```
@Test
  public void testStringMapValues() {
    IntObjectHashMap<String> map = new IntObjectHashMap<>();
    map.put(1, "a");
    map.put(2, "b");
    map.put(3, "c");
    String[] values = map.values().toArray();
  }
```

There are several options to fix the issue.
1. change the return value to `Object[]`;
2. mimic the `ArrayList.toArray(T[])` method to pass a `T[]` parameter;
3. replace the `toArray` method with a `asList` method, and return a `List<T>`.

IMO, either option 2 or 3 would be acceptable. Any thought?

### Version and environment details

_No response_

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description

Fixes #13761

### CODE REVIEW

**Comment by bugmakerrrrrr** [comment]
@dweiss would you mind taking a look at this if you get a chance

**Comment by dweiss** [comment]
Sure, thank you. The linter has failed - seems like an unused method. Please correct and perhaps add a CHANGES.txt entry with an attribution to you?

**Comment by bugmakerrrrrr** [comment]
@dweiss Thanks. I've fixed the lint error, PTAL.

**Review by dweiss — APPROVED** [review]

**Comment by dweiss** [comment]
Thank you!

**Pull request merged**
