### PR TITLE
Bump the codec version to 10.0.

### PR DESCRIPTION
**Pull request by jpountz**
Lucene100Codec is the exact same file format as Lucene912Codec. This codec dance just makes things slightly easier to reason about since our backward compatibility guarantees are aligned with major version: once we drop support for 9.x indices, we can remove all `Lucene9XXCodec`s.

### CODE REVIEW

**Comment by benwtrent** [comment]
Codec 💯 ! 😂

**Review by mikemccand — APPROVED** [review]

**Review by ChrisHegarty — APPROVED** [review]
Lucene 100. I love it!  LGTM

**Comment by mikemccand** [comment]
I was in a meeting yesterday and someone told me "oh we are using a very recent Lucene release, 9.1".  And I asked them to double check ... and it was 9.10 they were using.  This conflict between floating point numbers and release versioning sure is tricky!

**Comment by uschindler** [comment]
Thanks for merging @ChrisHegarty, I missed that PR.

**Pull request merged**
