### PR TITLE
Fix failure to load larger data sets in KnnGraphTest

### PR DESCRIPTION
**Pull request by benwtrent**
When running the `reindex` task with KnnGraphTester, exceptionally large
datasets can be used. Since mmap is used to read the data, we need to know the
buffer size. This size is limited to Integer.MAX_VALUE, which is inadequate for
larger datasets.

So, this commit adjusts the reading to only read a single vector at a time.

### CODE REVIEW

**Comment by benwtrent** [comment]
@jtibshirani or @msokolov care to review? The bug was introduced back in https://github.com/apache/lucene/pull/1054

**Comment by jtibshirani** [comment]
Thanks for fixing this @benwtrent ! I wonder if we could take the simpler approach of just opening the file, and iterating through the vectors one by one. I don't think there's a clear performance benefit to mmapping sections of the file, since we are always just iterating through the vectors in order (to then index them, search them one-by-one, etc.)

**Comment by benwtrent** [comment]
@jtibshirani My goal here was to fix the bug with as much as the original design as possible. I didn't want to spend a bunch of time re-factoring this code. 

I am open to simply read bytes from the file directly instead of using mmap. What say you @msokolov ?

**Review by jtibshirani — COMMENTED** [review]
This looks good, I like how simple it is! I don't think there should be one, but is there any effect on the result of ann-benchmarks? Maybe you could run against glove-100-angular with this change just to double-check QPS is unaffected?

**Comment by benwtrent** [comment]
@jtibshirani I confirmed that on my M1 Macbook, there is no significant change in QPS, I tested glove-100-angular and deep-image-96-angular

**Review by jtibshirani — APPROVED** [review]
Looks good to me 👍 I'll merge and backport shortly.

**Pull request merged**
