### PR TITLE
Removing all deprecated TopScoreDocCollector + TopFieldCollector methods (#create, #createSharedManager)

### LINKED ISSUE #13499: Remove the @Deprecated methods from TopScoreDocCollector and TopFieldCollector
### Description

These methods were deprecated in https://github.com/apache/lucene/pull/240 which is part of Lucene 10.0.

Since they are not marked for deprecation in Lucene 9.x, they will not be removed with Lucene 10.0 release (unless we want to deprecate them in 9.x in another backport commit?), but I still think we should remove the internal usage so it will be quicker to remove the methods when the time comes.

I'll submit a PR for a 1:1 change to remove the usages.

### PR DESCRIPTION
**Pull request by slow-J**
Following up on: https://github.com/apache/lucene/pull/13500

These methods already marked for deprecation in 9.x and we previously removed all internal use of these methods in 10.0 (in https://github.com/apache/lucene/pull/13500).

Tested with: `./gradlew tidy && ./gradlew test`

Closes: #13499

### CODE REVIEW

**Review by javanna — APPROVED** [review]
Looks great, thank you!

**Comment by javanna** [comment]
Thanks again @slow-J . Heads up, I moved the changes entry to the "API changes" section above after merging, I did not catch this while reviewing :)

**Comment by slow-J** [comment]
My bad, sorry for the mistake, thanks for catching it and the review!

**Comment by javanna** [comment]
> My bad, sorry for the mistake, thanks for catching it and the review!

no big deal, just a small oversight. Cheers!

**Pull request merged**
