### PR TITLE
Use Arrays.compareUnsigned instead of iterating compare.

### PR DESCRIPTION
**Pull request by vsop-479**
Similar to `SegmentTermsEnumFrame`, we can use `Arrays.compareUnsigned` instead of iterating compare, in `SegmentTermsEnum.seekCeil` and `SegmentTermsEnum.seekExact`.

### CODE REVIEW

**Comment by vsop-479** [comment]
@mikemccand 

Please take a look when you get a chance.

**Comment by rmuir** [comment]
This looks like a good improvement, these `Arrays` methods become much faster than the home-written loops for longer arrays.

**Review by uschindler — APPROVED** [review]
Great. Better replace all those handwritten loops with Arrays methods. We did this for the first time to improve Lucene 8.x with Java9+ (using MR-JAR).

**Review by mikemccand — APPROVED** [review]
Looks great, thank you @vsop-479!  I'll merge soon.

**Comment by mikemccand** [comment]
Woops, there are now conflicts here (from the binary search PR) -- maybe you could resolve them @vsop-479, and add a `CHANGES.txt` entry too?  Thanks!

**Comment by vsop-479** [comment]
@mikemccand 
I resolved the conflicts, and added a `CHANGES.txt` entry.
Please take a look when you get a chance.

**Pull request merged**
