### PR TITLE
remove username from MANIFEST.MF in build artifacts

### PR DESCRIPTION
**Pull request by magibney**
Following on discussion from #12094

### CODE REVIEW

**Review by uschindler — APPROVED** [review]

**Review by rmuir — APPROVED** [review]

**Review by janhoy — APPROVED** [review]

**Comment by gus-asf** [comment]
While we are at it maybe we should remove the timestamp too. It really ought to be a revision hash. This moves toward making the build repeatable. It's not actually important which day it was built, what's important is which revision it was built with and if there were any uncommitted changes. I implemented this in a couple of my projects (see https://github.com/nsoft/uno-jar/blob/master/core/build.gradle#L143 for example...)

**Comment by magibney** [comment]
MANIFEST.MF `ImplementationVersion` field does include the revision hash -- `${gitRev}` in the line that's edited in this PR. I think the build date/time is a potentially useful bit of metadata, if nothing else to fall back on to differentiate artifacts for the same commit hash.

**Comment by gus-asf** [comment]
I don't understand what you mean by differentiate artifacts for the same commit hash. How would a time stamp do this? If they are different artifacts the contents and the name are all different, and a timestamp doesn't actually tell you which is which anyway. If they are the "same" artifact from the same commit hash, every bit of difference is a bad thing, creating doubt about whether or not they are actually equivalent. The point of repeatability is that if you build the same artifact from the same commit hash it should contain the same bytes in the same order and the sha/md5 hashes should be the same. Putting timestamps and usernames in the files makes them non-reproducible (there's also some question of how much detail about the build OS is worth while for this too, but that's a harder question)

So adding information that tells the user what conditions are necessary to reproduce the artifact is good (JDK, OS, etc) but adding a timestamp that they can't ever hope to reproduce (without mindless post processing doesn't help.

As I said it would only be progress towards a goal which takes additional changes to realize. For example zips and jars also embed time stamps, but there are ways of dealing with that... https://wiki.debian.org/ReproducibleBuilds/TimestampsInZip

In any case this is a set of folks who's arguments seemed persuasive to me: https://reproducible-builds.org/

**Comment by janhoy** [comment]
As long as we have not decided to aim for reproducible builds (it will take lots and lots of effort) there’s little use in such a change..

You should present your proposal on the dev list as a first step.

**Comment by magibney** [comment]
I think reproducible builds would be an great goal! (and second Jan's suggestion of proposing on dev list).

Paradoxically, further consideration of the issues that "reproducible builds" seek to address has reinforced some nagging doubts I had about removing the userid from the manifest.

It's about trust. We don't have `@author` tags etc. in code, but the project does have usernames all over it -- in the form author/committer fields of commits. The process of preparing a release is mechanical, but it definitely requires trust in the RM (`>=` trust required for a commit). And I realize that the gpg signing of release artifacts fills this role (and in a more substantial way), so username in MANIFEST.MF is arguably redundant. But I think broadcasting the identity of the user who produced the artifact makes sense. When the same user _signs_ the artifacts, there's an implicit endorsement of the build user/agent as recorded in the MANIFEST.MF.

I'm not going to make an issue of it one way or another; and I'm still happy to merge this PR. But tbh my personal inclination would be to leave the userid in the manifest. It's trust and provenance for the "last mile" that bridges the gap between source code and the artifacts that most users will actually interact with; and even if in a sense it's redundant, declaring it explicitly as part of the build artifact strikes me as appropriate.

**Comment by gus-asf** [comment]
Discussion email sent.

**Comment by rmuir** [comment]
> It's about trust. We don't have `@author` tags etc. in code, but the project does have usernames all over it -- in the form author/committer fields of commits. The process of preparing a release is mechanical, but it definitely requires trust in the RM (`>=` trust required for a commit). And I realize that the gpg signing of release artifacts fills this role (and in a more substantial way), so username in MANIFEST.MF is arguably redundant. But I think broadcasting the identity of the user who produced the artifact makes sense. When the same user _signs_ the artifacts, there's an implicit endorsement of the build user/agent as recorded in the MANIFEST.MF.

horseshit.

Trust means release was cryptographically signed by GPG. That is it and only it.

Please remove this nonsense field, again, the issue is that some apps such as solr display it, and it causes harassment of the user whose username is in there.

And I'll state again, if it isn't removed, I'm going to make sure there's a release with something extremely offensive in there. Because there needs to be an end to this.

**Review by jpountz — APPROVED** [review]

**Comment by magibney** [comment]
Merged/backported to make this available for 9.5 release.

**Comment by uschindler** [comment]
Thanks for merging this. After your last message I was about to do it on my own.

**Comment by magibney** [comment]
>After your last message I was about to do it on my own.

Thanks, and sorry for the mixed signals. Just wanted to make sure it got done in time for 9.5!

**Pull request merged**
