### PR TITLE
LUCENE-10159: Fix invalid access in sorted set dv

### PR DESCRIPTION
**Pull request by dnhatn**
We introduced invalid accesses for sorted set doc values in [LUCENE-9613](https://issues.apache.org/jira/browse/LUCENE-9613). However, the issue has been unnoticed because the ordinals in doc values tests aren't complex enough to use high packed bits, and the [3 padding ](https://github.com/apache/lucene/blob/cdfa11b1582ead89547b08c4c41c13712550d4ba/lucene/core/src/java/org/apache/lucene/util/packed/DirectWriter.java#L152-L155)bytes make these invalid accesses perfectly fine. To reproduce this issue, we need to use at least 20 bits per value for the ordinals.

The Machine Learning team at Elastic uses a complex doc values setup and [uncovers](https://github.com/elastic/elasticsearch/issues/78785) this bug with a Elasticsearch 8.0 nightly build. Fortunately, this is an unreleased bug in both Lucene and Elasticsearch.

### CODE REVIEW

**Comment by dnhatn** [comment]
@rmuir I pushed https://github.com/apache/lucene/pull/389/commits/4ee7a6bd90d275a7df193a87aea3836c65a786ff to write more trailing bytes. Would you mind taking another look? Thank you!

**Comment by rmuir** [comment]
Also, given that writing a sortedset is really just a sortednumeric, isn't sortednumeric impacted by the bug too? would it easier to test for this bug with a sortednumeric unit test? The unit test is quite complicated.

**Comment by jpountz** [comment]
I think the test is useful to double check that the change is fixing the issue but I'm not sure if we should merge it: it wouldn't be manageable to have tests at the doc-values format test case's level for every possible number of bits per ord. This invalid access issue is something that I would have expected AssertingDocValuesFormat to catch, maybe we should review the assertions we have there around methods that shouldn't be called when iterators are not positioned?

**Comment by dnhatn** [comment]
> Seems a lot easier to just test this via SORTED_NUMERIC. There isn't any point in testing SORTED_SET as it only makes things more difficult.

@rmuir @jpountz Thanks for your reviews and discussion. I think the issue only affects the sorted_set dv. I've simplified the unit test and applied the solution that you both discussed. Can you give it another look.

**Comment by rmuir** [comment]
> Sorted set doc values don't have a docValueCount API, they're just expected to return NO_MORE_ORDS when all ords have been exhausted.

Thanks, sorry I had completely forgotten that, and that's the inconsistency that is root cause of the trouble here (padding/alignment that hid the bug didn't help). SortedSet was added first, and not having a count method may not have been the best decision. I am not sure it is even slightly helpful to save space if you want to implement as a vint-list, because you still need to store "some kind of length" to have per-document random access.

With the SortedNumeric, there is no available sentinel value that can be used (without boxing or something nasty), so we had to do a count method.

Maybe it is worth a second thought, if the SortedSet could get a count method to be more consistent and efficient like the numeric one. It would have costs (e.g. we'd need to hard-break the api in a way that it isnt trappy on users), but it would also have benefits: e.g. none of this state-keeping inside the codec, instead based on a more natural loop that happens outside of the codec code. Then AssertingCodec would really detect issues, maybe the compiler can do a better job with it, etc.

**Review by rmuir — APPROVED** [review]

**Pull request merged**
