### PR TITLE
LUCENE-9955: Reduced state of stored fields readers.

### PR DESCRIPTION
**Pull request by jpountz**
This removes most state from stored fields readers.

#10994

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
Great find, LGTM.

**Comment by rmuir** [comment]
it would be great to open a followup "wish" issue at least to think about ways we might remove the stored fields and term vectors threadlocals completely? The difficult part is figuring out how to make the api easy, but i feel like it should be possible, e.g. something minimally invasive like:

```java
// old
Document d1 = reader.doc(doc1);
Document d2 = reader.doc(doc2);
// new
var storedfields = reader.getStoredFields();
Document d1 = storedfields.doc(doc1);
Document d2 = storedfields.doc(doc2);
``` 

then the `storedfields` would just be garbage-collected normally like any other lucene index api. So you'd still prevent `clone()/shared dictionary/whatever` resources from happening per-document, but they'd happen per-query (is this good enough?)

Anyway, just worth a thought for the future. I hate making these apis difficult to use, but at the same time I don't like how trappy the threadlocals can be (especially if you arent using fixed threadpools etc).

**Comment by jpountz** [comment]
Agreed we should look into this! I opened https://issues.apache.org/jira/browse/LUCENE-9959.

**Comment by rmuir** [comment]
-1 to this code change which started all the new public classes/renaming problems

**Pull request closed without merging**
