### PR TITLE
Add support for stored fields to MemoryIndex

### PR DESCRIPTION
**Pull request by romseygeek**

### CODE REVIEW

**Review by mkhludnev — APPROVED** [review]

**Review by jpountz — APPROVED** [review]

**Comment by uschindler** [comment]
Hi,
I have no idea, what the reason for this issue/PR is (can I have a bit more information, is there an issue, too?), because MemoryIndex is mostly used for the old highlighting. I am fine to add stored fields to the MemoryIndex, but from my perspective the whole encoding looks useless: Why do we need to encode the stored contents at all into a byte[]? MemoryIndex only has one document and like terms, why not simply use a `Map<String,Object[]>` as datastore. `Object` can be any type here. To me it looks like an overhead to encode values on indexing and decode them, although the encoded values are never exposed.
Merging MemoryIndex into another conventional index is no issue, as MemoryIndexReader does not implement CodecReader at all, so Bulk Merging won't work and merging will use the LeafReader interface.

**Comment by romseygeek** [comment]
MemoryIndex is used by the monitor module and by the ES percolator as well, and that's where we may have issues - there are some slow queries in ES that use stored fields to search non-indexed documents, and they won't work when run against a MemoryIndex.

We need to store the types of the data so that we can call the correct methods on StoredFieldsVisitor.  But you're right, it might be easier to store as a Map and then use instanceof checks to get the types - will give that a go and see if it works!

**Comment by rmuir** [comment]
> there are some slow queries in ES that use stored fields to search non-indexed documents, and they won't work when run against a MemoryIndex.

Sorry, this seems like its the problem you should fix. not adding stored fields to memoryindex!

**Comment by rmuir** [comment]
i hate to be that guy, but -1, this isn't a real use-case. we all know you shouldnt search on stored fields. shame on you.

**Comment by romseygeek** [comment]
> you shouldnt search on stored fields

It works surprisingly well as a confirmation phase in a two-phase query!

The fact that memory indexes don't support stored fields also makes highlighting in monitor/percolator more annoying.  And with Uwe's suggested refactor it's a very minimal change.  It's also I think the only LeafReader functionality apart from Vectors that MemoryIndex doesn't support? It just seems a weird omission.

**Comment by rmuir** [comment]
i'm sticking with my -1. i will also keep close watch on all stored fields issues now, to try to make sure it isn't for "searching abuse cases" like this.

I think, maybe we should use stackwalker and throw exception if someone retrieves storedfields from a query subclass.

**Comment by romseygeek** [comment]
To clarify, is your objection to adding support for `document()` to the only `LeafReader` implementation that doesn't have it, or is it that `document()` is a method on `LeafReader` in the first place?

**Comment by rmuir** [comment]
it doesn't need stored fields because stored fields aren't for searching on. PERIOD.

**Review by uschindler — APPROVED** [review]
Hi,
technically I have no complaints with this PR. I agree with Robert that the use-case looks wierd, but this is a simple change and goes in line with Robert's changes in th other PR.

I'd use the new pattern matching for switches - but it is preview in 17, but you already used pattern matching for the instanceof check: cool!

**Comment by romseygeek** [comment]
The elasticsearch highlighter for the percolator has been working for years with a really annoying workaround, because MemoryIndex is the only LeafReader implementation in lucene that doesn't support the `document` method, and that this small PR will allow me to remove.

**Comment by rmuir** [comment]
> The elasticsearch highlighter for the percolator has been working for years with a really annoying workaround, because MemoryIndex is the only LeafReader implementation in lucene that doesn't support the `document` method, and that this small PR will allow me to remove.

Thanks @romseygeek this is an actual valid use-case (as opposed to searchiing on stored fields which is NOT). please proceed. Though I will mention, its not true about only LeafReader without `document`, trust me, there are others, i know (look in IndexingChain.java if you need an example).

**Pull request merged**
