### PR TITLE
Reduce the overhead of ImpactsDISI.

### PR DESCRIPTION
**Pull request by jpountz**
`ImpactsDISI` is nice: you give it an `ImpactsEnum`, typically coming from the `PostingsFormat` and it will automatically skip hits whose score cannot be greater than the minimum competitive score. This is the class that yields 10x or more speedups on top-level `TermQuery`s compared to exhaustive evaluation.

However, when nested under a disjunction or a conjunction, `ImpactsDISI` typically adds more overhead than it enables skipping. The reason is that on a disjunction `a OR b`, the minimum competitive score of `a` is the minimum score for the disjunction minus the maximum score of `b`. While this sort of propagation of minimum competitive scores down the query tree sometimes helps, it does hurt more than it helps on average, because `ImpactsDISI` adds quite some overhead and the per-clauses minimum scores are usually so low that they don't actually enable skipping hits. I looked into reducing this overhead, but a big part of it is the additional virtual call, so the only way to get rid of this overhead is to not wrap with an `ImpactsDISI` at all.

This means that scorers need a way to know whether they are producing the top-level score, or whether they are producing a partial score that then gets combined into the top-level score. Term queries would then only wrap with `ImpactsDISI` when they produce the top-level score. Note that this does not only include top-level term queries, but also conjunctions that have a single scoring clause (`a #b`) or combinations of a term query and one or more prohibited clauses (`a -b`).

### CODE REVIEW

**Comment by jpountz** [comment]
Opened this PR as a draft to get feedback on the API (if any). Existing tests pass, but I plan on adding more tests before merging as well. Here are the results of this PR on wikimedium10m. Top-k queries on disjunctions and conjunctions get a significant performance boost by removing this overhead.

```
                            TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
                    OrHighNotMed      416.61      (4.8%)      399.18      (5.6%)   -4.2% ( -13% -    6%) 0.074
                    OrHighNotLow      534.35      (4.8%)      512.73      (5.7%)   -4.0% ( -13% -    6%) 0.087
                   OrHighNotHigh      340.89      (4.4%)      327.66      (5.1%)   -3.9% ( -12% -    5%) 0.069
                   OrNotHighHigh      395.37      (3.9%)      380.50      (4.7%)   -3.8% ( -11% -    5%) 0.051
                    OrNotHighMed      511.30      (1.9%)      497.11      (3.7%)   -2.8% (  -8% -    2%) 0.034
                        HighTerm      597.37      (6.3%)      580.82      (4.1%)   -2.8% ( -12% -    8%) 0.244
                         MedTerm      802.79      (5.3%)      783.67      (3.4%)   -2.4% ( -10% -    6%) 0.235
                         LowTerm     1092.20      (4.6%)     1069.37      (4.6%)   -2.1% ( -10% -    7%) 0.306
                          IntNRQ       61.95     (14.7%)       61.33     (16.1%)   -1.0% ( -27% -   34%) 0.883
               HighTermMonthSort     5037.79      (3.0%)     4992.75      (2.8%)   -0.9% (  -6% -    5%) 0.494
             MedIntervalsOrdered       23.71      (3.8%)       23.55      (7.2%)   -0.7% ( -11% -   10%) 0.793
                        PKLookup      247.34      (3.2%)      245.97      (3.0%)   -0.6% (  -6% -    5%) 0.688
               HighTermTitleSort      177.34      (4.9%)      176.39      (3.9%)   -0.5% (  -8% -    8%) 0.785
             LowIntervalsOrdered       35.58      (3.2%)       35.43      (5.2%)   -0.4% (  -8% -    8%) 0.829
                    OrNotHighLow     1495.12      (2.1%)     1489.60      (2.4%)   -0.4% (  -4% -    4%) 0.718
           HighTermDayOfYearSort      407.38      (1.4%)      405.96      (1.1%)   -0.4% (  -2% -    2%) 0.537
                       LowPhrase       68.81      (2.4%)       68.66      (1.3%)   -0.2% (  -3% -    3%) 0.796
                         Respell       85.14      (1.2%)       85.05      (2.1%)   -0.1% (  -3% -    3%) 0.884
                     MedSpanNear       28.29      (2.6%)       28.27      (3.3%)   -0.1% (  -5% -    5%) 0.944
                        Wildcard      157.04      (3.0%)      157.00      (3.5%)   -0.0% (  -6% -    6%) 0.987
                      TermDTSort      194.42      (2.2%)      194.53      (1.1%)    0.1% (  -3% -    3%) 0.943
                     LowSpanNear       84.26      (2.5%)       84.32      (3.0%)    0.1% (  -5% -    5%) 0.950
                      HighPhrase       42.16      (3.0%)       42.23      (2.2%)    0.2% (  -4% -    5%) 0.892
                       MedPhrase      132.52      (2.5%)      132.78      (1.4%)    0.2% (  -3% -    4%) 0.827
                    HighSpanNear       21.37      (3.7%)       21.44      (4.5%)    0.3% (  -7% -    8%) 0.857
                 LowSloppyPhrase       64.26      (2.1%)       64.62      (2.4%)    0.6% (  -3% -    5%) 0.575
            HighTermTitleBDVSort       21.59      (1.6%)       21.79      (2.3%)    0.9% (  -2% -    4%) 0.281
                         Prefix3      299.62      (2.8%)      302.58      (3.9%)    1.0% (  -5% -    7%) 0.517
                 MedSloppyPhrase       73.65      (3.0%)       74.38      (3.7%)    1.0% (  -5% -    7%) 0.503
            HighIntervalsOrdered        6.22      (4.5%)        6.30      (4.7%)    1.2% (  -7% -   10%) 0.565
                HighSloppyPhrase       11.09      (3.7%)       11.22      (3.4%)    1.2% (  -5% -    8%) 0.449
                      AndHighLow     1246.88      (2.8%)     1262.41      (2.7%)    1.2% (  -4% -    6%) 0.311
                          Fuzzy2       86.08      (1.1%)       87.67      (1.2%)    1.9% (   0% -    4%) 0.000
                          Fuzzy1      121.95      (1.0%)      124.27      (1.3%)    1.9% (   0% -    4%) 0.000
                      AndHighMed      199.47      (5.3%)      234.03      (3.0%)   17.3% (   8% -   27%) 0.000
                       OrHighLow      413.43      (7.0%)      485.29      (4.6%)   17.4% (   5% -   31%) 0.000
                       OrHighMed      191.17      (5.6%)      225.07      (3.7%)   17.7% (   8% -   28%) 0.000
                     AndHighHigh       92.26      (5.6%)      108.84      (3.2%)   18.0% (   8% -   28%) 0.000
                      OrHighHigh       59.24      (9.2%)       73.86      (6.9%)   24.7% (   7% -   44%) 0.000
```

**Comment by jpountz** [comment]
To give a bit more context about why I ended up adding `ScorerSupplier#setTopLevelScoringClause`: I considered other options, such as:
 - adding a new `ScoreMode` but `Query#createWeight` is too early to make this kind of decision. E.g. if your query is `a OR b`, `a` may be the top-level scoring clause if `b` produces a null scorer, so `createWeight` is not a good fit.
 - adding a new parameter to `Weight#scorer`, but again it's too early for the same reason. With query `a OR b`, if Lucene creates a scorer for `a` first assuming it will be a clause of a boolean query, but if then `b` produces a `null` scorer, `a` will be the top-level scoring clause, but it's already been created as a non-top-level scoring clause.
 - adding a similar `setTopLevelScoringClause` on `Scorer`, but I did not like mutating scorers

So a setter on `ScorerSupplier` felt like the best place to set this kind of information.

**Comment by msokolov** [comment]
I'm concerned that we would disable impacts-based skipping in cases where it could help. For example suppose you have a sparsely-populated field a, that when it is present has a big impact on the score, and a regular field b that is present on every doc. For a disjunction of these, as soon as you exhaust the a-matches it will degenerate into a single term query. I guess this isn't the common case, but will there be a way to make use of information like that with this API? How can callers specify that they *do* want skipping to be applied in some case?

**Comment by jpountz** [comment]
I remember seeing cases when propagating the minimum score on inner clauses and take advantage of their skipping logic helped when I started working on dynamic pruning indeed, but there have been many changes since then and I can't easily find queries that perform better when propagating anymore.

I suspect that one change that plays a role here was the introduction of block-max indexes. Since minimum competitive scores are only allowed to go up, we can only propagate a minimum score to an inner clause of a boolean query that is equal to the minimum competitive score of the boolean query minus the sum of the **global** maximum scores of all other clauses. This gives `BooleanQuery` better score bounds to work with than its inner `TermQuery`s.

For instance I tried to reproduce the case that you suggested by taking a very high-frequency term on wikimedium10m: `ref` (docFreq=877152, maxScore ~= 1) and a low-frequency term: `quark` (docFreq=566, maxScore ~=8), and both conjunctions and disjunctions still run faster with this change. I only managed to make the query slower with this change by putting a boost of 1000 on the high-frequency term. In that case, propagating the minimum competitive score helps because `BooleanQuery` only knows how to skip one block at a time right now while `TermQuery` is able to look at impacts at higher levels in skip lists to skip many blocks at once.

Something also worth noting is that queries that would benefit from propagating the minimum score would generally be queries where a single clause dominates the overall score, and these queries are already handled quite efficiently by boolean queries. On the other hand, queries where MAXSCORE/WAND struggle to help (e.g. because the k value is high, because there are many clauses, or because clauses have suboptimal score upper bounds) get a higher overhead due to the wrapping with `ImpactsDISI`. So the current approach tends to make slow queries slower in exchange of potentially making fast queries faster, which is usually not the best trade-off.

> How can callers specify that they do want skipping to be applied in some case?

I guess we could have some heuristics when to tell some inner clause that they should skip based on their minimum score. E.g. maybe we could do this when we have a clause whose max score accounts for more than X% of the total score or something along these lines, which suggests that propagating maximim scores to this inner clause may help. But it also makes things more complicated API-wase since scorer suppliers don't have access to max scores.

**Comment by jpountz** [comment]
@msokolov I wonder if my above reply addresses your concerns? I'm happy to run more tests if there are other cases you are concerned about. I'm interested in trying to get this change in given how it gives a 15-20% speedup to both conjunctions and disjunctions.

**Comment by msokolov** [comment]
Adrien, thanks for investigating the extreme cases. I think it makes sense to realize these gains and worry about any other losses (which seem largely theoretical at this point) later if we can find a common case that's worth focusing on. Nice improvement here, as far as I'm concerned you should please go ahead and merge

**Comment by jpountz** [comment]
This change is ready for review.
 - `TermQuery` and `FeatureQuery` implement the new API.
 - To keep the PR small, `PhraseQuery`, `ConstantScoreQuery` and `SynonymQuery` do not implement this new API even though they could, I left TODOs.
 - `BooleanQuery` and `DisjunctionMaxQuery` take advantage of the new API to only wrap iterators of inner clauses with an `ImpactsDISI` when appropriate and get a speedup.

**Comment by jpountz** [comment]
I plan on merging soon if there are no objections.

**Comment by jpountz** [comment]
Another benchmark run on the last commit to make sure it still works as expected, and wikibigall this time instead of wikimedium10m:

```
                            TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
               HighTermMonthSort     4813.12      (2.6%)     4760.12      (2.7%)   -1.1% (  -6% -    4%) 0.193
                         Prefix3      286.82      (5.0%)      285.78      (4.4%)   -0.4% (  -9% -    9%) 0.809
                    HighSpanNear        8.01      (2.1%)        7.99      (2.8%)   -0.3% (  -5% -    4%) 0.692
                     MedSpanNear        7.14      (1.5%)        7.14      (2.4%)   -0.1% (  -3% -    3%) 0.854
                          IntNRQ      109.71     (15.0%)      109.82     (15.0%)    0.1% ( -25% -   35%) 0.983
                HighSloppyPhrase        3.52      (5.2%)        3.53      (3.8%)    0.1% (  -8% -    9%) 0.942
                     LowSpanNear       43.43      (1.4%)       43.49      (2.1%)    0.1% (  -3% -    3%) 0.808
                        PKLookup      224.68      (1.9%)      225.84      (2.9%)    0.5% (  -4% -    5%) 0.500
                 LowSloppyPhrase       17.55      (3.6%)       17.65      (3.0%)    0.6% (  -5% -    7%) 0.556
           HighTermDayOfYearSort      244.66      (1.7%)      246.26      (2.0%)    0.7% (  -2% -    4%) 0.264
                         Respell       75.37      (1.5%)       75.92      (2.0%)    0.7% (  -2% -    4%) 0.195
                 MedSloppyPhrase       13.14      (3.9%)       13.24      (2.9%)    0.8% (  -5% -    7%) 0.482
                        Wildcard       65.52      (3.5%)       66.43      (3.5%)    1.4% (  -5% -    8%) 0.213
                          Fuzzy1      139.90      (1.6%)      145.17      (1.5%)    3.8% (   0% -    6%) 0.000
                          Fuzzy2      104.47      (1.6%)      108.44      (1.5%)    3.8% (   0% -    6%) 0.000
                       LowPhrase       45.82      (3.3%)       48.13      (3.4%)    5.0% (  -1% -   12%) 0.000
                       MedPhrase       60.75      (3.7%)       64.16      (3.6%)    5.6% (  -1% -   13%) 0.000
                      HighPhrase       49.20      (3.9%)       52.11      (3.9%)    5.9% (  -1% -   14%) 0.000
                      AndHighLow      682.56      (3.5%)      727.45      (3.2%)    6.6% (   0% -   13%) 0.000
                        HighTerm      440.00      (9.1%)      490.39      (7.1%)   11.5% (  -4% -   30%) 0.000
                         LowTerm      917.37      (8.4%)     1033.11      (5.4%)   12.6% (  -1% -   28%) 0.000
                         MedTerm      459.23      (9.4%)      519.72      (6.6%)   13.2% (  -2% -   32%) 0.000
                       OrHighLow      605.42      (5.7%)      694.24      (3.7%)   14.7% (   5% -   25%) 0.000
                     AndHighHigh       36.06      (5.7%)       44.64      (6.8%)   23.8% (  10% -   38%) 0.000
                      AndHighMed       86.74      (5.1%)      107.82      (4.5%)   24.3% (  13% -   35%) 0.000
                       OrHighMed      190.57      (6.5%)      251.30      (5.5%)   31.9% (  18% -   46%) 0.000
                      OrHighHigh       39.38      (9.4%)       55.12      (8.7%)   40.0% (  19% -   64%) 0.000
```

**Comment by jpountz** [comment]
This change had an impact on nightly benchmarks
 - [AndHighHigh](http://people.apache.org/~mikemccand/lucenebench/AndHighHigh.html): +14%
 - [AndHighMed](http://people.apache.org/~mikemccand/lucenebench/AndHighMed.html): +15%
 - [OrHighHigh](http://people.apache.org/~mikemccand/lucenebench/OrHighHigh.html): +8%
 - [OrHighMed](http://people.apache.org/~mikemccand/lucenebench/OrHighMed.html): +8%
 - [AndHighOrMedMed](http://people.apache.org/~mikemccand/lucenebench/AndHighOrMedMed.html): -47%
 - [AndMedOrHighHigh](http://people.apache.org/~mikemccand/lucenebench/AndMedOrHighHigh.html): -12%
 - [Fuzzy1](http://people.apache.org/~mikemccand/lucenebench/Fuzzy1.html): +3%
 - [Fuzzy2](http://people.apache.org/~mikemccand/lucenebench/Fuzzy2.html): +2%
 - [Term](http://people.apache.org/~mikemccand/lucenebench/Term.html): -7%

I pushed an annotation.

**Pull request merged**
