### PR TITLE
Make generated archive files reproducible

### PR DESCRIPTION
**Pull request by breskeby**
This should ensure deterministic archive files and fix issues with changing checksums even though the codebase has not changed.

### CODE REVIEW

**Comment by javanna** [comment]
Thanks @breskeby ! This should solve an issue we have observed when building Elasticsearch against a lucene snapshot. We have seen that the snapshot name may stay the same while the verification sha changes, which requires us to wipe the gradle cache or gradle complains about the mismatch.

@dweiss are you the build expect nowadays? Would you like to have a look? :)

**Comment by rmuir** [comment]
Looks awesome, almost too good to be true if it is this simple. IMO: it is a great property for the build to have.

**Comment by dweiss** [comment]
Part of this is actually already in gradle-archives.gradle - I think adding this patch there would be better?

**Comment by breskeby** [comment]
> Part of this is actually already in gradle-archives.gradle - I think adding this patch there would be better?

@dweiss updated this accordingly. boiled down to a one line change now

**Review by dweiss — APPROVED** [review]

**Comment by dweiss** [comment]
Thank you. I'll merge this into branch_9x and branch_10x.

**Pull request merged**
