### PR TITLE
11730 removed unused fst load mode

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
### Description
This pull request removes the `ON_HEAP` load mode for finite state machines. If FSTs are not MMAPped, they are read from disk using NIO FS. I did not see a way to force `ON_HEAP`. Perhaps we should remove it.

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
It's linked to this issue: https://github.com/apache/lucene/issues/11730

**Comment by MarcusSorealheis** [comment]
The MLT commit did not belong in the working tree. I removed it.

**Comment by MarcusSorealheis** [comment]
Ok, so I did identify how an advanced user can still get FSTs to be loaded in heap (via service provider initialization).

**Comment by jpountz** [comment]
Changing the default for the completion postings format might be controversial. Maybe we should close this PR since we're still using the ON_HEAP mode and have a separate discussion about whether completion postings formats could move to OFF_HEAP?

**Comment by MarcusSorealheis** [comment]
@jpountz It makes sense to close the PR It's very dirty. 

Can you link me to the discussion? I remember [LUCENE-8859](https://github.com/apache/lucene/issues/9902) but haven't seen/couldn't find something more recent.

I am really excited about the Git migration. I think it will feel even nicer in the future once i get used to information discovery here.

**Pull request closed without merging**
