### PR TITLE
Improve MIGRATE.md around analyzers artifacts.

### PR DESCRIPTION
**Pull request by rmuir**
Move this to the very top of MIGRATE, the user needs to first be able to pull in the artifacts, before doing anything else like trying to compile, deal with renamed classes, etc.

Add a table of each package that got moved, with explicit old and new names. Hopefully it helps search engines and users.

@jpountz I'd like to backport this to 9.0 if possible, since we are respinning for module names anyway. It is low risk.

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/lucene/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Lucene maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
Feel free to go ahead with backporting.

**Review by uschindler — APPROVED** [review]
Have you compared all Maven artifacts, also the ones not related to analysis?

Otherwise looks fine.

**Comment by uschindler** [comment]
A separate note: The new name is also more conforming what the modules relay do: They are not only "analyzers", those are compoents for "analysis" of text while indexing/searching lucene. So new name is better. Maybe add this to explanation.

**Comment by uschindler** [comment]
Table looks much better now. Thanks!

**Comment by rmuir** [comment]
Sorry for all the commits, I wanted to try to make this easy to read and prominent, and linked from the README too for more visibility. 

I realize the `MIGRATE.md` is an unstructured list, but there's an advantage to listing some stuff at the top (esp. if it is likely to impact most users that upgrade). I don't want to hold up the 9.0 release, but maybe for the next one we can improve it to be better, some ideas:
* avoid usage of abbreviations in our MIGRATE notes such as `o.a.l.a.util.TokenizerFactory`
* avoid lists of from-to stuff and use tables (like this one as an example)
* structure the high-impacting stuff such as package and class renames at the top.

**Comment by uschindler** [comment]
Originally I made the MIGRATE.md a markdown file to have all formatting possibilities. The unordered list was just a "quick conversion" from the old format introduced in Lucene 4.0.

The Markdown converter accepts all markdown in the `gradlew documentation` output and also expands LUCENE/SOLR issue numbers (and makes them clickable): https://github.com/apache/lucene/blob/main/gradle/documentation/markdown.gradle

**Comment by rmuir** [comment]
> A separate note: The new name is also more conforming what the modules relay do: They are not only "analyzers", those are compoents for "analysis" of text while indexing/searching lucene. So new name is better. Maybe add this to explanation.

I'd rather not mix in justification/reasoning for any changes in this file, I think it adds noise. Most users will be annoyed with us regardless :)  I think this file should just be simple hints of how to fix your code? We list the JIRA issue for each change already, in case an interested party wants to drill down to background discussion of why changes were done, or get any more detailed information.

**Comment by uschindler** [comment]
This was just meant as a replacement for this text: "and are now consistent with repository module 'analysis'". This does not sound like a acceptable explanation to an annoyed user, so my idea was to just say: "better name because it does more than providing analyzers".

But all fine, was just my 2ct.

**Comment by uschindler** [comment]
Hi Robert,
I built the documentation with "gradlew documentation" and noticed that tables were not enabled in the markdown converter. It now looks not very well.

If you don't mind I will add a change to fix the converter:
image

So please wait a bit with merging!

**Pull request merged**
