### PR TITLE
LUCENE-9854: Clean up utilities to download and extract test/ benchmark data sets.

### PR DESCRIPTION
**Pull request by dweiss**
Just a cleanup of existing tasks.

### CODE REVIEW

**Review by dsmiley — COMMENTED** [review]
Today I went looking for these tasks so that I could execute them to download the data.  I didn't see them where I expected them to be; thankfully a git history revealed this change.  Had someone other than me stumbled across this benchmark build, I think they wouldn't even know there were such things.

@dweiss this change surprises me with respect to moving the benchmark module's dataset tasks into a new external-datasets.gradle file.  These tasks are not a cross-cutting concern across our modules; it is specific to this one (right?).  Thus it appears you take an extreme position on build file organization philosophy that a build.gradle file should only have a dependency list, not even one-off tasks specific to the module.  Why?

Separately, is your position/philosophy codified/written anywhere?  It would be useful for newcomers to read about this so that they understand that we do things in non-obvious ways.

**Comment by dweiss** [comment]
you can move it back to benchmarks if it's used only from there.

**Comment by dweiss** [comment]
>  I didn't see them where I expected them to be

Btw. you should use 'gradlew -p lucene/benchmark tasks' for such queries - then the location of task definitions are less important? If you shuffle things around the build and in the gradle/ folder then things will get messy again, I think. In this particular case - sure, fine, I don't mind at all.

image

**Comment by dsmiley** [comment]
I don't quite care enough to spend the time to move it back.  More than anything, I wanted to get your perspective.

**Comment by dweiss** [comment]
In this particular case I don't think there's much of a difference - you could place it inside the project's build file as well. I still think the 'tasks' list should be the place to look at when you're trying to locate a task name - the fact you can configure tasks from different places is one of the greatest and most annoying features at the same time... I understand you're puzzled because this has happened to me in the past as well. In my opinion (expressed previously), I think the task-based layout of gradle files (or classes, or plugins) is still superior to fragments of configuration scattered across build files. It lets you rip out/ modify things across the entire codebase from a single place (most of the time).

I've been actually thinking of moving some of those scripts to java/ precompiled code so that the bootstrap is faster - the scripts have been stable enough and there's been fewer changes to them so perhaps it's time....

**Pull request merged**
