### PR TITLE
Fix Field.java documentation to refer to new IntField/FloatField/LongField/DoubleField #12125

### PR DESCRIPTION
**Pull request by SreehariG73**
### Description
Replaced IntPoint, LongPoint, FloatPoint, and DoublePoint with IntField, LongField, FloatField, and DoubleField to make it easier-to-use field subclasses.

### CODE REVIEW

**Comment by jpountz** [comment]
Thanks for doing it, it looks like the PR includes unintended changes though?

**Comment by jpountz** [comment]
@SreehariG73 Do you plan on removing the unintended changes?

**Comment by SreehariG73** [comment]
Hello Adrien,

I have made changes to the PR. Please review the same and let me know if it
looks good

regards,
Sreehari Guruprasad

**Comment by jpountz** [comment]
Thank you! I'll close this one then.

**Pull request closed without merging**
