### PR TITLE
Allow building with java 18 now that gradle supports it

### PR DESCRIPTION
**Pull request by rmuir**
Since #11886, java 18 actually works, so let's allow it. unfortunately java 19 still does not work.

### CODE REVIEW

**Review by risdenk — CHANGES_REQUESTED** [review]
Based on the commit that added this check, https://github.com/apache/lucene/commit/c897aac0773d7c14fedceefa26511b97866ad587 gradlew and gradlew.bat should be updated as well.
* https://github.com/apache/lucene/blob/main/gradlew#L127
* https://github.com/apache/lucene/blob/main/gradlew.bat#L100

**Comment by rmuir** [comment]
> Based on the commit that added this check, [c897aac](https://github.com/apache/lucene/commit/c897aac0773d7c14fedceefa26511b97866ad587) gradlew and gradlew.bat should be updated as well.
> 
> * https://github.com/apache/lucene/blob/main/gradlew#L127
> * https://github.com/apache/lucene/blob/main/gradlew.bat#L100

oh, thanks for the reminder, i forgot about the generic "something went wrong" message

**Comment by rmuir** [comment]
i'm gonna fix that too. but for the future i wonder if we need that "generic" message anymore... or at least versions in it: that was kinda a previous workaround for gradle's confusing errors. but now if you use the wrong java version you get an explicit error.

**Review by risdenk — APPROVED** [review]

**Review by dweiss — APPROVED** [review]

**Comment by dweiss** [comment]
>i'm gonna fix that too. but for the future i wonder if we need that "generic" message anymore... or at least versions in it: that was kinda a previous workaround for gradle's confusing errors. but now if you use the wrong java version you get an explicit error.

I agree - the message should be printed by the downloader script. If somebody is using a REALLY old Java then so be it - it'll fail to interpret the script.

**Review by uschindler — APPROVED** [review]

**Comment by rmuir** [comment]
unrelated to this PR, does anyone know what happened with the "run distribution test" check?

it hit connect timeout and failed, this isn't "our" downloading, there's no `org.apache.lucene` in the stacktraces. We already added retries to that piece. so i dont know how to make this more reliable...

Screen_Shot_2022-10-28_at_09 55 19

**Comment by uschindler** [comment]
I restarted the Github actions. Was some timeout error.

**Comment by uschindler** [comment]
> @uschindler i know, but in order to prevent flaky builds, we should have backoff and retry to these type of requests.

Sometimes also Apache Git is down then Jenkins fails. Who cares? I don't want to modify Gradle's code just because 1 in 100 cases the gradle download fails. On Jenkins this is not an issue at all, as it is cached accross builds.

**Comment by dweiss** [comment]
This is gradle bootstrapping itself (new version). It's the gradle-wrapper that downloads the distribution. I'm not sure how we could retry it on network failures, unfortunately. The downloader script could try to do it/ ping the network but it seems like an unacceptable overhead for everyone just to detect a rare glitch.

**Comment by rmuir** [comment]
> This is gradle bootstrapping itself (new version). It's the gradle-wrapper that downloads the distribution. I'm not sure how we could retry it on network failures, unfortunately. The downloader script could try to do it/ ping the network but it seems like an unacceptable overhead for everyone just to detect a rare glitch.

I don't want to add anything crazy such as pings. it wouldn't help for cases like random connect-timeout/503/etc. 

but if theres a way to add `try/catch` to some java code or even `download || (sleep 10 && download) || (sleep 10 && download)` to prevent builds from having annoyingly noisy fails, we should do it :)

**Comment by uschindler** [comment]
> but if theres a way to add `try/catch` to some java code or even `download || (sleep 10 && download) || (sleep 10 && download)` to prevent builds from having annoyingly noisy fails, we should do it :)

You would need to do that around each Maven Central call :-) This was just a bad incidence that it failed. I don't care if the build fails from time to time. It does it for other reasons, too.

**Comment by rmuir** [comment]
> You would need to do that around each Maven Central call :-) This was just a bad incidence that it failed. I don't care if the build fails from time to time. It does it for other reasons, too.

usually package managers have robust retry behavior like this already.

**Comment by rmuir** [comment]
ok, ill ignore it. but i'm not happy about flaky builds because someone used the network naively!

**Comment by dweiss** [comment]
> usually package managers have robust retry behavior like this already.
 
It's something that would have to be fixed in the gradle wrapper, I think. :(

**Comment by uschindler** [comment]
Thanks!

**Pull request merged**
