### PR TITLE
fix errors in DocStats comments

### PR DESCRIPTION
**Pull request by wormday**
Comments for two fields of DocStats are reversed

### CODE REVIEW

**Comment by mocobeta** [comment]
Hi @wormday - sorry for the late reply. Do you have the idea of the reviewer? Committers are usually too busy to watch all pull requests and often overlook good PRs.

**Comment by wormday** [comment]
> Hi @wormday - sorry for the late reply. Do you have the idea of the reviewer? Committers are usually too busy to watch all pull requests and often overlook good PRs.


What work do reviewers need to do? I have nothing to do recently, I am reading the source code of lucene, and I hope to do something.

**Comment by mocobeta** [comment]
Anyone can be a reviewer for this project. Browse the opened/active pull requests (there are always tons of PRs), choose one you are interested in and able to review, and make comments on it to improve the code. Only committers can merge it, though.

**Comment by wormday** [comment]
> Anyone can be a reviewer for this project. Browse the opened/active pull requests (there are always tons of PRs), choose one you are interested in and able to review, and make comments on it to improve the code. Only committers can merge it, though.

I see. I'll try
thanks

**Pull request closed without merging**
