### PR TITLE
LUCENE-10365 Wizard changes contributed from Solr

### PR DESCRIPTION
**Pull request by janhoy**
https://issues.apache.org/jira/browse/LUCENE-10365 (#11401) 

* Now asks whether to use gradle or gpg based release signing
* Now asks whether to prompt for password or not (during gpg step)
* When running multiple commands with prompt, now prints any command-comments just before the prompt - they sometimes contain important additional information
* Remove warning about asf mirror network in release template
* Use `--set-upstream` when pushing new branches, so next `git pull` command will work
* Use `{{ dist_url_base }}` several places for brewity
* Check svn exists at startup
* URL changes

The Solr release is still in progress, so there may be more improvements further down the road. So I propose we let this PR stay open until Solr 9.0 is done, and add any last commits to the PR along the way. Marking as draft.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
These changes make sense to me. I see your PR is in draft mode, does it require more work before it can be merged?

**Comment by janhoy** [comment]
Sure, will add more commits during the Solr 9.0 release, thought I’d make it one PR instead of many small.

**Comment by janhoy** [comment]
I have an ambition to refactor the release wizard into a generic tool with ability to add a custom py script for custom functions and variables, and then perhaps make it into a su project of COMDEV. And perhaps release as pip module. Then Lucene, Solr and Operator would have a tiny py file that imports the common package. Think it could be useful for other Apace projects as well.

**Comment by janhoy** [comment]
@msokolov This has been hanging for a while, and I'll now merge it into main and then to branch_9x. 

Just though I'd alert you as 9.4.0 RM, although I don't anticipate any issues with the ongoing release, as these are mostly bug fixes and improvements related to release signing (ability to sign with gradle plugin instead of GPG). I'll let you make the call whether you merge it into branch_9_4 for use with this release.

**Comment by janhoy** [comment]
I took the time to include also the remaining fixes from Solr wizard, please have a quick look at the last two commits:
* [More Python fixes from the Solr 9 release](https://github.com/apache/lucene/pull/591/commits/677082577fe43c45ed74e569dac86b660d8b8798)
* [Various yaml improvements from the Solr 9 release](https://github.com/apache/lucene/pull/591/commits/cdcd31656076d423ed2bd1dc1537323e1606df52)

I did specifically *not* port over @HoustonPutman's script to stage maven artifacts (https://github.com/apache/solr/pull/807), as there seems to be an ongoing discussion on the route Lucene wants to take here.

**Comment by msokolov** [comment]
ah thanks Jan! Since I went through all the GPG setup I feel I should use it! But ... probably will backport

**Comment by janhoy** [comment]
I'm going to merge this in now, and then any bug fixing can happen in followup commits.

**Pull request merged**
