### PR TITLE
Fix typo in the documentation of TaxonomyReader

### PR DESCRIPTION
**Pull request by Yuti-G**

### CODE REVIEW

**Comment by msokolov** [comment]
not sure why you closed, looks good to me, I'll commit

**Comment by Yuti-G** [comment]
Thanks @msokolov! I forgot to change account in GitHub Desktop and accidentally pushed this pr using my two GitHub accounts. I thought it would be better to use one account, and pushed #733 (closed now).

**Comment by Yuti-G** [comment]
> not sure why you closed, looks good to me, I'll commit

Thanks @msokolov! I forgot to change account in GitHub Desktop and accidentally pushed this pr using my two GitHub accounts. I thought it would be better to use one account, and pushed https://github.com/apache/lucene/pull/733 (closed now).

**Comment by msokolov** [comment]
Ah, I see - sorry if I jumped the gun and now your commit is recorded against the wrong github id! Sadly there is no fixing github.

**Comment by Yuti-G** [comment]
> Ah, I see - sorry if I jumped the gun and now your commit is recorded against the wrong github id! Sadly there is no fixing git history.

No worries! I think it is against my correct GitHub id. This is my first practice of pushing a pr upstream, and sorry for the confusion. Thank you!

**Pull request merged**
