### PR TITLE
Remove unnecessary fields loop from extractWeightedSpanTerms()

### PR DESCRIPTION
**Pull request by sabi0**

### CODE REVIEW

**Comment by sabi0** [comment]
It seems the method could be skipped completely if the query does not contain `fieldName` or `defaultField`:
```
  protected void extractWeightedSpanTerms(Map<String,WeightedSpanTerm> terms, SpanQuery spanQuery, float boost) throws IOException {
    Set<String> queryFieldNames = new HashSet<>();
    collectSpanQueryFields(spanQuery, queryFieldNames);
    if (fieldName != null
        && !queryFieldNames.contains(fieldName)
        && (defaultField == null || !queryFieldNames.contains(defaultField))) {
      return;
    }
```

Should I add this to the PR?

**Comment by dweiss** [comment]
Yep, I think this early termination condition makes sense. Could you add it, please? Thank you.

**Comment by sabi0** [comment]
I've rebased on the latest main, added the early termination check and a separate commit with minor cleanups.
Please let me know if you'd like me to squash them all before the merge.

**Comment by dweiss** [comment]
Thank you!

**Pull request merged**
