### PR TITLE
LUCENE-10399: Handle large boolean expressions better in flexible query parser

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

**Comment by rmuir** [comment]
This isn't a safe optimization though, it changes ranking.

**Comment by dweiss** [comment]
Right - TermInSet is a constant score one... I wonder how significant scores are if somebody generates hundreds of these terms for a disjunction boolean query.

**Comment by rmuir** [comment]
Maybe an alternative would be to just explicitly expose TermInSetQuery via an operator? Sorry, I don't have suggested syntax: can't remember what symbols are already used :) But you could imagine something like `field:[dogs,cats,birds,squirrels,....]` or operator such as `IN`. Sorry i'm just thinking out loud and don't have a great suggestion.

**Comment by dweiss** [comment]
Any change to jflex parser will cause backward compatibility issues. I'll take a look though.

**Comment by rmuir** [comment]
I don't think any more abstractions are needed if you want to do the rewrite. You can do it in ConstantScoreQuery.rewrite().

**Comment by dweiss** [comment]
I admit I'm looking at this from an user-endpoint where the distinction between constant and regular scoring is not visible... All people see is a hard constraint once they hit the exception on max clauses, which I wanted to soften a bit (even if this means sacrificing document order/ scores).

**Comment by rmuir** [comment]
> Any change to jflex parser will cause backward compatibility issues. I'll take a look though.

LOL, but breaking scoring isn't?!

**Comment by dweiss** [comment]
I originally planned for this patch to kick in only when the number of clauses exceeds the threshold that would otherwise throw an exception - so better something that has no scores than nothing at all. This was brought to my attention because folks used those long lists of terms as exclusions/ inclusion filters in addition to more sane query criteria, something like:
```
foo bar -(long OR long OR list OR of OR excluded OR terms)
```
So it's in effect a filtering sub-clause that doesn't really need scores. I'm not saying it's the best way to solve the problem but it worked for the above. :)

**Comment by rmuir** [comment]
The problem is there is no intent telling you where scores are wanted and where they aren't. Specifying this intent (e.g. syntax) is a necessary prerequisite to doing this optimization for `SHOULD` clauses!

In your example above, where it's entirely `MUST_NOT` clauses, the optimization is actually safe, because `MUST_NOT` clauses don't impact scoring, since they only restrict matches. So it is fine to optimize this specific case right now.

**Comment by dweiss** [comment]
> Specifying this intent (e.g. syntax) is a necessary prerequisite to doing this optimization for SHOULD clauses!

I agree with you but I can't convince myself to add yet another syntax extension to that query parser, it is already pretty complex. 

I looked at optimizing just the filtering expressions but this would have to be done at the graph level (not query builder level) because by the time the node builder tries to optimize the subclause, it's already thrown an exception (boolean query builder is eager). 

Finally I've just modified the code so that this is an optional feature which has to be explicitly turned on. This really works fine in practice (based on what I've seen) because if the number of boolean clauses is in hundreds then scores from these filtering subexpressions are typically secondary - not too important given the goal of the entire query. 

Let me know if this optional feature is acceptable for you. If not, I'll just leave it as a patch for anybody who wants to reuse it - the query parser's default boolean node builder can be replaced in custom applications so this is not a problem.

**Comment by dweiss** [comment]
Ping, @rmuir - WDYT? Should I merge this in or leave as a convenience patch in jira?

**Comment by rmuir** [comment]
sorry @dweiss for the delay. I'm not properly getting email notifications from GH: I dont know why. I randomly looked in the github UI and saw this one right now.

Maybe get a second opinion, I think I am too biased against it. I really feel that people doing `JOIN` shouldn't be doing it with enormous boolean expressions of `AND`'s and `OR`'s. And that if they really should be doing stuff thru thee parsers, it'd be better to add support for things like `BooleanClause.Occur.FILTER`, `TermInSetQuery`, and maybe even `ConstantScoreQuery` to these parsers if we want things like this to be more efficient for them.

I get that nobody wants to have to deal with javacc to change the syntax, but to some people, it would probably be less complicated than that massive stream expression, magical options that impact scoring and performance in confusing ways, etc.

There's a reason why these kinds of issues turn into bikesheds, and its because hacky solutions / option explosion doesn't scale long-term for the project, the code just becomes insane.

I also resent the implication that i don't live in the "real world", that my world is somehow fake, because I push back on such things. I just want code to be clean.

**Comment by rmuir** [comment]
also, just think about the technical benefits if "filtering" (non-scoring) is exposed properly in the parsers. Long term, users adding these kinds of structured clauses today could get much improved performance for many situations, thanks to query caching and other optimizations that will suddenly work for them.

**Comment by dweiss** [comment]
> I get that nobody wants to have to deal with javacc to change the syntax

Sure, no worries - I don't have to commit it to Lucene and can apply it externally.

Let me explain my motivation of why I thought it'd be useful though - it's not about changing javacc - I can change the syntax with no problem - it's that a great many folks I deal with who use Lucene search systems never look (deeply) at the documentation. They don't get the difference or need for things things that are more obvious to programmers. For these users foo:[5 TO 6], foo:{5 TO 6], foo:(5 TO 6) and foo:(5 to 6) is the same even if all of these are different queries in the flexible query parser... My experience is that even the sophisticated search-interface users rarely go beyond boolean queries (maybe sprinkled with fuzzy or wildcards). These can be large queries, but structurally they're simple.

I'll just leave this as a PR/ patch, perhaps an idea for a better general solution will come to me in the future.

**Pull request closed without merging**
