### PR TITLE
Add getter for SynonymQuery#field

### PR DESCRIPTION
**Pull request by AndreyBozhko**
### Description

Since all the query terms must have the same field, the `field` value is exposed anyway via
```java
synonymQuery.getTerms().get(0).field()
```
but it's cleaner if one could instead use
```java
synonymQuery.getField()
```

### CODE REVIEW

**Review by dungba88 — APPROVED** [review]
I think we can add some javadoc as well

**Comment by AndreyBozhko** [comment]
Thanks for the review @dungba88 - I added the javadoc as well (tried to match the style of other javadocs in the file).

**Comment by AndreyBozhko** [comment]
@dungba88 If all looks good, please feel free to merge this at your earliest convenience (as I don't have access to do so myself).

**Comment by mkhludnev** [comment]
Thanks. It's probably worth to refer to this method from a test to further prevent its' sudden drop from the API.

**Comment by AndreyBozhko** [comment]
@mkhludnev Makes sense - I added a simple test.

**Comment by AndreyBozhko** [comment]
Checks are failing due to unrelated error from 314c553bdce22bc1bc08e46b218691575c2287e0:
```
Deprecated is not a repeatable annotation type
  @Deprecated public static final Version LUCENE_9_10_0 = new Version(9, 10, 0);
```

**Review by mkhludnev — APPROVED** [review]
Awaiting for concerns. Will merge next week.

**Review by kkmr — APPROVED** [review]

**Comment by mkhludnev** [comment]
aaahgg... wrong CHANGES.. going to move in unde 9.11

**Pull request merged**
