### PR TITLE
LUCENE-10502: Use IndexedDISI to store docIds and DirectMonotonicWriter/Reader to handle ordToDoc

### PR DESCRIPTION
**Pull request by LuXugang**
follow up of https://github.com/apache/lucene/pull/792 and https://github.com/apache/lucene/pull/870

### CODE REVIEW

**Comment by LuXugang** [comment]
Hi, @mayya-sharipova , such merge operation is new to me, I am not sure if I could add an entry to CHANGES.txt correctly, so I could add entry after this PR merged or could you be nice to help me out.

**Comment by mayya-sharipova** [comment]
@LuXugang Right,  you can add an entry to CHANGES.txt after this PR is merged.

**Review by mayya-sharipova — APPROVED** [review]
@LuXugang Thanks, fantastic work! This LGTM to merge to `main`.  

Let's hear from @jtibshirani if she has any additional comments.

**Review by jtibshirani — APPROVED** [review]
Thanks @LuXugang !

**Comment by mayya-sharipova** [comment]
@LuXugang I've merged your PR to `main`.

Other things we need to do:
1) Please create a PR against `main` add an entry to CHANGES.txt  under the `Lucene 9.2.0` release.  
2) After 1) is merged,  we need to cherry-pick all these changes to 9.x branch.

**Comment by LuXugang** [comment]
@mayya-sharipova , @jtibshirani  Thanks for your reviews! 

>Please create a PR against main add an entry to CHANGES.txt under the Lucene 9.2.0 release.

Addressed in https://github.com/apache/lucene/pull/881.

**Pull request merged**
