### PR TITLE
Upgrade several build dependencies.

### PR DESCRIPTION
**Pull request by dweiss**
This is mostly taken from what @risdenk did on the Solr side of the build.

### CODE REVIEW

**Comment by dweiss** [comment]
Not sure what's failing here, will take a look later. I suspect errorprone.

**Comment by rmuir** [comment]
Looks like error-prone fails saying that `PublicConstructorForAbstractClass` is not a valid checker name. 
We explicitly disable it currently:
```
gradle/validation/error-prone.gradle:            '-Xep:PublicConstructorForAbstractClass:OFF'
```

**Comment by dweiss** [comment]
Yeah, thanks, Robert. I'll be looking into this - have an hour to spare at the airport anyway.

**Comment by dweiss** [comment]
Right - this check was removed here: https://github.com/google/error-prone/commit/b4c6a03168102026bb6540627b21b356804250e4

**Comment by dweiss** [comment]
Another check was removed here: https://github.com/google/error-prone/pull/2809

**Review by rmuir — APPROVED** [review]

**Comment by rmuir** [comment]
oh, one question @dweiss, since `javacc` is upgraded, should we force a `gradlew regenerate`?

**Review by risdenk — APPROVED** [review]

**Comment by dweiss** [comment]
> oh, one question @dweiss, since javacc is upgraded, should we force a gradlew regenerate?

Hmmm.. isn't javacc part of the checksum? It should regenerate itself when javacc is upgraded. If it's not then it's something that should be corrected there. I did run regenerate after updating stuff and it returns cleanly.

**Comment by dweiss** [comment]
I re-ran javacc and the generated files just seem to be identical.

**Comment by dweiss** [comment]
Sorry, I was wrong about javacc and possibly other tasks - I'll do a follow-up.

**Pull request merged**
