### PR TITLE
Optimize decoding blocks of postings using the vector API. (#13636)

### PR DESCRIPTION
**Pull request by jpountz**
Backport of #13636 to branch_9x.

### CODE REVIEW

**Comment by jpountz** [comment]
@uschindler I was wondering while doing this backport: would you apply the same refactoring wrt `PanamaVectorConstants` to the `src/java20` folder, or would you keep it as-is?

**Comment by uschindler** [comment]
Maybe for consistency it would be good. I don't remember, did we backport Chris changes to java 20, too?

**Comment by uschindler** [comment]
> I don't remember, did we backport Chris changes to java 20, too?

No we did not. Nevertheless, maybe the constants code backport would be cool.

**Comment by jpountz** [comment]
OK, I did it for src/java20 too.

**Review by uschindler — APPROVED** [review]
Looks fine. 👍

**Pull request merged**
