### PR TITLE
[Backport] Integrate the Incubating Panama Vector API #12311

### PR DESCRIPTION
**Pull request by ChrisHegarty**
Backport of #12311

Leverage accelerated vector hardware instructions in Vector Search.

Lucene already has a mechanism that enables the use of non-final JDK APIs, currently used for the Previewing Pamana Foreign API. This change expands this mechanism to include the Incubating Pamana Vector API. When the jdk.incubator.vector module is present at run time the Panamaized version of the low-level primitives used by Vector Search is enabled. If not present, the default scalar version of these low-level primitives is used (as it was previously).

Currently, we're only targeting support for JDK 20. A subsequent PR should evaluate JDK 21, which is still in development.

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
There are a couple of warnings showing up in the precommit checks. Not sure why I only see these here, but they should be relatively straightforward to fix (and will be required in _main_ too)

```
/home/runner/work/lucene/lucene/lucene/core/src/java20/org/apache/lucene/store/MemorySegmentIndexInput.java:275: error: incompatible types: possible lossy conversion from long to int

      this.curPosition = Objects.checkIndex(pos & chunkSizeMask, curSegment.byteSize() + 1);
                                                ^
/home/runner/work/lucene/lucene/lucene/core/src/java20/org/apache/lucene/store/MemorySegmentIndexInput.java:468: error: incompatible types: possible lossy conversion from long to int
        curPosition = Objects.checkIndex(pos, length + 1);
                                         ^
/home/runner/work/lucene/lucene/lucene/core/src/java20/org/apache/lucene/util/VectorUtilPanamaProvider.java:82: error: cannot access VectorSupport
      FloatVector acc1 = FloatVector.zero(PREF_FLOAT_SPECIES);
                                    ^
  class file for jdk.internal.vm.vector.VectorSupport not found
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors
> Task :lucene:core:compileMain20Java FAILED
```

**Comment by ChrisHegarty** [comment]
Well there are two different types of warnings: 
 1. possible lossy conversion - easy, this is a new lint warning in JDK 20
 2. jdk.internal.vm.vector.VectorSupport not found - I'll regenerate the apijar

**Comment by uschindler** [comment]
I wonder why you got this error in MemorySegmentIndexInput?

This is a problem which was already solved log ago. After Java 11 a new method for longs was added which is not available in Java 11.

**Comment by uschindler** [comment]
I know the problem with MMAap. The Objects.checkIndex(long, long) was added in Java 16, so not availebale to Java 11 compiler.

The API extract also needs to extract `java/lang/Objects`; this got lost by merging!!!!

**Comment by uschindler** [comment]
Here is the problem: https://github.com/apache/lucene/pull/12327/files#diff-1ff94b709f930416054d6a370251ac7376f9a4ec170b662b9ba12983f35ff1f1L51

The Glob pattern must be extended in the new extractor, then it should work.

**Comment by uschindler** [comment]
I don't know the problem with jdk.internal.VectorSupport. Why is that needed for compilation? Maybe we need another hack for the Java 11 compiler?

**Comment by ChrisHegarty** [comment]
There is definitely some internals "leaking" into the jdk20 api jar, because of this:

```
/home/runner/work/lucene/lucene/lucene/core/src/java20/org/apache/lucene/util/VectorUtilPanamaProvider.java:82: error: cannot access VectorSupport

      FloatVector acc1 = FloatVector.zero(PREF_FLOAT_SPECIES);
> Task :lucene:core:compileMain20Java FAILED
                                    ^
  class file for jdk.internal.vm.vector.VectorSupport not found.  <<<<<<<<<<<<<<<<
```

**Comment by uschindler** [comment]
> There is definitely some internals "leaking" into the jdk20 api jar, because of this:
> 
> ```
> /home/runner/work/lucene/lucene/lucene/core/src/java20/org/apache/lucene/util/VectorUtilPanamaProvider.java:82: error: cannot access VectorSupport
> 
>       FloatVector acc1 = FloatVector.zero(PREF_FLOAT_SPECIES);
> > Task :lucene:core:compileMain20Java FAILED
>                                     ^
>   class file for jdk.internal.vm.vector.VectorSupport not found.  <<<<<<<<<<<<<<<<
> ```

I will check this, you can easily do this by adding a System.out() in the loop that expands the "references" and adds them to classesToLoad.

I am on it. It looks like some public signature or return value is indirectly referencing the internal class (maybe through superclass). In JDK 17 it exists already, but not in 11. So the extraction was incomplete. I will feedback soo.

**Comment by uschindler** [comment]
Here we see the issue with a println, it looks like VectorSupport is a superclass/interface of some of the Vector classes:
```
Transforming 189 class files in [/modules/jdk.incubator.vector]...
[java/lang/Object, jdk/internal/vm/vector/VectorSupport$VectorMask, jdk/internal/vm/vector/VectorSupport$VectorShuffle, jdk/incubator/vector/VectorOperators$Binary, jdk/internal/vm/vector/VectorSupport$Vector, java/lang/Enum, jdk/incubator/vector/AbstractVector, jdk/incubator/vector/VectorOperators$Operator]
[java/lang/Object, jdk/incubator/vector/Vector, jdk/incubator/vector/VectorOperators$Operator]
[java/lang/Object, jdk/internal/vm/vector/VectorSupport$Vector]
[]
```

**Comment by uschindler** [comment]
I think we should forward port this internal class special case to main branch, too. It is just working because JDK17 has this internal class ready.

In total: It is not a good API design to make public classes refer to internal classes (yes it works, but it is a bit strange).

**Comment by uschindler** [comment]
Looks like we have to add `jdk/internal/vm/vector/**.class` to the pattern (i think it is base module!?).

**Comment by uschindler** [comment]
It is in java.base, I will try something out.

**Comment by uschindler** [comment]
OK, I think I will open a PR on the main branch to fix the Extractor to:
- print a warning for missing classes (superclasses, interfaces) that are not part of Java's public API (classname starts with "jdk/internal" or similar).
- add the VectorSupport class to the pattern. Problem is that it then also goes into the memory map JAR for java 19, where it is not needed. This can be fixed by doing the reference analysis globally, at moment it is done per module.

So it needs a bit of refactoring, but to make porting easier, I will do it in separate PR on main branch. Let's keep this one open and later merge the main branch changes in.

**Comment by uschindler** [comment]
Another simpler approach is: As methods/constants/... from those module-private APIs are not visible at runtime, I tend to simply replace the superclass by "java/lang/Object" and rmeove all jdk/internal interfaces. Looks much better to me and cleans API JAR small.

**Comment by uschindler** [comment]
This seems to work:

```diff
 .../generation/extract-jdk-apis/ExtractJdkApis.java |  11 +++++++++++
 lucene/core/src/generated/jdk/jdk20.apijar          | Bin 52851 -> 52874 bytes
 2 files changed, 11 insertions(+)

diff --git a/gradle/generation/extract-jdk-apis/ExtractJdkApis.java b/gradle/generation/extract-jdk-apis/ExtractJdkApis.java
index be8741db366..9df612e89e4 100644
--- a/gradle/generation/extract-jdk-apis/ExtractJdkApis.java
+++ b/gradle/generation/extract-jdk-apis/ExtractJdkApis.java
@@ -101,6 +101,7 @@ public final class ExtractJdkApis {
     // recursively add all superclasses / interfaces of visible classes to classesToInclude:
     for (Set<String> a = classesToInclude; !a.isEmpty();) {
       a = a.stream().map(references::get).filter(Objects::nonNull).flatMap(Arrays::stream).collect(Collectors.toSet());
+      System.out.println(a);
       classesToInclude.addAll(a);
     }
     // remove all non-visible or not referenced classes:
@@ -122,6 +123,9 @@ public final class ExtractJdkApis {
   static class Cleaner extends ClassVisitor {
     private static final String PREVIEW_ANN = "jdk/internal/javac/PreviewFeature";
     private static final String PREVIEW_ANN_DESCR = Type.getObjectType(PREVIEW_ANN).getDescriptor();
+
+    private static final String REPLACE_INTERNAL_PREFIX = "jdk/internal/";
+    private static final String OBJECT_CLASS = "java/lang/Object";
     
     private final Set<String> classesToInclude;
     private final Map<String, String[]> references;
@@ -134,7 +138,14 @@ public final class ExtractJdkApis {
 
     @Override
     public void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
+      // remove references to internal JDK classes:
+      if (superName.startsWith(REPLACE_INTERNAL_PREFIX)) {
+        superName = OBJECT_CLASS;
+      }
+      interfaces = Arrays.stream(interfaces).filter(c -> !c.startsWith(REPLACE_INTERNAL_PREFIX)).toArray(String[]::new);
+      // call classwriter
       super.visit(Opcodes.V11, access, name, signature, superName, interfaces);
+      // update references to other classes (so we can figure out what is needed to be packaged in JAR):
       if (isVisible(access)) {
         classesToInclude.add(name);
       }
diff --git a/lucene/core/src/generated/jdk/jdk20.apijar b/lucene/core/src/generated/jdk/jdk20.apijar
index de737b7eb75..45bde0c5ca2 100644
Binary files a/lucene/core/src/generated/jdk/jdk20.apijar and b/lucene/core/src/generated/jdk/jdk20.apijar differ
```

**Comment by uschindler** [comment]
OK, see #12329.

I just check how to report the remaining "seen" classes not packaged. In ideal world it should only contain public JDK classes, but we should report them to make debugging easier in future.

**Comment by ChrisHegarty** [comment]
Just for reference, this is the problematic dependency:
  `jdk.incubator.vector.Vector<E extends java.lang.Object> extends jdk.internal.vm.vector.VectorSupport$Vector<E>`

I think that your proposed change is fine. Alternatively we could determine accessibility / visibility of the super class / interface by reading it from the jrt. But this is probably overkill for this one particular case.

**Comment by uschindler** [comment]
> Just for reference, this is the problematic dependency: `jdk.incubator.vector.Vector<E extends java.lang.Object> extends jdk.internal.vm.vector.VectorSupport$Vector<E>`

Yes, I looked at the source code, too. I have no idea why it was done like that, looks strange to me. It only works because the public members of that class are not visible to the outside, although inherited (which is another crazy thing in the module system).

**Comment by ChrisHegarty** [comment]
Don't worry, I'll not merge without our explicit LGTM.   Take your time, I just wanted to get the tests running, etc.

**Review by uschindler — APPROVED** [review]
Looks fine. I also tested it locally:
- Regenerating the apijars worked without problem
- Compilation worked

**Pull request merged**
