### PR TITLE
Fixed bit set vector

### PR DESCRIPTION
**Pull request by risdenk**

### CODE REVIEW

**Comment by risdenk** [comment]
@benwtrent here are some jmh benchmarks run from this branch. basically on m2 pro macbook and m7g instances - no change. On m7i instance there was some improvement only for short array sizes. Most of the time is spent in updating the array.

```
./gradlew :lucene:benchmark-jmh:assemble

java --module-path lucene/benchmark-jmh/build/benchmarks --module org.apache.lucene.benchmark.jmh FixedBitSetBenchmark
```

m2 macbook pro bitsize of 128 for preferred species on jdk 21
```
Benchmark                                     (size)   Mode  Cnt       Score       Error   Units
FixedBitSetBenchmark.fixedBitSetAnd             1024  thrpt   15  183024.773 ± 5502.789  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd            10240  thrpt   15   40736.755 ± 2802.097  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd           102400  thrpt   15    4851.307 ±  176.865  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd          1024000  thrpt   15     287.924 ±    1.844  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd         10240000  thrpt   15      29.162 ±    0.146  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd        102400000  thrpt   15       2.503 ±    0.042  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector       1024  thrpt   15  185351.585 ±  779.640  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector      10240  thrpt   15   42331.272 ± 3062.637  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector     102400  thrpt   15    4722.656 ±  701.887  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector    1024000  thrpt   15     291.871 ±    2.028  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector   10240000  thrpt   15      29.760 ±    0.108  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector  102400000  thrpt   15       2.515 ±    0.025  ops/ms
FixedBitSetBenchmark.fixedBitSetXor             1024  thrpt   15  186939.704 ± 1009.492  ops/ms
FixedBitSetBenchmark.fixedBitSetXor            10240  thrpt   15   39273.618 ± 4409.987  ops/ms
FixedBitSetBenchmark.fixedBitSetXor           102400  thrpt   15    4854.171 ±  153.207  ops/ms
FixedBitSetBenchmark.fixedBitSetXor          1024000  thrpt   15     287.090 ±    2.588  ops/ms
FixedBitSetBenchmark.fixedBitSetXor         10240000  thrpt   15      29.199 ±    0.137  ops/ms
FixedBitSetBenchmark.fixedBitSetXor        102400000  thrpt   15       2.483 ±    0.098  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector       1024  thrpt   15  183748.380 ± 1784.546  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector      10240  thrpt   15   42135.988 ± 1044.335  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector     102400  thrpt   15    4698.301 ±  589.486  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector    1024000  thrpt   15     286.415 ±    7.291  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector   10240000  thrpt   15      29.182 ±    0.313  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector  102400000  thrpt   15       2.544 ±    0.207  ops/ms
```


c7g aws instance with `INFO: Java vector incubator API enabled; uses preferredBitSize=256; FMA enabled` on jdk 21
```
Benchmark                                     (size)   Mode  Cnt       Score      Error   Units
FixedBitSetBenchmark.fixedBitSetAnd             1024  thrpt   15  103744.332 ± 2222.149  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd            10240  thrpt   15   26435.735 ±  760.113  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd           102400  thrpt   15    3548.496 ±   12.370  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd          1024000  thrpt   15     220.686 ±    0.404  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd         10240000  thrpt   15      22.306 ±    0.024  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd        102400000  thrpt   15       2.083 ±    0.019  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector       1024  thrpt   15  140169.058 ± 1822.592  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector      10240  thrpt   15   28495.474 ± 2103.457  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector     102400  thrpt   15    3391.169 ±  261.299  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector    1024000  thrpt   15     234.190 ±    0.622  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector   10240000  thrpt   15      20.199 ±    0.101  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector  102400000  thrpt   15       1.722 ±    0.005  ops/ms
FixedBitSetBenchmark.fixedBitSetXor             1024  thrpt   15  103478.516 ± 3336.075  ops/ms
FixedBitSetBenchmark.fixedBitSetXor            10240  thrpt   15   27173.709 ±  441.822  ops/ms
FixedBitSetBenchmark.fixedBitSetXor           102400  thrpt   15    3550.565 ±   21.300  ops/ms
FixedBitSetBenchmark.fixedBitSetXor          1024000  thrpt   15     220.728 ±    0.342  ops/ms
FixedBitSetBenchmark.fixedBitSetXor         10240000  thrpt   15      22.287 ±    0.016  ops/ms
FixedBitSetBenchmark.fixedBitSetXor        102400000  thrpt   15       2.084 ±    0.017  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector       1024  thrpt   15  142067.543 ± 6697.089  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector      10240  thrpt   15   28618.070 ± 1749.192  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector     102400  thrpt   15    3467.767 ±  251.337  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector    1024000  thrpt   15     233.871 ±    0.351  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector   10240000  thrpt   15      20.173 ±    0.120  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector  102400000  thrpt   15       1.727 ±    0.006  ops/ms
```

c7i.2xlarge aws instance with 512 preferred bit size on jdk 21
```
Benchmark                                     (size)   Mode  Cnt       Score       Error   Units
FixedBitSetBenchmark.fixedBitSetAnd             1024  thrpt   15  115338.102 ±  1578.331  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd            10240  thrpt   15   57236.967 ±  1938.814  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd           102400  thrpt   15    9355.549 ±    78.470  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd          1024000  thrpt   15     394.832 ±     1.430  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd         10240000  thrpt   15      18.576 ±     0.696  ops/ms
FixedBitSetBenchmark.fixedBitSetAnd        102400000  thrpt   15       1.292 ±     0.028  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector       1024  thrpt   15  237134.798 ±  2778.003  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector      10240  thrpt   15   64773.668 ± 13412.499  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector     102400  thrpt   15    7548.625 ±  1278.444  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector    1024000  thrpt   15     375.300 ±    21.939  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector   10240000  thrpt   15      18.167 ±     0.658  ops/ms
FixedBitSetBenchmark.fixedBitSetAndVector  102400000  thrpt   15       1.308 ±     0.022  ops/ms
FixedBitSetBenchmark.fixedBitSetXor             1024  thrpt   15  118689.304 ±  1297.567  ops/ms
FixedBitSetBenchmark.fixedBitSetXor            10240  thrpt   15   58491.149 ±  1873.067  ops/ms
FixedBitSetBenchmark.fixedBitSetXor           102400  thrpt   15    9361.477 ±    83.379  ops/ms
FixedBitSetBenchmark.fixedBitSetXor          1024000  thrpt   15     395.261 ±     1.586  ops/ms
FixedBitSetBenchmark.fixedBitSetXor         10240000  thrpt   15      18.506 ±     1.074  ops/ms
FixedBitSetBenchmark.fixedBitSetXor        102400000  thrpt   15       1.292 ±     0.026  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector       1024  thrpt   15  238452.717 ±  1205.654  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector      10240  thrpt   15   62637.015 ± 10901.087  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector     102400  thrpt   15    7388.709 ±  1073.625  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector    1024000  thrpt   15     381.209 ±    21.748  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector   10240000  thrpt   15      18.510 ±     0.943  ops/ms
FixedBitSetBenchmark.fixedBitSetXorVector  102400000  thrpt   15       1.300 ±     0.022  ops/ms
```

**Comment by risdenk** [comment]
I ran with profiling and grabbed some screenshots to show that its all updating the array.

```
java --module-path lucene/benchmark-jmh/build/benchmarks --module org.apache.lucene.benchmark.jmh FixedBitSetBenchmark.fixedBitSetAnd -p size=1024000 -prof 'async:libPath=/Users/kevin.risden/Downloads/async-profiler-3.0-macos/lib/libasyncProfiler.dylib;event=cpu;alloc=1k;lock=1us;output=jfr;interval=1'
```
Screenshot 2024-09-26 at 12 25 21
Screenshot 2024-09-26 at 12 25 40

**Comment by risdenk** [comment]
Maybe @benwtrent you have a good idea how to interpret these results? This was more me just playing around to see if this would help. It doesn't seem to hurt much but also didn't seem to improve. The autovectorization stuff makes sense. I don't quite understand why the 512 preferred size saw a speedup but only in the smaller array size cases.

**Comment by benwtrent** [comment]
I don't know why the smaller size saw a speed up, but I am pretty sure Java auto vectorization only vectorizes up until AVX256. So I would expect 512 to see an improvement. It's unintuitive to me why only smaller vectors saw an improvement.

Maybe auto-vectorization didn't kick in at all for the smaller vectors?



I will have to look more later. I still don't have power and such due to hurricane Helene in the US.

**Comment by risdenk** [comment]
assembly output from my m2 macbook. looks like at least vectorization kicked in from a quick glance.

[jmh_output_assembly.txt.gz](https://github.com/user-attachments/files/17215143/jmh_output_assembly.txt.gz)

**Comment by benwtrent** [comment]
Yeah, I poked around and it just seems like unloading the CPU vectors back into an array eats all performance gains.

I tried some reorganization to see if there was a better way, and there just doesn't seem to be :/

**Comment by risdenk** [comment]
Thanks appreciate the second set of eyes. Glad to know I'm not going crazy. I also didn't see a good way forward for updating the array.

**Pull request closed without merging**
