### PR TITLE
LUCENE-10003 No C style array declaration

### PR DESCRIPTION
**Pull request by dsmiley**
https://issues.apache.org/jira/browse/LUCENE-10003

The first commit was purely automated by IntelliJ.
The second commit are my hand edits to other spots IntellIJ didn't find because it was in a comment or some other file like a .jflex.  These hand edits were found via 
```
^(?!\s*(\/\/|\/?\*).*).*\b((?!instanceof)\w+)\s+\w+(\[])+\s*[=,;)]
```
Expect a separate PR to add checks to prevent this syntax via tooling.

### CODE REVIEW

**Comment by rmuir** [comment]
Why are we not doing this with spotless? As mentioned on the JIRA, I'm really -1 on the approach of enforcing *formatting* with anything but spotless. Sorry, it will just be annoying. The purpose of spotless is to avoid troubles like these.

**Comment by dsmiley** [comment]
This PR isn't about automatic enforcement so I think your veto is intended at the conversation in the JIRA issue about how to enforce.

**Comment by dsmiley** [comment]
I think this PR is ready; I've made the changes.  WDYT @dweiss @rmuir ?  Remember this is just the rote changes, mostly done via IntelliJ's inspection automation.

**Review by dweiss — APPROVED** [review]
I'm fine with these cleanups. Thanks!

**Pull request merged**
