### PR TITLE
Add migration note about the deprecation of optional RegExp complement syntax

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit adds a migration note about the deprecation of optional RegExp complement support.

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
Relates to Elasticsearch issue https://github.com/elastic/elasticsearch/issues/112453

**Comment by ChrisHegarty** [comment]
The removal of the optional complement syntax is technically a "breaking" change. It is of course fine to do such things in a major release, no issue there. Just want to ensure that it is intentional, and we provide whatever guidance is necessary in the migration, etc.

**Comment by mikemccand** [comment]
Thanks @ChrisHegarty for catching this!  It's important to document all breaks in `MIGRATE.md`.

I'm trying to understand why/when we removed this operator.  Was it really during [adding NFA support](https://issues.apache.org/jira/browse/LUCENE-10010) (linked from your linked Elasticsearch issue)?  I don't think that was intentional, or (more likely) I at least don't remember it -- I thought that change was purely additive.

**Comment by mikemccand** [comment]
I think it was [this commit](https://github.com/apache/lucene/commit/84e4b85b094ccf2dc248ad90a302307d3618b81e) that removed it ...?

**Comment by rmuir** [comment]
I removed it. I don't wish to revisit the situation. But it was not enabled by default for a reason.

**Review by rmuir — APPROVED** [review]
maybe if you want, mention that complement-of-range/label (e.g. `[^a-z]`) is still supported. This is the common use case and does not require exponential time.

**Comment by rmuir** [comment]
maybe this small post with diagram helps explain the situation: I hope it is more clear that there's no way we could support "let caller decide NFA vs DFA" with this operator: https://eugene-eeo.github.io/blog/nfa-complement.html

**Comment by rmuir** [comment]
and the title of this video can't be beat: https://www.youtube.com/watch?v=bbMku8ZAoBk

**Comment by mikemccand** [comment]
Phew, thank you for the historical context @rmuir!!  I forgot about the horrors of complementing NFAs... I love that talk title.

**Review by mikemccand — APPROVED** [review]
Thanks @ChrisHegarty!

**Comment by ChrisHegarty** [comment]
> Sorry, i was a bit offended that it might have been accidental :)

Apologies. My wording was a little clumsy. No offence intended.

> maybe if you want, mention that complement-of-range/label (e.g. [^a-z]) is still supported. This is the common use case and does not require exponential time.

Good idea. I'll add something about this.

**Comment by rmuir** [comment]
> Apologies. My wording was a little clumsy. No offence intended.

no need, nobody's fault. I read too far into @mikemccand comment without enough caffeine

**Comment by rmuir** [comment]
also just FYI

Operations.complement() still exists if you need it. And it documents the horrors that it does and requires you to pass work limit since determinization is necessary for correctness.

Hence instead of:
```java
var automaton = new Regexp("~(crazystuff)").toAutomaton();
```

you can do:
```java
var automaton = Operations.complement(new Regexp("(crazystuff").toAutomaton(), MY_DETERMINIZE_WORK_LIMIT);
```

The key to this change is that regexp parsing doesn't implicitly minimize() or determinize() whenever it feels like it. Instead, it is the user's choice (caller responsibility).

**Comment by ChrisHegarty** [comment]
Thank @rmuir. I included that advice in the migration note.

**Review by rmuir — APPROVED** [review]

**Comment by rmuir** [comment]
This is the best alternative I could come up with. For the user it just kicks the can down the road, but that's probably years out until the next release so it can make the change easier to cope with? https://github.com/apache/lucene/pull/13739

Meanwhile we can just remove it from `main` as soon as 10.x is branched and proceed normally with improving NFA support.

**Review by rmuir — APPROVED** [review]

**Pull request merged**
