### PR TITLE
Remove the HPPC dependency from all modules and add the required classes to the hppc fork.

### PR DESCRIPTION
**Pull request by bruno-roustant**
- Add the required classes to the hppc fork.
- Remove the hppc dependency from the facet, join, spatial modules.
- Remove the hppc version from versions.props and versions.lock.

It remains to move the hppc fork to oal.internal.

### CODE REVIEW

**Review by uschindler — COMMENTED** [review]
Looks fine; i also like that you updated the classes to latest version which may have fixed some bugs.

There is one issue which already existed: The classes are public and also have no `@lucene.internal` in their javadocs. Maybe we should add this. The other suggestion was brought in by Dawid:
- Move the classes to `org.apache.lucene.internal.hppc` package which is not exported in module-info
- Add qualified exports to the module-info only for the Lucene modules which actually use the classes

Not sure if the move to internal package should be part of this PR, but adding the Javadocs comment to mark them as internal should be done here (for all classes, also those not modified).

**Comment by uschindler** [comment]
Ah I see you mentioned the missing move in the PR description, sorry!

So except the `@lucene.internal` javadocs (should be added always, also when in private package), +1

**Comment by dweiss** [comment]
I'll do it.

**Comment by bruno-roustant** [comment]
Ok, Dawid I let you move the fork.
I added the @lucene.internal annotations. I like that this hppc integration is cleaner and well defined now.

**Review by uschindler — APPROVED** [review]

**Comment by bruno-roustant** [comment]
Do you want to move in this PR, or in another PR once this one is merged?

**Comment by dweiss** [comment]
I'll push to this PR, if you don't mind?

**Review by ChrisHegarty — APPROVED** [review]
Thank you for doing this. While there is still a little left to do in this PR, it looks like it's going in the right direction.

**Comment by bruno-roustant** [comment]
I agree with the baby step, and this PR is already massive.

**Review by dweiss — APPROVED** [review]

**Comment by dweiss** [comment]
I think the only thing missing is perhaps a changes entry and migration entry warning people that the dependency is gone and that the currently exposed internal package will be gone without a warning in the future (if we want to apply it to 9x as well).

**Review by uschindler — APPROVED** [review]
Looks ok as baby step.

About the test strategy: making tests modules is not a good idea, as this requires to open many more classes and it's also not the correct way for unit tests, which should run in same module.

Patching the module with test classes should work and is done by other projects, but I remember that you faced some issues.

Maybe another "hack": For running tests just pack a secondary jar file with main classes and tests including the module info? It's a duplicate but would make the tests and main classes a module with same name so all exports work.

Module patching should achieve the same, but I don't remember what your issues were.

At least for the MR-JAR compilation patching works, never tried at runtime.

**Comment by dweiss** [comment]
I can't remember what the problem was, to be honest. Will have to return to it.

**Comment by bruno-roustant** [comment]
Thank you Dawid!
I can work on the backport to 9x.

How long should we wait for this PR before merging it?
Given it is large, it has higher probabilities of conflicts, in main and 9x, so I would prefer to merge it quickly.

**Comment by dweiss** [comment]
I'd merge it right away, I don't see the point in waiting. If there are conflicts - they should be easy to resolve.

**Comment by uschindler** [comment]
Go ahead!

**Comment by bruno-roustant** [comment]
Backport to branch_9x complete!

**Pull request merged**
