### PR TITLE
LUCENE-10393: Unify resource loader in kuromoji and nori

### PR DESCRIPTION
**Pull request by mocobeta**
See https://issues.apache.org/jira/browse/LUCENE-10393

### CODE REVIEW

**Comment by mocobeta** [comment]
The test fails since this wouldn't work on module mode (the resource loader attempts to read resources in another module). I'll look at it later.

**Comment by mocobeta** [comment]
I opened `o.a.l.a.ja.dict` and `o.a.l.a.ko.dict` to `analysis-common` module to allow `DictionaryResourceLoader` (common utility) to read dictionary resources in kuromoji and nori module.

Then `TestModuleLayer.testAllOpenAnalysisPackagesInSync()` says
```
error: [Opens should only be targeted to Lucene Core.] 
```

Is there a way to lose this restriction? I don't think the resource loader should resident in lucene-core, it's too specific to kuromoji and nori (and a bit hacky; I think the two-args constructor should be break down into two constructors at the next major release - one for resources on the classpath and another for ones on the file path. In the future, I hope we will be able to resolve LUCENE-8816 then we'll need only one constructor that loads the dictionary resources from classpaths).

**Comment by mocobeta** [comment]
Hi @uschindler, I think I need your review or opinion.
This reduces code duplication and technically works, but adds "open" directives in the module descriptors.
If this approach is not preferable, I'll back the dictionary loader utility to both kuromoji and nori - we'll need to maintain two dictionary loaders as before though, I think the code was simplified by the refactoring here.

**Review by uschindler — CHANGES_REQUESTED** [review]
Hi,
I was not happy with DictionaryLoader at all and Robert and I wanted to remove it already in 2012 when we rewrote the code. But this was one open point we forgot about.

The code around the Resource Types is in my personal opinion total bullshit (CLASSPATH vs. FILE) and is not conformant to any Java standard out there. It breaks with modules and the enum is a misnomer anyways -- there's no concept of "Classpath". In short: DictionaryLoader should completely be removed and the ConnectionCosts and Dictionary classes should simply open InputStreams with hardcoded Class#getResourceAsStream like we do this at other places (e.g. to load stop words files). There's no need to make this customizeable or allow to load those files from arbitrary file system locations. We should never ever use opens (there was a reason why I restricted opens to Lucene core only!). In addition, you can't even load the dictionaries from arbitrary files, because there's no public API available anymore (we have hidden it completely).

I already wanted to start a separate PR about this. Please don't do the current code or add opens. Just simple remove the DictionaryLoader class completely and just use getResourceAsStream() directly. Most important: Remove the ENUM, its a misnomer anyways (CLASSPATH is incorrect).

To load a custom Dictionary one can pass InputStream, too.

**Comment by uschindler** [comment]
> Please don't do the current code or add opens. Just simple remove the DictionaryLoader class completely and just use getResourceAsStream() directly. Most important: Remove the ENUM, its a misnomer anyways (CLASSPATH is incorrect).

This is exactly the same: Never ever delegate opening class' resources to other code. Call getResourceAsStream() from the class that wants to load the files and where they reside. Don't add abstractions: ConnectionCosts class should call getResourceAsStream in its own code and load the file placed next to the class in JAR.

**Comment by mocobeta** [comment]
Thanks for your comment. Minor correction - we currently don't even have DictionaryLoader but the resource loading methods are embedded in two BinaryDictionarys themselves. My intention here is, first simplify the resource loading stuff then break it down into proper methods. I know the current switching between classpath/filepath is not good at all and agree with we should remove it at some point.
I'll explore if we can remove the delegation around resource loading without changing the API interface (for now).

**Comment by uschindler** [comment]
> I'll explore if we can remove the delegation around resource loading without changing the API interface (for now).

I won't care about API, it is all not really public, because most of the stuff may be public visible, but can't be used, because the JapaneseTokenizer can't really load any other resources.

**Comment by uschindler** [comment]
I would really not move this dictionary code to commons module and add opens. This is as bad as having the (now deprecated) methods in IOUtils to load stopwords files. Loading of a class resource must always be done by the class itsself not delegated to somebody else - because it is caller-sensitive!

**Comment by mocobeta** [comment]
Personally, I don't care about the APIs (two-args constructors to load external resources) too, but I know there are people who need and add the feature to kuromoji and nori (I forgot the issue).

> I would really not move this dictionary code to commons module and add opens. 

Sure, yes - I understood your intention.

**Comment by mocobeta** [comment]
I will open an issue to clean up the constructors' signatures for the dictionaries if I have a chance. I might need some time and good motivation for the refactoring.

**Comment by uschindler** [comment]
Thanks. This really needs motivation, one reason why I did not do it!

**Comment by msokolov** [comment]
I think the only reason why we have the file loading option is to support unit testing the dictionary-loading components. Maybe there's a better way?

**Comment by mocobeta** [comment]
I opened a draft PR: https://github.com/apache/lucene/pull/643.
Would you take a look at it?

**Pull request closed without merging**
