### PR TITLE
Handle jdk.internal classes mentioned in vector superclass or interfaces during extraction

### PR DESCRIPTION
**Pull request by uschindler**
This fixes problem on branch_9x backport (#12327) where the private superclasses are not available in Java 11.

On Java 17 it just worked so we didn't figure. :-(

### CODE REVIEW

**Review by ChrisHegarty — APPROVED** [review]

**Comment by uschindler** [comment]
Thanks for review, i added a logging statement to show all classes which were not referenced but not included. This would solve problems like this in future.

Will merge when CI is happy.

**Comment by uschindler** [comment]
Looks like this:

```
> Task :lucene:core:generateJdkApiJar19
Transforming 31 class files in [/modules/java.base]...
Writing 26 visible classes for [/modules/java.base]...
Writing stub for class: java/lang/foreign/AbstractLayout
Writing stub for class: java/lang/foreign/Addressable
Writing stub for class: java/lang/foreign/FunctionDescriptor
Writing stub for class: java/lang/foreign/GroupLayout
Writing stub for class: java/lang/foreign/Linker
Writing stub for class: java/lang/foreign/MemoryAddress
Writing stub for class: java/lang/foreign/MemoryLayout
Writing stub for class: java/lang/foreign/MemoryLayout$PathElement
Writing stub for class: java/lang/foreign/MemorySegment
Writing stub for class: java/lang/foreign/MemorySession
Writing stub for class: java/lang/foreign/SegmentAllocator
Writing stub for class: java/lang/foreign/SequenceLayout
Writing stub for class: java/lang/foreign/SymbolLookup
Writing stub for class: java/lang/foreign/VaList
Writing stub for class: java/lang/foreign/VaList$Builder
Writing stub for class: java/lang/foreign/ValueLayout
Writing stub for class: java/lang/foreign/ValueLayout$OfAddress
Writing stub for class: java/lang/foreign/ValueLayout$OfBoolean
Writing stub for class: java/lang/foreign/ValueLayout$OfByte
Writing stub for class: java/lang/foreign/ValueLayout$OfChar
Writing stub for class: java/lang/foreign/ValueLayout$OfDouble
Writing stub for class: java/lang/foreign/ValueLayout$OfFloat
Writing stub for class: java/lang/foreign/ValueLayout$OfInt
Writing stub for class: java/lang/foreign/ValueLayout$OfLong
Writing stub for class: java/lang/foreign/ValueLayout$OfShort
Writing stub for class: java/nio/channels/FileChannel
Referenced classes not included: [java/nio/channels/ScatteringByteChannel, java/nio/channels/GatheringByteChannel, java/nio/channels/SeekableByteChannel, java/nio/channels/spi/AbstractInterruptibleChannel, java/lang/AutoCloseable, java/lang/Object]

> Task :lucene:core:generateJdkApiJar20
Transforming 30 class files in [/modules/java.base]...
Writing 29 visible classes for [/modules/java.base]...
Writing stub for class: java/lang/foreign/Arena
Writing stub for class: java/lang/foreign/FunctionDescriptor
Writing stub for class: java/lang/foreign/GroupLayout
Writing stub for class: java/lang/foreign/Linker
Writing stub for class: java/lang/foreign/Linker$Option
Writing stub for class: java/lang/foreign/Linker$Option$CaptureCallState
Writing stub for class: java/lang/foreign/MemoryLayout
Writing stub for class: java/lang/foreign/MemoryLayout$PathElement
Writing stub for class: java/lang/foreign/MemorySegment
Writing stub for class: java/lang/foreign/PaddingLayout
Writing stub for class: java/lang/foreign/SegmentAllocator
Writing stub for class: java/lang/foreign/SegmentScope
Writing stub for class: java/lang/foreign/SequenceLayout
Writing stub for class: java/lang/foreign/StructLayout
Writing stub for class: java/lang/foreign/SymbolLookup
Writing stub for class: java/lang/foreign/UnionLayout
Writing stub for class: java/lang/foreign/VaList
Writing stub for class: java/lang/foreign/VaList$Builder
Writing stub for class: java/lang/foreign/ValueLayout
Writing stub for class: java/lang/foreign/ValueLayout$OfAddress
Writing stub for class: java/lang/foreign/ValueLayout$OfBoolean
Writing stub for class: java/lang/foreign/ValueLayout$OfByte
Writing stub for class: java/lang/foreign/ValueLayout$OfChar
Writing stub for class: java/lang/foreign/ValueLayout$OfDouble
Writing stub for class: java/lang/foreign/ValueLayout$OfFloat
Writing stub for class: java/lang/foreign/ValueLayout$OfInt
Writing stub for class: java/lang/foreign/ValueLayout$OfLong
Writing stub for class: java/lang/foreign/ValueLayout$OfShort
Writing stub for class: java/nio/channels/FileChannel
Referenced classes not included: [java/nio/channels/ScatteringByteChannel, java/nio/channels/GatheringByteChannel, java/nio/channels/SeekableByteChannel, java/nio/channels/spi/AbstractInterruptibleChannel, java/lang/AutoCloseable, java/lang/Object]
Transforming 189 class files in [/modules/jdk.incubator.vector]...
Writing 21 visible classes for [/modules/jdk.incubator.vector]...
Writing stub for class: jdk/incubator/vector/AbstractVector
Writing stub for class: jdk/incubator/vector/ByteVector
Writing stub for class: jdk/incubator/vector/DoubleVector
Writing stub for class: jdk/incubator/vector/FloatVector
Writing stub for class: jdk/incubator/vector/IntVector
Writing stub for class: jdk/incubator/vector/LongVector
Writing stub for class: jdk/incubator/vector/ShortVector
Writing stub for class: jdk/incubator/vector/Vector
Writing stub for class: jdk/incubator/vector/VectorMask
Writing stub for class: jdk/incubator/vector/VectorOperators
Writing stub for class: jdk/incubator/vector/VectorOperators$Associative
Writing stub for class: jdk/incubator/vector/VectorOperators$Binary
Writing stub for class: jdk/incubator/vector/VectorOperators$Comparison
Writing stub for class: jdk/incubator/vector/VectorOperators$Conversion
Writing stub for class: jdk/incubator/vector/VectorOperators$Operator
Writing stub for class: jdk/incubator/vector/VectorOperators$Ternary
Writing stub for class: jdk/incubator/vector/VectorOperators$Test
Writing stub for class: jdk/incubator/vector/VectorOperators$Unary
Writing stub for class: jdk/incubator/vector/VectorShape
Writing stub for class: jdk/incubator/vector/VectorShuffle
Writing stub for class: jdk/incubator/vector/VectorSpecies
Referenced classes not included: [java/lang/Enum, java/lang/Object]
```

**Comment by uschindler** [comment]
Did you generate everything?

**Comment by uschindler** [comment]
Ahhhhh, the signature because it is generic....

**Comment by uschindler** [comment]
Here you see it, must be the signature as it shows generics:

```
>javap Vector.class | grep internal
public abstract class jdk.incubator.vector.Vector<E> extends jdk.internal.vm.vector.VectorSupport$Vector<E> {
```

Uwe

**Comment by ChrisHegarty** [comment]
Here's what I'm doing:

```
$ ./gradlew :lucene:core:regenerate
```

Debugging the extractor Cleaner, I can see that _superName_ is replaced with _java/lang/Object_. But for some reason the apijar is not updated! ?

```
$ cat T.java
import jdk.incubator.vector.*;

public class T {
    static final FloatVector acc1 = FloatVector.zero(FloatVector.SPECIES_PREFERRED);
}
$ 
$ /Users/chegar/binaries/jdk-11.0.12.jdk/Contents/Home/bin/javac --patch-module java.base=lucene/core/src/generated/jdk/jdk20.apijar --add-exports=java.base/jdk.incubator.vector=ALL-UNNAMED T.java
T.java:4: error: cannot access VectorSupport
    static final FloatVector acc1 = FloatVector.zero(FloatVector.SPECIES_PREFERRED);
                                               ^
  class file for jdk.internal.vm.vector.VectorSupport not found
```

```

cd lucene/core/src/generated/jdk
$ unzip jdk20.apijar 
...
javap -v -p jdk/incubator/vector/Vector.class  | more
Classfile /Users/chegar/git/lucene/lucene/core/src/generated/jdk/jdk/incubator/vector/Vector.class
  Last modified 1 Jan 2022; size 10382 bytes
  MD5 checksum 9d8f0c7cc22956e602994bfc4f1507b4
public abstract class jdk.incubator.vector.Vector<E extends java.lang.Object> extends jdk.internal.vm.vector.VectorSupport$Vector<E>
...
```

**Comment by uschindler** [comment]
The problem is the signature, I verified it. Let me think how to do that.

**Comment by uschindler** [comment]
This can't be repaired, as the generic signature refers to the other class which has generics, too. By replacing it with `java.lang.Object` it breaks horribly (as `Object` has no type parameters).

If I just null out the generic signature, javac reports:

```
  bad class file: C:\Users\Uwe Schindler\Projects\lucene\lucene\lucene\core\src\generated\jdk\jdk20.apijar(/jdk/incubator/vector/Vector.class)
    undeclared type variable: E
```

So the only route here is my original idea to include the internal classes intothe JAR -- unfortunately.

**Comment by uschindler** [comment]
Keep the backport open, I will try to fix it later this afternoon, I first have to do something else.

**Comment by uschindler** [comment]
I think I can fix it, we need a SignatureVisitor to remove the superclass.

**Comment by ChrisHegarty** [comment]
For now, I just updated the glob in the 9x Panama vector branch to include VectorSupport, see https://github.com/apache/lucene/pull/12327/commits/7c353f045cfbc42de33818add402c9de564e3ee6

```diff
--- a/gradle/generation/extract-jdk-apis/ExtractJdkApis.java
+++ b/gradle/generation/extract-jdk-apis/ExtractJdkApis.java
@@ -50,7 +50,7 @@ public final class ExtractJdkApis {
   private static final FileTime FIXED_FILEDATE = FileTime.from(Instant.parse("2022-01-01T00:00:00Z"));
   
   static final Map<String,String> CLASSFILE_MATCHERS = Map.of(
-      "java.base",             "glob:java/{lang/foreign/*,nio/channels/FileChannel,util/Objects}.class",
+      "java.base",             "glob:{java/lang/foreign/*,java/nio/channels/FileChannel,java/util/Objects,jdk/internal/vm/vector/VectorSupport*}.class",
       "jdk.incubator.vector",  "glob:jdk/incubator/vector/*.class"
   );
```

**Comment by ChrisHegarty** [comment]
yeah, it breaks - in the same way - "class file for jdk.internal.vm.vector.VectorSupport not found"

**Comment by uschindler** [comment]
I have no idea way they had did this crazy class layout. There's also the special javadoc tag "@hidden" which looks like a crazy workaround.

It looks like we have to include also the superclasss. There are also interfaces which on the other hand are not referenced downstream, so the current code to hide them is fine.

**Comment by uschindler** [comment]
Here is this mess with the `@hidden` Javadoc tag explained: https://bugs.openjdk.org/browse/JDK-8277074

As you see we are in the areas of heavy hacks with visibility. So we can't solve this in a general way.  I tend to hardcode the exact classes needed into the extractor as patterns.

I will also change the patterns a bit by having a list of filename patterns without module per Java version.

**Comment by ChrisHegarty** [comment]
> So we can't solve this in a general way. I tend to hardcode the exact classes needed into the extractor as patterns.

++ while not perfect, it is understandable and maintainable. The extra logging is also very welcome, which will help future potential changes in this area.

**Comment by uschindler** [comment]
@ChrisHegarty: do you want to crosscheck the 9.x branch? (don't forget to re-add the java/lang/Objects class pattern).

**Review by ChrisHegarty — APPROVED** [review]
The changes look good. And maintainable.  

I can confirm that it works on the 9x Panama_vector branch. 👍

**Comment by ChrisHegarty** [comment]
> Thanks, as always a fun to work together!

Absolutely. And thanks for fixing this so quickly.    So how to proceed?  I can merge in this PR commit (to he 9x_panama_branch), or we can coordinate and you can backport very quickly afterwards?

**Comment by uschindler** [comment]
I would merge this to the 9x_panama_branch. I don't want the huge binary file go into the main repo's Git state (I am afraid of Dawid and Robert about binaries in checkouts).

**Pull request merged**
