### PR TITLE
An improved check for ignoring the c2-crash test if running on a client compiler.

### PR DESCRIPTION
**Pull request by dweiss**
Follow-up to #12905

### CODE REVIEW

**Comment by uschindler** [comment]
FYI, there's also `Constants.IS_HOTSPOT_VM`. Just in case :-) But I don't think that's usefil here as additional constraint.

**Review by uschindler — CHANGES_REQUESTED** [review]
Remove this method, too (it is dead code):

https://github.com/apache/lucene/pull/12953/files#diff-a55d6b740bc9510cd53e003a0f209951ea914ce3f9998fa333df95f7445a46d4R181

**Comment by uschindler** [comment]
This works and you can still run the tests with `export CI=true`.

https://github.com/apache/lucene/blob/f6582ce04830b0122de90a045f1abc595a411aa1/gradle/testing/defaults-tests.gradle#L54

**Comment by dweiss** [comment]
I've removed the unused method and added hotspot check, thanks Uwe.

**Review by uschindler — APPROVED** [review]

**Comment by dweiss** [comment]
I've applied to main and branch_9x.

**Comment by ChrisHegarty** [comment]
I'm way too slow here, sorry.  Belated LGTM. And thanks for following up on this.

**Pull request merged**
