### PR TITLE
Rewrite newSlowRangeQuery to MatchNoDocsQuery when upper > lower

### PR DESCRIPTION
**Pull request by ioanatia**
We already have a check in place that rewrites `SortedNumericDocValuesRangeQuery` to a `FieldExistsQuery` when the lookup range interval is `[ Long.MIN_VALUE, Long.MAX_VALUE]`.

This PR adds another check to see whether the upper bound is smaller than the lower bound.
If it is not, we can confidently rewrite `SortedNumericDocValuesRangeQuery` to a `MatchNoDocsQuery`.

### CODE REVIEW

**Comment by jpountz** [comment]
This makes sense to me, can you add a CHANGES entry under 9.11?

**Comment by ioanatia** [comment]
thank you @jpountz
I added the changelog so this is ready for another review

**Comment by jpountz** [comment]
@ioanatia Would you mind bumping this change to 9.12 since the 9.11 branch has been bumped in the meantime? Sorry for the inconvenience? The change looks good to me, I'll merge once this is done.

**Comment by ioanatia** [comment]
thank you for the merge - I was out for a few days and did not had a chance to bump the version.

**Pull request merged**
