### PR TITLE
unify exception thrown by regexp & check repetition range

### PR DESCRIPTION
**Pull request by tang-hi**
### Description
ISSUE #12251 

This pull request addresses two issues in the [RegExp.java code](https://github.com/apache/lucene/blob/a39885fdab93c4cbbcab8f3112c9783a05ca15a9/lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java#LL1088C3-L1111C4):

1. It unifies the exception handling by ensuring that IllegalArgumentException is thrown when Integer.parseInt fails, such as in cases of overflow, as per the method signature.
2. It adds a check for the correct order of the repetition range. Previously, the code would parse and accept invalid repetition ranges like "a{99,11}" that are not accepted by Java's Pattern. This update prevents such cases from being passed.

Original Code
````
  final RegExp parseRepeatExp() throws IllegalArgumentException {
    RegExp e = parseComplExp();
    while (peek("?*+{")) {
      if (match('?')) e = makeOptional(flags, e);
      else if (match('*')) e = makeRepeat(flags, e);
      else if (match('+')) e = makeRepeat(flags, e, 1);
      else if (match('{')) {
        int start = pos;
        while (peek("0123456789")) next();
        if (start == pos) throw new IllegalArgumentException("integer expected at position " + pos);
        int n = Integer.parseInt(originalString.substring(start, pos));
        int m = -1;
        if (match(',')) {
          start = pos;
          while (peek("0123456789")) next();
          if (start != pos) m = Integer.parseInt(originalString.substring(start, pos));
        } else m = n;
        if (!match('}')) throw new IllegalArgumentException("expected '}' at position " + pos);
        if (m == -1) e = makeRepeat(flags, e, n);
        else e = makeRepeat(flags, e, n, m);
      }
    }
    return e;
  }
  ````

### CODE REVIEW

**Comment by rmuir** [comment]
NumberFormatException is a subclass of IllegalArgumentException already. Catching it and rethrowing it doesn't make any sense.

**Comment by tang-hi** [comment]
> NumberFormatException

@rmuir OH! I didn't verify whether NumberFormatException is a subclass of IllegalArgumentException. Upon reviewing [RegExp.java](https://github.com/apache/lucene/blob/a39885fdab93c4cbbcab8f3112c9783a05ca15a9/lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java#LL1215C7-L1233C10), I noticed that it catches the NumberFormatException and rethrows it as an IllegalArgumentException. I followed the same approach in my code. However, considering your feedback, it might be more appropriate to remove this try-catch block. What are your thoughts on this?

**Comment by mikemccand** [comment]
Thanks for incorporating @rmuir's feedback @tang-hi!  The change looks great to me: we catch an invalid usage and throw a clean exception in that case.  I'll merge!  Sorry for the long delay.

**Review by mikemccand — APPROVED** [review]

**Comment by mikemccand** [comment]
Merged to 10.0 and 9.9.0.  Thanks @tang-hi!

**Pull request merged**
