### PR TITLE
LUCENE-10041: Remove TieredMergePolicy's redundant query computation

### PR DESCRIPTION
**Pull request by gf53520**
[LUCENE-10041](https://issues.apache.org/jira/browse/LUCENE-10041)

# Description 
 In lucene 8.4 (Elasticsearch 7.6.2), all indices are enabled with soft-deletes. We found the TieredMergePolicy contains redundant query computation to acquire **numDeletesToMerge** for **findMerges**. According to code from [getSortedBySegmentSize](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/TieredMergePolicy.java#L303) , I think we should reuse the result of numDeletesToMerge which can reduce 3% CPU and some IO overheads.

# Solution
 Reuse the result of numDeletesToMerge

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/lucene/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Lucene maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.

### CODE REVIEW

**Comment by dnhatn** [comment]
@gf53520 Changes look good to me. Can you also override the new method in FilterMergePolicy?

**Comment by gf53520** [comment]
> @gf53520 Changes look good to me. Can you also override the new method in FilterMergePolicy?

Thanks @dnhatn.  I have just overridden the new method in FilterMergePolicy, Please take a took.

**Comment by dnhatn** [comment]
@gf53520 Sorry for the late response. I was offline last week. 

After taking another look, I think we should not introduce another `size` method in MergePolicy, but wrap MergeContext to cache `numDeletesToMerge` in SoftDeletesRetentionMergePolicy instead. I know this is not ideal, but it's less confusing than the current approach.

**Comment by gf53520** [comment]
> @gf53520 Sorry for the late response. I was offline last week.
> 
> After taking another look, I think we should not introduce another `size` method in MergePolicy, but wrap MergeContext to cache `numDeletesToMerge` in SoftDeletesRetentionMergePolicy instead. I know this is not ideal, but it's less confusing than the current approach.
ok, I think make that cache for SoftDeletesRetentionMergePolicy is more elegrant, considering that size method is only useful in soft-deletes case.

**Pull request closed without merging**
