### PR TITLE
#12911: regenerate binary FSTs for Nori and Kuromoji dictionaries to match current FST format

### PR DESCRIPTION
**Pull request by mikemccand**
This is the result of top-level `./gradlew regenerate` to rewrite all generated stuff in our source tree.  The only resulting `git diff` were the Nori and Kuromoji FST dictionaries.

Note that I had to use OpenJDK 21 to do this.  When I tried with JDK 17 (`openjdk full version "17.0.9+8"`) I hit these spooky errors:

```
/s1/l/99x/gradle/generation/extract-jdk-apis/ExtractJdkApis.java:192: error: illegal character: '\ufffd'
    public void visitPermittedSubclass???(String c) {
                                      ^
```
I think we should do this for 9.9.1?

### CODE REVIEW

**Review by ChrisHegarty — APPROVED** [review]
I dunno how to review this, so I generated the files myself and compared against those in your branch - they are identical. SO, LGTM.

**Review by dweiss — APPROVED** [review]
I don't think there's anything to review; what Chris did - run regenerate locally, see if there are any changes)  is the most you can do.

**Comment by mikemccand** [comment]
Thanks @ChrisHegarty and @dweiss -- I'll merge to 9.9.x, 9.x and main shortly.  Hmm, rather, I'll regen on the other two branches (not certain FST format is identical everywhere), and merge this onto 9.9.x.

**Comment by rmuir** [comment]
if it regenerates successfully and the test suite passes afterwards (which it seems they do), that's basically it

**Comment by mikemccand** [comment]
OK I regenerated these two FSTs on 9.9.x, 9.x, and main.

**Pull request merged**
