### PR TITLE
fail clearly on too-new JDK

### PR DESCRIPTION
**Pull request by rmuir**
Gradle will give a very confusing error, let's make it absolutely clear.
Screen_Shot_2022-04-19_at_08 28 26

### CODE REVIEW

**Review by mikemccand — APPROVED** [review]
Whoa, I love how simple this is!  Perfect.

**Comment by dweiss** [comment]
Yep. I wonder if we could do it in one script (the downloader?) to avoid running java so many times but overall I think it's better than before. :)

This also reminds me that the various java versions (minimum required for Lucene, minimum required for gradle) are scattered around in oh-so-many places. I wonder how we could somehow centralize this information. I don't have any clean ideas though.

**Review by dweiss — APPROVED** [review]

**Comment by rmuir** [comment]
> Yep. I wonder if we could do it in one script (the downloader?) to avoid running java so many times but overall I think it's better than before. :)

I agree with this (as someone who disables the daemon and runs the commands every time). The only reason I specified it as a different command was due to the fact that if the downloader fails, the error is "trapped" and an additional version-related error (that you need at least java 11) is printed... IMO that's a bit confusing, but I get it.

> 
> This also reminds me that the various java versions (minimum required for Lucene, minimum required for gradle) are scattered around in oh-so-many places. I wonder how we could somehow centralize this information. I don't have any clean ideas though.

Maybe it could be in a .properties file? Not gradle, not groovy, a real actual .properties file that we can read with java.io.Properties too?

**Comment by dweiss** [comment]
> Maybe it could be in a .properties file? Not gradle, not groovy, a real actual .properties file that we can read with java.io.Properties too?

I was thinking about something like this too, it's convenient. There is a number of those places referencing version numbers - I can't even remember them all. A commit list referencing LUCENE-10283 is a good place to start... :)

**Comment by rmuir** [comment]
> I agree with this (as someone who disables the daemon and runs the commands every time). The only reason I specified it as a different command was due to the fact that if the downloader fails, the error is "trapped" and an additional version-related error (that you need at least java 11) is printed... IMO that's a bit confusing, but I get it.

we can clean up exit status so that wrapperdownloader uses something other than `1` when it fails. that's also the same status old `java` uses when it doesn't recognize `--source` parameter. then we can move the version check into wrapperdownloader and only say "please make sure you're using at least java 11" when it is relevant (java itself fails).  and it is safe to only apply it to exit status `1` because it is only relevant to already-released older jvms. I will look into this.

**Comment by rmuir** [comment]
OK, @dweiss can you take another look when you get a chance?

java 8:
```
$ ./gradlew check
Unrecognized option: --source
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
ERROR: Something went wrong. Make sure you're using Java 11 or later.
```

java 18:
```
$ ./gradlew check
ERROR: java version must not be newer than 17 (unsupported by gradle), your version: 18
```

But there's still more to do. if you use java 11 it will still fail, just differently, based on our gradle actual gradle logic.

Let's say the user has java 9. It isn't good to tell a user to upgrade to java 11 or later (say they pick java 11), they download it, install it, only it then fails and says you need 17 or later. then the user download and install's the latest (say 18), only for it to fail yet one more time and tell them they need exactly 17... this is like leading them through a maze. So I want to clean up the messaging some more still...

java 11:
```
$ ./gradlew check
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build

FAILURE: Build failed with an exception.

* Where:
Script '/home/rmuir/workspace/lucene/gradle/validation/check-environment.gradle' line: 36

* What went wrong:
A problem occurred evaluating script.
> At least Java 17 is required, you are running Java 11 [OpenJDK 64-Bit Server VM 11.0.13+8]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

**Comment by rmuir** [comment]
OK, i cleaned up the messaging here to emit better messages so we don't lead users through a maze of downloading and retrying. I didn't touch the gradle checks. And yeah, it would be great to consolidate to a properties file (min and max versions?) so there is less places to change when we bump it, we could read the properties from this checker at least.

java 18
```
$ ./gradlew check
ERROR: java version be exactly 17, your version: 18

java 9
```
$ ./gradlew check
Unrecognized option: --source
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
ERROR: Something went wrong. Make sure you're using Java 17.
```

java 11:
```
$ ./gradlew check
ERROR: java version be exactly 17, your version: 11
```

**Comment by mocobeta** [comment]
> Maybe it could be in a .properties file? Not gradle, not groovy, a real actual .properties file that we can read with java.io.Properties too?

+1 to a single source of source/target Java version(s). A simple key-value format may be easily used from the outside world of java/gradle - github actions scripts or the smoke tester, and so on.

**Comment by rmuir** [comment]
> +1 to a single source of source/target Java version(s). A simple key-value format may be easily used from the outside world of java/gradle - github actions scripts or the smoke tester, and so on.

Yes, if everyone can really restrain themselves to keep such a thing actually a simple key-value (no groovy, no nonsense), then we can read it from java/groovy with `java.io.Properties` and it could be read from this bash script with `source`.

**Comment by dweiss** [comment]
Windows will be a problem, as it always is, argh.

**Comment by rmuir** [comment]
> Windows will be a problem, as it always is, argh.

why is windows a problem? this PR works perfectly fine on windows. I didnt touch the .bat file because, unlike the .sh file, it has no special error messaging. so there's nothing to be done with it.

**Comment by dweiss** [comment]
I'll take a look if I can modify the windows scripts the same way - it should be doable.

**Comment by rmuir** [comment]
There's no version numbers in the .bat script. Hence no need for it to be able to suck in .properties file?

**Comment by dweiss** [comment]
There's the emitted message there - I've just pushed a commit to your branch that does the same thing as the bash does. I think it's fine. We can probably add a test to check whether those scripts, even if hardcoded, are consistent with the property file (as the worst workaround).

**Comment by rmuir** [comment]
i'm fine with starting the properties file here, but the problem is not exactly new. really fixing all the stuff like smoketester, eclipse linter config, etc etc is gonna be some amount of work. Even the gradle is some work (there are version numbers everywhere).

**Comment by dweiss** [comment]
Yeah - I think we should do it as a separate issue. It'll be clearer.

**Comment by rmuir** [comment]
OK let's merge this for now and investigate the properties refactoring as a separate change.

**Pull request merged**
