### PR TITLE
Allow reusing indexed binary fields.

### PR DESCRIPTION
**Pull request by jpountz**
Today Lucene allows creating indexed binary fields, e.g. via `StringField(String, BytesRef, Field.Store)`, but not reusing them: calling `setBytesValue` on a `StringField` throws.

This commit removes the check that prevents reusing fields with binary values. I considered an alternative that consisted of failing if calling `setBytesValue` on a field that is indexed and tokenized, but we currently don't have such checks e.g. on numeric values, so it did not feel consistent.

Doing this change would help improve the [nightly benchmarks for the NYC taxis dataset](http://people.apache.org/~mikemccand/lucenebench/sparseResults.html) by doing the String -> UTF-8 conversion only once for keywords, instead of once for the `StringField` and one for the `SortedDocValuesField`, while still reusing fields.

### CODE REVIEW

**Comment by rmuir** [comment]
> I considered an alternative that consisted of failing if calling `setBytesValue` on a field that is indexed and tokenized

Can we just do this instead?

I think an important point here is that you shouldnt be calling setBytesValue if it is tokenized (TokenStream in use). You need Reader/String.

**Comment by rmuir** [comment]
and yeah, you don't have such checks on numeric values, but numeric values don't have TokenStream tokenization. Being consistent with them makes no sense, that isn't what this is about.

otherwise, if we cant agree here, lets just keep the restriction.

**Comment by rmuir** [comment]
the fact that the tests pass with this change is really upsetting too. we should at least add checks for the type of luser moments we want to prevent, e.g. calling setBytesRef on a fucking TextField, etc. If we dont add these checks then users are going to invoke these methods and... nothing will happen at all... or something that isn't what they want.

**Comment by jpountz** [comment]
I'm good with adding more validation, I pushed more changes:
 - The Field ctor that takes a BytesRef complains if the field is tokenized or if offsets are indexed.
 - The Field ctor that takes a BytesRef complains if the field is neither indexed, nor docvalued, nor stored.
 - It is no longer possible to configure a TokenStream plus a value on the same field: either the value is a token stream, or it's something else. Otherwise this introduces weird situations, like we only need to tolerate a tokenized binary value if a token stream is configured too.

The last bit makes the change breaking, so I'm targeting 10.0 only.

**Comment by rmuir** [comment]
will take another pass, this sounds really good to me. I think the restriction was just a hacky way of preventing some of the issues, its obviously not ideal.

.document api is just a PITA

**Comment by jpountz** [comment]
I pushed a new commit that also disallows term vector offsets on binary fields.

**Comment by jpountz** [comment]
@rmuir Do you have thoughts on this change?

**Comment by rmuir** [comment]
@jpountz I will try to review this today. Sorry for the delay. I haven't written java code in years, i'm crazy busy at work, and i try to give more time to `.document` api.... all contributing to my slowness. I had in mind that i wanted to checkout this branch and "poke" too

**Comment by jpountz** [comment]
Thank you, and no worries at all about the delay, I just wanted to check if it was still on your mind since you said you were interested in looking into it.

**Review by rmuir — APPROVED** [review]
This is great, I think it really simplifies Field. At least I can reason about it better now.

The checks look complete, I spent a good deal of time looking for holes. Thanks for the paranoia!

**Comment by jpountz** [comment]
Thanks @rmuir !

**Pull request merged**
