### PR TITLE
GH-11772: remove WindowsDirectory and native subproject.

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

**Comment by dweiss** [comment]
Fixes #11772.

**Review by jpountz — APPROVED** [review]

**Review by danmuzi — APPROVED** [review]
Looks good to me 👍 
However, the issue number in the PR and commit message should be changed from "GH-1172" to "GH-11772".

**Review by rmuir — CHANGES_REQUESTED** [review]
can we remove WindowsDirectory.java too?

**Comment by dweiss** [comment]
Ah. missed the bull's eye, didn't I.

**Review by rmuir — APPROVED** [review]

**Comment by uschindler** [comment]
Thanks. I was just wondering, why this strange title of PR with "GH-"? I would just put issue number in usual # notation. This does not highlight at all.

**Comment by dweiss** [comment]
This is an alternative notation for issue numbers that github actually understands; see commit links, for example:
image
I tend to prefer it to hash+number because hash+number is treated as a commented line if you edit any previous commit (rebase interactive, amend, etc.)... There are ways to work around it, but it requires some manual tweaks - I prefer to just use GH-xxx.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests

**Comment by danmuzi** [comment]
I think the issue number for this patch is wrong again.
It needs to be changed from #11172 to #11772.

**Pull request merged**
