### PR TITLE
GITHUB#11728: Improve code clarity for OrdinalMap

### PR DESCRIPTION
**Pull request by mdmarshmallow**
### Description

#11728 

* Added comments to `OrdinalMap` to hopefully make the code and map construction algorithm clearer
* Changed some variable names
* Replaced `firstSegmentBits` with `firstSegmentHasAllTerms` boolean, the latter makes the code a bit more clear

### CODE REVIEW

**Comment by jpountz** [comment]
This class is indeed a bit subtle, but most of the comments that you are suggesting seem to be paraphrasing what the code is doing and I'm not sure that they would actually help someone who would try to get more familiar with this class.

**Comment by mdmarshmallow** [comment]
That's fair, I think I also was getting a little too specific with the comments in some places. I'll go through and see if I can make the comments more general than they currently are.

**Comment by mdmarshmallow** [comment]
Removed some of the comments that were maybe just paraphrasing the code too much. I also renamed some variables to what I think are more clear names. Hopefully the comments/variable names make more sense now?

**Comment by stefanvodita** [comment]
Bumping this PR because I think it’s a good change in its current form. The increased expressiveness would be helpful to me if I was using this class.

**Comment by jpountz** [comment]
Hey @mdmarshmallow. There have been some changes in the meantime that introduced many conflicts, so what I did is that I took your main comment that describes the OrdinalMap algorithm and pushed it under your name. Sorry for the delay.

**Comment by mdmarshmallow** [comment]
Hi @jpountz, thanks for pushing! I took a look back at the comment and I think it references some variable names changes that were added with some of the code changes that weren't included. I'll make a follow up commit in the next few days to address some of those inconsistencies.

**Comment by jpountz** [comment]
Oops, sorry about that. Thank you!

**Pull request closed without merging**
