### PR TITLE
LUCENE-10259: Fix startup scripts to allow whitespace in path names

### PR DESCRIPTION
**Pull request by uschindler**
see https://issues.apache.org/jira/browse/LUCENE-10259

### CODE REVIEW

**Review by dweiss — APPROVED** [review]

**Review by jpountz — APPROVED** [review]

**Comment by rmuir** [comment]
Can we fix scripts header while we are here. `/bin/bash` is wrong. Let's use `/usr/bin/env bash` so it works everywhere (such as BSD). Also for the future, I suspect bash is not really needed and Bourne (sh) will suffice.

**Comment by uschindler** [comment]
I will check syntax and maybe move to /bin/sh. I am not sure about the `$(...)` vs the backticks `` `...` ``. The latter works with plain bourne, the first I am unsure. It's hard to test as most linux have only bash. I can try with dash.

**Comment by uschindler** [comment]
@rmuir the bourne shell does not support `$(...command...)` and you can only use backticks which can't be nested. I can fix this by writing the first line split into several lines.

**Comment by uschindler** [comment]
Hi i committed a fix which now uses backticks only. It's only 2 lines now.

Can anybody check this again with Mac or do i need to start a shell? Maybe @rmuir can check on his BSD box.

**Comment by mocobeta** [comment]
luke.sh works for me on Fedora 34. I will run it on macOS 11

**Comment by uschindler** [comment]
When testing, make sure to extract lucene to a directory with whitespace (often a quick "mv"works and revert after testing).

**Comment by mocobeta** [comment]
```
lucene $ tar xzf lucene/distribution/build/release/lucene-10.0.0-SNAPSHOT.tgz -C /tmp/
lucene $ mv /tmp/lucene-10.0.0-SNAPSHOT/ "/tmp/lucene-10.0.0 SNAPSHOT/"
lucene $ /tmp/lucene-10.0.0\ SNAPSHOT/bin/luke.sh 
```
This works for me on Fedora 34 and macOS 11.

**Review by dweiss — APPROVED** [review]

**Review by rmuir — APPROVED** [review]
Thanks!

**Pull request merged**
