### PR TITLE
Compare the missing value with the top value even after the hit queue is full

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description

see #13643

### CODE REVIEW

**Comment by gsmiller** [comment]
Thanks! I left you one comment in the corresponding issue you opened for this (sorry, meant to put it here in the PR).

**Comment by gsmiller** [comment]
Looks good. Thanks @bugmakerrrrrr! (Looks like the check task failed in a transient way... out of disk space? I ran the checks locally just to make sure they pass and they do, as expected)

**Comment by gsmiller** [comment]
@bugmakerrrrrr could you add an entry in CHANGES.txt before we merge please?

**Comment by bugmakerrrrrr** [comment]
@gsmiller I add the entry under 9.12.0 Optimizations, please correct me if I'm wrong.

**Comment by gsmiller** [comment]
Sounds right to me. Thanks @bugmakerrrrrr !

**Review by gsmiller — APPROVED** [review]

**Pull request merged**
