### PR TITLE
hunspell: support empty dictionaries, adapt to the hunspell/C++ repo changes

### PR DESCRIPTION
**Pull request by donnerpeter**

### CODE REVIEW

**Review by dweiss — APPROVED** [review]

**Comment by dweiss** [comment]
Pater, would you mark the milestone these changes go into? If they're not going to be backported to 9x, then only main (10.0.0) would be the right one to select.

**Comment by donnerpeter** [comment]
@dweiss I've scheduled them for 10 for now, thanks! Actually, if there happens to be a new major release from the 9x branch, I'd like to backport all recent Hunspell changes there. Do you have any concerns about that?

**Comment by dweiss** [comment]
No, absolutely - I think these changes are great and everyone on 9x would benefit from them. We should probably add a note to migration.txt but otherwise I'm more than fine for everything to land on 9x as well!

**Comment by donnerpeter** [comment]
What's migration.txt? I see no such file in the repository :(

**Comment by dweiss** [comment]
Sorry - typed from memory, here it is:
https://github.com/apache/lucene/blob/main/lucene/MIGRATE.md

**Comment by donnerpeter** [comment]
Aha! What do you think should be added there? I'd expect the APIs to stay the same, maybe with more of them available in 10.

**Comment by dweiss** [comment]
Sorry if I lost track among all these patches - I thought there would be user facing changes as well. If there are none - no need to add anything.

**Comment by donnerpeter** [comment]
There are some, but they're just API additions which should be backward-compatible.

**Pull request merged**
