### PR TITLE
LUCENE-10560: Faster merging of TermsEnum

### PR DESCRIPTION
**Pull request by jpountz**
This commit adds a new `TermsEnumIndex` abstraction in `oal.index` that wraps a 
`TermsEnum` and an index of the segment that it belongs to, and can be used to
create priority queues that merge TermsEnum instances (either from the inverted
index or from doc values). In either case, a long that holds the first 8 bytes
of the term is computed in order to speed up comparisons. In the doc-values
case, `OrdinalMap` also leverages seek-by-ord capabilities to reason about
shared prefixes across entire windows of terms to not compare shared prefixes
whenever re-ordering the queue, this should especially help with fields that
may share long common prefixes like URLs.

On luceneutil's `OrdinalMap` benchmark, construction time reduced by 30.5% for
the `id` field and by 17.5% for the `name` field.

JIRA: [LUCENE-10560](https://issues.apache.org/jira/browse/LUCENE-10560)
#11596

### CODE REVIEW

**Comment by mikemccand** [comment]
This is a cool idea @jpountz!  And `OrdinalMap` construction is important, e.g. SSDV faceting uses it on every refresh, merging uses it, etc.  Maybe let's revive it? :)

**Comment by jpountz** [comment]
+1 I fell a bit into a trap by trying to make long shared prefixes less adversarial. Let's do progress over perfection and start with a simple approach and look into whether/how we can better handle long sequences of shared prefixes better.

It still shows a good speedup on `OrdinalMapBenchmark`:
main:

```
id: 1401.18461 msec
name: 1248.35069 msec
country_code: 0.39746 msec
time_zone: 0.91389 msec
```

PR:

```
id: 623.27067 msec
name: 937.10905 msec
country_code: 0.30416 msec
time_zone: 0.88108 msec
```

I plan on merging soon if there are no objections.

**Comment by jpountz** [comment]
For reference, it should speed up:
 - OrdinalMap construction
 - Merging of terms in the inverted index
 - Merging of terms in doc values (as a side-effect of the OrdinalMap speedup)

**Comment by mikemccand** [comment]
> +1 I fell a bit into a trap by trying to make long shared prefixes less adversarial. Let's do progress over perfection and start with a simple approach and look into whether/how we can better handle long sequences of shared prefixes better.

+1

Thanks @jpountz!

**Pull request merged**
