### PR TITLE
Allow open-ended ranges in Intervals range

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Currently IntervalsSource.range function closed intervals. 
This will allow open-ended ranges

Relates to #13562

### CODE REVIEW

**Review by romseygeek — COMMENTED** [review]
Can we add a note to the `@param` javadocs on `IntervalsSource#range()` to say that `null` is permitted on `lowerTerm` and `upperTerm` and means an open-ended range at that end?

**Comment by mayya-sharipova** [comment]
@romseygeek Thanks for checking, addressed in 2f2df7951fe416a84fdc7f3b15e5c1283b255ac2

**Comment by javanna** [comment]
Kind reminder to backport if needed and set the appropriate milestone :)

**Comment by javanna** [comment]
Do we also need a changes entry? :)

**Comment by mayya-sharipova** [comment]
@javanna Thanks Luca, can we still backport to 9.12? Are we expecting more releases?

**Comment by benwtrent** [comment]
@mayya-sharipova 10x, there is no longer a 9x.

Lucene main is Lucene 11 now

**Comment by mayya-sharipova** [comment]
@benwtrent Thanks Ben. @javanna Will packport to 10x with a change entry

**Pull request merged**
