### PR TITLE
Replace usage of deprecated java.net.URL constructor with URI

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit replaces the usage of the deprecated `java.net.URL` constructor with `URI`, later converting `toURL` where necessary to interoperate with the URLConnection API.  The usage is mostly in tools, which I verified with `gradlew regenerate`.

The motivation for this change is to address tech debt identified when experimenting with bumping to Java 21. 

relates #12753

### CODE REVIEW

**Comment by rmuir** [comment]
needs @uschindler to review. Only germans understand the difference between URI and URL. Probably not great usability-wise for java to deprecate URL and force everyone to deal with this stuff...

**Comment by rmuir** [comment]
oh yeah, this is also the same class that does DNS lookups in its `equals()` method :)

**Review by uschindler — APPROVED** [review]
The German explanation: one is a location the other is just an opaque name. Every URL is an URI, but not otherwise round.

**Comment by rmuir** [comment]
> The German explanation: one is a location the other is just an opaque name. Every URL is an URI, but not otherwise round.

If every URL is a URI, then how come `URL.equals()` do a DNS lookup and `URI.equals()` does not?

**Comment by uschindler** [comment]
> > The German explanation: one is a location the other is just an opaque name. Every URL is an URI, but not otherwise round.
> 
> If every URL is a URI, then how come `URL.equals()` do a DNS lookup and `URI.equals()` does not?

That's the buggy java implementation.

The question was what the difference between the term URI and URL according to RFC and standards is.

**Comment by ChrisHegarty** [comment]
> oh yeah, this is also the same class that does DNS lookups in its `equals()` method :)

Yeah, it’s a 20+ yr old issue, that is too late to change. I tried…  Anyway, thanks for the reviews.

**Pull request merged**
