### PR TITLE
hunspell: speed up "compress"; minimize the number of the generated entries; don't even consider "forbidden" entries anymore

### PR DESCRIPTION
**Pull request by donnerpeter**

### CODE REVIEW

**Review by dweiss — APPROVED** [review]
I admit I've no idea what improvement I'm looking at here but I trust you know!

**Comment by donnerpeter** [comment]
> I admit I've no idea what improvement I'm looking at here but I trust you know!

I can add some comments with explanations :)

**Comment by dweiss** [comment]
> I can add some comments with explanations :)

No need. I glanced through the code and it doesn't seem to be a backdoor. :) You know better what works here anyway.

**Comment by uschindler** [comment]
@rmuir can you have a look?

**Comment by uschindler** [comment]
> > I can add some comments with explanations :)
> 
> No need. I glanced through the code and it doesn't seem to be a backdoor. :) You know better what works here anyway.

Hahaha. I know donnerpeter and have seen code by him already. But like the xz/liblzma desaster he could possibly be working for long time on taking over the world! We should check if Gradle code was changed!

**Review by dweiss — APPROVED** [review]
I looked again and I think I get the gist. No Gradle executable hooks are included. 
LGTM.

**Pull request merged**
