### PR TITLE
minor javadoc correction on VectorUtilSupport#findNextGEQ

### PR DESCRIPTION
**Pull request by gsmiller**

### CODE REVIEW

**Comment by gsmiller** [comment]
@jpountz was looking through #13958 retroactively to understand the change and I _think_ I spotted a small javadoc error. Can you take a peek? Even though this is super trivial, I wanted to check with you prior to merging to make sure I'm not missing something. Thanks!

**Comment by jpountz** [comment]
I wrote the javadocs this way on purpose, so that it would still work to create an IntVector/LongVector that starts before `from` and count the number of values that are less than the target. E.g. something like this:

```java
if (length >= LONG_SPECIES.length() && length - from < LONG_SPECIES.length()) {
  // less than LONG_SPECIES.length() doc IDs
  LongVector vector = LongVector.fromArray(LONG_SPECIES, values, length - LONG_SPECIES.length());
  VectorMask<Long> mask = vector.compare(VectorOperators.LT, target);
  return length - LONG_SPECIES.length() + mask.trueCount();
} else {
  // other cases
}
```

The current implementation doesn't take advantage of it, so I don't mind removing it, we could add it back later on if we want to take advantatge of it since it's an internal API.

**Comment by gsmiller** [comment]
@jpountz thanks for the clarification! Let's not make the javadoc change then since it sounds like a reasonable reason to keep the requirement that values are sorted beginning at index `0` and not `from`.  (We could always change it later if it seemed like there was a useful reason to not require values `[0, from]` to be sorted).

**Comment by gsmiller** [comment]
@jpountz after thinking a little more, I wonder if an `assert` would make sense to guard against unsorted data between index `0` and `from`? Probably quite unlikely, but would also be nice if that use-case tripped an assert now instead of silently working and then failing later because it didn't adhere to the contract outlined in the javadoc? We could do something like `assert IntStream.range(0, length - 1).noneMatch(i -> buffer[i] > buffer[i + 1]);`. It's trivial but I'm happy to add this if you think it would be reasonable.

**Comment by jpountz** [comment]
This sounds good to me, maybe extract it to a function to avoid increasing the method size too much? Now that you made me look harder at this code, I'm also considering renaming `length` to `to` since `length` usually is a number of entries after `from` while it's an absolute end offset here.

**Comment by gsmiller** [comment]
> I'm also considering renaming length to to since length usually is a number of entries after from while it's an absolute end offset here

+1. I noticed this as well when writing the assertion.

**Comment by gsmiller** [comment]
Added an assertion and tweaked parameter naming as discussed here over in #13972.

**Pull request closed without merging**
