### PR TITLE
LUCENE-10273: Deprecate SpanishMinimalStemmer in favor of SpanishPluralStemmer

### PR DESCRIPTION
**Pull request by rmuir**
The new SpanishPluralStemmer is in fact more "minimal", less agressive  stemming and normalization. For the user that wants only plural stemming, it is the better choice.

Analysis: https://s.apache.org/spanishplural
Original Issue: https://issues.apache.org/jira/browse/LUCENE-10248
Discussion on PR: https://github.com/apache/lucene/pull/461

### CODE REVIEW

**Comment by rmuir** [comment]
To be clear, my major motivation to deprecate is to direct users to the new stemmer, to help with their choice. 

Long term, I think we can simplify choices by removing the previous minimal stemmer which has no separate use-case, or academic literature/study around it. This simplifies users' understanding of the choices we provide. I thought @xaviersanchez blog did a great job of walking through these.

If users want to do aggressive text normalization, they have plenty of choices: ASCIIFoldingFilter, ICUFoldingFilter, MappingCharFilter, etc etc. The minimal stemmer should be minimal!

**Review by jpountz — APPROVED** [review]
What version are you targeting for the removal? 10.0?

**Comment by rmuir** [comment]
> What version are you targeting for the removal? 10.0?

i was thinking to just deprecate, we could revisit the deprecation for 11?

**Comment by jpountz** [comment]
:+1:

**Pull request merged**
