### PR TITLE
Remove IOContext from Directory#openChecksumInput

### PR DESCRIPTION
**Pull request by zacharymorn**
### Description

Remove IOContext from `Directory#openChecksumInput` as suggested in https://github.com/apache/lucene/issues/11933

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
LGTM!

**Review by uschindler — APPROVED** [review]
Looks good. I would suggest to only apply this on master to not break APIs for those who have own codecs.
Please add a migrate.txt entry for migration to 10.

**Comment by zacharymorn** [comment]
Thanks @jpountz @uschindler for the approvals! I have added a migration entry for version 10, and will merge this change to main branch only.

**Review by uschindler — APPROVED** [review]
Looks good. 👍

**Pull request merged**
