### PR TITLE
Propagate topLevelScoringClause from QueryProfiler

### PR DESCRIPTION
**Pull request by mrkm4ntr**
### Description
The topLevelScoringClause is not propagated from QueryProfiler. This causes some optimizations are skipped during profiling.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
Good catch!

**Comment by jpountz** [comment]
@mrkm4ntr Can you add a CHANGES entry for your change?

**Comment by mrkm4ntr** [comment]
@jpountz Thank you for your review. Where should I add an entry? 9.9.2 or 9.10.0?

**Comment by jpountz** [comment]
@mrkm4ntr 9.10 please

**Comment by mrkm4ntr** [comment]
@jpountz Sure. Added.

**Pull request merged**
