### PR TITLE
Fix GeoDegeneratePath compile error

### PR DESCRIPTION
**Pull request by javanna**
9x is not compiling due to a bad cherry pick I believe. This should fix it.

I tried to push the fix directly but something is missing because I don't have permissions, or have I dreamed that I became a committer? :)

### CODE REVIEW

**Comment by rmuir** [comment]
I thought you were a committer too... something isn't right, thank you for the fix

**Comment by rmuir** [comment]
@javanna did you try to push to  https://gitbox.apache.org/repos/asf/lucene.git ? This should work, it is what i set as `upstream` in my git. As far as github goes, in order to be able to use merge button etc, I think go to https://id.apache.org. login and make sure your github username is filled out there.

**Comment by javanna** [comment]
Thanks Robert! id.apache.org is correctly set up but that still does not help. I tried to push to the github repo and not gitbox, I will change that then.

**Comment by rmuir** [comment]
@javanna try to push to the gitbox first. if you want to do a test commit you can add yourself to whoweare page on the website repository: https://github.com/apache/lucene-site. It is a similar situation where you want to set your upstream ref to https://gitbox.apache.org/repos/asf/lucene-site.git.

The github/id.apache.org is a separate thing, basically that just gives you the merge button, since github is really only a readonly mirror.  If you just setup the github username, it may take a while to synchronize (?) If it isn't working by tomorrow, send an email to private@

**Comment by javanna** [comment]
@rmuir I went to gitbox.apache.org (thanks for the tip) and followed the instructions. Turns out that `https://gitbox.apache.org/boxer/` was the missing step to link my github account to the relevant repos. I can now push directly to github too. Thanks for helping me sorting this out.

**Pull request merged**
