### PR TITLE
Work around SecurityManager issues during initialization of vector api (JDK-8309727)

### PR DESCRIPTION
**Pull request by uschindler**
see #12311

### CODE REVIEW

**Comment by uschindler** [comment]
We could also catch the SecurityException, log a warning and throw UOE, so it falls back to Lucene's VectorUtilProvider.

**Comment by uschindler** [comment]
I added a try-catch. The caller of ctor will log the UOE as warning and falls back to default impl.

**Comment by uschindler** [comment]
I also removed a stale comment from earlier days and made constant private.

**Comment by uschindler** [comment]
I now removed the calculation and just initialized a FloatVector.fromArray() to trigger the stupid property read.

**Comment by ChrisHegarty** [comment]
This looks good to me.   I'm going to verify it now in a local ES branch, then report back here.

**Review by ChrisHegarty — APPROVED** [review]
LGTM.  I confirmed that it works in the previously-broken Elasticsearch environment ( even without the need to initialise the class explicitly ).

**Comment by ChrisHegarty** [comment]
I'll get the JDK bug fix into JDK 21, so we can drop this workaround in the upcoming 21 version of this code.

**Comment by uschindler** [comment]
> LGTM. I confirmed that it works in the previously-broken Elasticsearch environment ( even without the need to initialise the class explicitly ).

ES should initialize the class in the main bootstrap. Otherwise the new vector API could randomly disabled if the painless plugin starts first.

**Comment by uschindler** [comment]
> I'll get the JDK bug fix into JDK 21, so we can drop this workaround in the upcoming 21 version of this code. Unfortunately, it's too late for JDK 20.0.2 :-(

Could you check my comment about 9.7 release of lucrne on dev mailing list?

I'd like to get memory segments and this code into 9.7 and wanted to know if the API is finalized or could it still change before GA?

In case of adding Java 21 support into 9.7, I may forward-port this fix to the 21 code as it does not hurt. We can remove it later of the GA release works without.

**Review by benwtrent — APPROVED** [review]
I have confirmed that with class initialization that this fixes the security issue.

I needed to still initialize the class eagerly or I received errors referring to Log4j (a separate issue). But, initializing the class eagerly fixes both of them. 

Thank you @uschindler!!! :shipit:

**Comment by uschindler** [comment]
Ok also backported to 9.x. You can now update the ES snapshot build and just add class initialization into bootstrapping code.

**Comment by ChrisHegarty** [comment]
> > LGTM. I confirmed that it works in the previously-broken Elasticsearch environment ( even without the need to initialise the class explicitly ).
> 
> ES should initialize the class in the main bootstrap. Otherwise the new vector API could randomly disabled if the painless plugin starts first.

++ Agreed. I was mistaken, we do need this initialization.

**Pull request merged**
