### PR TITLE
LUCENE-10301: extract constants to TestSecrets to spare stack inspection and make code more readable

### PR DESCRIPTION
**Pull request by uschindler**
Followup to cleanup TestSecrets after https://issues.apache.org/jira/browse/LUCENE-10301

### CODE REVIEW

**Comment by uschindler** [comment]
This is done in similar way by the JDK SharedSecrets. The reason is mainly to not produce a stack inspection on every access. It is also more readable because code is smaller.

If you'd want to rename the constants, tell me. I just used the Eclipse "extract constant" refactoring and this was done automatically.

**Comment by dweiss** [comment]
To me the explicit version is more readable because you see the "testsecrets" class and not the private constant but I really don't care or mind either way - looks fine to me.

**Review by dweiss — APPROVED** [review]

**Comment by uschindler** [comment]
This is why I asked to rename the constants. I think `INDEX_PACKAGE_ACCESS` => `INDEX_PACKAGE_SECRETS` or `indexPackageSecrets` (although this does not conform to coding standards as it is static final.

**Comment by uschindler** [comment]
I think both names are fine. No matter if its "secret" or "access". Both mean the same in this context. I will merge this later and backport (should work).

**Comment by dweiss** [comment]
I modelled this after the JDK, actually. So Test"Secrets" but inside they have "access" objects. Makes sense to me.

**Comment by uschindler** [comment]
Here is an example in the JDK: https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.base/windows/classes/sun/nio/ch/SocketDispatcher.java#L40-L41

So looks like mine, although the constant is camelcase.

**Comment by uschindler** [comment]
Hi, have you seen this method in Java 15, this should be used, maybe we should add a TODO: [Lookup#ensureInitialized(Clazz)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/invoke/MethodHandles.Lookup.html#ensureInitialized(java.lang.Class))

**Comment by dweiss** [comment]
No, I didn't see that. But it's an equivalent of what class for name currently does (and it doesn't require a lookup). Up to you, this would only apply on main though if it requires jdk 15?

**Comment by dweiss** [comment]
I'd stick to normal java conventions with respect to naming (so upper case, final constant).

**Comment by uschindler** [comment]
I just left a TODO. The code you did is fine, I just like to add TODOs for all stuff where we may need to work after a JDK upgrade. Maybe we should mark those with a separate "tag". But that's a separate issue. It happens often that I write code but I know: in later versions this has to be rewritten.

**Comment by uschindler** [comment]
Main is still JDK 11, but may change soon.

**Pull request merged**
