### PR TITLE
LUCENE-10285: try to force ordering of internal tasks, in spite of ma…

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

**Comment by dweiss** [comment]
@rmuir Can you try on your machine? I've ran 
```gradlew regenerate --rerun-tasks``` 
on a linux box but I suspect the graph ordering may depend on the number of cores, wind patterns, ectoplasm surrounding the CPU and maybe other factors.

**Comment by rmuir** [comment]
@dweiss running now. I'll run regenerate twice and see if i encounter similar behavior.

**Comment by rmuir** [comment]
I can already see the difference in execution order. in the main branch i was able to trivially reproduce the problem. with this patch it runs the TLD stuff first:

```
> Task :lucene:analysis:common:generateTldsInternal
Found 1489 TLDs in IANA TLD Database at https://data.iana.org/TLD/tlds-alpha-by-domain.txt
                      ASCIITLD: 1370 TLDs
    ASCIITLDprefix_1CharSuffix:  108 TLDs
    ASCIITLDprefix_2CharSuffix:   11 TLDs
                         Total: 1489 TLDs
Generated TLD content identical as before, not updating.

> Task :lucene:analysis:common:generateUAX29URLEmailTokenizerInternal
...
```

**Comment by dweiss** [comment]
I do believe it should be all right, although there may be other quirks lurking in there. The thing is: when you have this task graph:

A.dependsOn B
C.dependsOn D

then when you say:

A.dependsOn C

this only means C will run prior to A but says nothing about relative order of B and D. The ordering can be executed like this: B, D, C, A and it's valid.

**Review by rmuir — APPROVED** [review]
I can see the different in task execution order. The TLD list is unchanged, so I was unable to "fully test" the situation where it changes and that triggers TLD regeneration, then tokenizer regeneration after that which incorporates the TLD changes. But from the console output I have confidence this would now work correctly.

**Pull request merged**
