### PR TITLE
Implement MMapDirectory with Java 20 Project Panama Preview API

### PR DESCRIPTION
**Pull request by uschindler**
This implements MMapDirectory's IndexInput with the Project Panama Preview APIs of Java 20 (see https://openjdk.org/jeps/434). This is mainly a copy of the Java 19 implementation, only with a few changes:
- `MemorySession` was splitted into `Arena` and `SegmentScope`, mainly we now use `Arena` in `MemorySegmentIndexInput` lifetime handling and `Arena#scope()` for the actual `FileChannel#map` invocation.
- Add a new MR-JAR sourceset
- Use new `ValueLayout.JAVA_xxx_UNALIGNED` constants

Like in #12033 we remove the preview flag of class files

### CODE REVIEW

**Comment by uschindler** [comment]
As JDK 20 is not yet availabe on Adoptium/Eclipse servers this fails prechecks.

**Comment by uschindler** [comment]
@mcimadamore: This is the Java 20 version. Changes were simple (see above).

**Comment by uschindler** [comment]
Code is tested here (Java 17 till 20):
- [Linux](https://jenkins.thetaphi.de/job/Lucene-MMAPv2-Linux/)
- [Windows](https://jenkins.thetaphi.de/job/Lucene-MMAPv2-Windows/)

**Comment by mcimadamore** [comment]
Thanks for testing @uschindler!

**Comment by mbien** [comment]
> As JDK 20 is not yet availabe on Adoptium/Eclipse servers this fails prechecks.

@uschindler I believe the gradle automatic JDK download feature itself [doesn't support ea JDKs atm](https://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning).

It might work by pointing it at a local JDK. Although be warned that the gradle daemon can't run on JDK 20 yet, so we [run the daemon on 11](https://github.com/apache/netbeans/blob/df0c22a07a95882ea76c03ac6a25f91ba4c7eb21/.github/workflows/main.yml#L120-L125) while using the standard setup-java action to get JDK 20ea (e.g. zulu, since they provide those super early). Works fairly well for the NetBeans CI which uses gradle for some modules.

**Comment by uschindler** [comment]
Hi @mbien,
This is why the PR is currently in draft status. We build and test it already with a local install. It is enough to set an env variable. Lucene always runs Gradle with Java 17. You can still test against later version by passing RUNTIME_JAVA_HOME.

This PR is just not yet merged to not being too much hassle for contributors/committers. When it does not Autodownload it's too hard to use.

Once GA release is available on Adoptium we will merge this.

I have another solution in my dev folder that allows to compile without jdk 19 or 20 downloaded or installed at all, but it is a bit hacky (it ships with a signatures jar file that's compiled against).

**Comment by uschindler** [comment]
See also #12188 for the alternative version which needs no JDK 19/20/21/... at compile time.

**Comment by uschindler** [comment]
Closing in favor of #12188.

**Pull request closed without merging**
