### PR TITLE
LUCENE-5595: re-enable TestICUNormalizer2CharFilter random test, splitting by mode

### PR DESCRIPTION
**Pull request by rmuir**
Re-enable the randomized testing here, but with a separate test for each
mode rather than all in one method. It gives better testing and also easier-to-debug
testing.

### CODE REVIEW

**Comment by rmuir** [comment]
cc: @magibney 

This is the basic random test that we've had disabled for years. Honestly original bugs could have been in ICU itself, not sure. Maybe the new tests will fail! But I think it is much better for us to enable it in `main` branch with the new gradle build, with tests corresponding to different normalization modes. Maybe we stand a better chance to fix any failures this way.

**Comment by magibney** [comment]
LGTM; makes sense to re-enable and add separate tests for different normalization forms.

**Comment by rmuir** [comment]
I'm running my inefficient beasting script: shell script loop, gradle daemons disabled, all lucene/analysis/icu tests with nightly and multiplier. I'll let it run for a while before we try jenkins, I don't want to just make builds flaky.

**Comment by rmuir** [comment]
100 successful runs in beasting with nightly and 10x multiplier: I think we are ok. Can always open an issue if jenkins trips.

**Pull request merged**
