### PR TITLE
Avoid NPEx if the end of the stream has been reached without reading any characters

### PR DESCRIPTION
**Pull request by pzygielo**
e.g. by user responding with ^D
```
Press (n)ext page, (q)uit or enter number to jump to a page.
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "line" is null
	at org.apache.lucene.demo.SearchFiles.doPagingSearch(SearchFiles.java:244)
	at org.apache.lucene.demo.SearchFiles.main(SearchFiles.java:152)
```

```
Press (p)revious page, (n)ext page, (q)uit or enter number to jump to a page.
n
Only results 1 - 50 of 104 total matching documents collected.
Collect more (y/n) ?
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "line" is null
	at org.apache.lucene.demo.SearchFiles.doPagingSearch(SearchFiles.java:198)
	at org.apache.lucene.demo.SearchFiles.main(SearchFiles.java:152)
```

### CODE REVIEW

**Comment by pzygielo** [comment]
May I ask for review, please?

**Comment by pzygielo** [comment]
@kaivalnp @gf2121

**Review by benwtrent — APPROVED** [review]
Simple enough. It's nice to have demos not throw NPEs :)

**Review by dweiss — APPROVED** [review]

**Comment by pzygielo** [comment]
Thanks for checking.

**Comment by dweiss** [comment]
I've applied this to main and branch_9x (9.9). Thank you.

**Pull request merged**
