### PR TITLE
Backport to 9x: Initialize facet counting data structures lazily #12408

### PR DESCRIPTION
**Pull request by stefanvodita**
We can bring this optimisation from #12408 to 9x. It would make it easier to backport #12966 afterwards. I think the intention was to backport at first, since [the CHANGES entry is under 9.8 in the commit](https://github.com/apache/lucene/blob/179b45bc23e4496278b7058811577b66ef3af77d/lucene/CHANGES.txt#L164).

### CODE REVIEW

**Comment by stefanvodita** [comment]
@gsmiller - I'd like your opinion as the author of the original commit. Am I missing some reason why we shouldn't backport?

**Comment by stefanvodita** [comment]
I went through this change once more to make sure it's safe to push. I would still like a second opinion, just in case I'm missing something, otherwise I'll merge this in a few days.

**Review by msokolov — APPROVED** [review]
it seems reasonable, if a bit messy (so many conditionals!) ... but this is what was committed to main branch, right? Did you have to make many changes to pull it in to 9x? Anyway LGTM

**Comment by stefanvodita** [comment]
Thank you for the review Mike! I did have to change a couple things:
1. Added a new constructor to `TaxonomyFacets`, which takes a `FacetsCollector`, since I couldn't change the existing one.
2. Updated `TaxonomyFacetCounts` too, which no longer exists on `main`.

**Pull request merged**
