### PR TITLE
trivial updates on github actions

### PR DESCRIPTION
**Pull request by mocobeta**
- upgrade actions/setup-java to v2 in the hunspell regression workflow (aligned with the main workflow)
- migrate the distribution to 'temurin' (recommended in [supported distributions](https://github.com/actions/setup-java#supported-distributions))

### CODE REVIEW

**Comment by mocobeta** [comment]
Do you have a minute to take a look? @dweiss

**Review by dweiss — APPROVED** [review]

**Comment by dweiss** [comment]
It'd be interesting to randomize those distributions using a custom action, perhaps? I have no experience here whatsoever, but I bet it's possible...

**Comment by mocobeta** [comment]
Thank you, I will merge this soon.

> It'd be interesting to randomize those distributions using a custom action, perhaps? I have no experience here whatsoever, but I bet it's possible...

I have never tried writing such a complex action, it could be implemented by some bash script. ? (I am not sure the Actions' sandbox gives users what level of flexibility.)

**Comment by dweiss** [comment]
I think these actions are javascript, basically. I've never written one myself, so can't help. Don't worry about it, it was just a wild idea - we have lots of randomization elsewhere.

**Comment by mocobeta** [comment]
I am not sure if randomizing the distribution per test run is possible without forking the setup-java action, but I think a matrix test may be easy  (if it makes sense to run workflows for multiple distributions on every PR.)

**Pull request merged**
