### PR TITLE
No need to rewrite queries in unified highlighter

### LINKED ISSUE #11490: UnifiedHighlighter can miss terms because of query rewrites [LUCENE-10454]
Before extracting terms from a query, UnifiedHighlighter rewrites the query using an empty searcher. If the query rewrites to MatchNoDocsQuery when the reader is empty, then the highlighter will fail to extract terms. This is more of an issue now that we rewrite BooleanQuery to MatchNoDocsQuery when any of its required clauses is MatchNoDocsQuery (https://issues.apache.org/jira/browse/LUCENE-10412). I attached a patch showing the problem.

This feels like a pretty esoteric issue, but I figured it was worth raising for awareness. I think it only applies when weightMatches=false, which isn't the default. I couldn't find any existing queries in Lucene that would be affected.

We ran into it while upgrading Elasticsearch to the latest Lucene snapshot, since a couple custom queries rewrite to MatchNoDocsQuery when the reader is empty.

---
Migrated from [LUCENE-10454](https://issues.apache.org/jira/browse/LUCENE-10454) by Julie Tibshirani (@jtibshirani), updated Aug 18 2022
Attachments: [LUCENE-10454.patch](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-10454/LUCENE-10454.patch), [LUCENE-10454-fix.patch](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-10454/LUCENE-10454-fix.patch)

### PR DESCRIPTION
**Pull request by romseygeek**
### Description

Since QueryVisitor added the ability to signal multi-term queries, the query rewrite
call in UnifiedHighlighter has been essentially useless, and with more aggressive
rewriting this is now causing bugs like #11490.  We can safely remove this call.

Fixes #11490

### CODE REVIEW

**Review by dsmiley — COMMENTED** [review]
I'm supportive of this (net positive I guess?), but we must recognize there are query parsers that aren't compatible with this.  I believe the Surround Query Parser is one.  See LUCENE-8492 and a simple Solr test shown there (still exists; I suspect it'll fail after this change).  Basically, this query parser produces Query subclasses that must be rewritten before they know their terms.  These queries don't support a query visitor?  We should add a Lucene level test.

**Comment by romseygeek** [comment]
I thought the changes you made for unrecognized queries fixed the issues with the surround query parser? If not it would be good to implement query visitors for the queries that it produces, or at the very least have a test in the highlighting module for them.

**Comment by dsmiley** [comment]
> I thought the changes you made for unrecognized queries fixed the issues with the surround query parser? 

I forget LOL but...

> If not it would be good to implement query visitors for the queries that it produces, or at the very least have a test in the highlighting module for them.

Indeed; let's test & see

**Comment by romseygeek** [comment]
I ported the test in https://issues.apache.org/jira/secure/attachment/12919819/TestUnifiedHighlighterSurround.java to latest main, and I can confirm that it fails if you set `withWeightMatches(false)`.  But! It fails if the empty searcher rewrite is in place as well, so this change makes no difference to it.  So I think we should merge it anyway, as it doesn't seem to break anything that isn't already broken?

**Comment by dsmiley** [comment]
+1 works for me; this change is the right thing to do, even if it surfaces issues that can be separately fixed.

**Comment by OpakAlex** [comment]
Thanks for the fix!

**Comment by jpountz** [comment]
@romseygeek Should it be backported to branch_9x?

**Comment by romseygeek** [comment]
Oops, yes, I should have backported it at the time.  Will do that now!

**Pull request merged**
