### PR TITLE
Reduce number of calculations in FSTCompiler

### PR DESCRIPTION
**Pull request by mrhbj**

### CODE REVIEW

**Review by mikemccand — APPROVED** [review]
Thanks for the tiny optimization, it looks great.

Are you an AI or a real human ;)  Let's try for a PR-based Turing Test!

Regardless of that outcome, this change is great -- I'll merge.

**Comment by mrhbj** [comment]
@mikemccand You are welcome. I am a ream human. no an AI. -_-

**Comment by mikemccand** [comment]
> @mikemccand You are welcome. I am a ream human. no an AI. -_-

Ahh thanks for the reply.  Could you describe how you got involved / interested in open source development?  How about specifically Apache Lucene?

**Comment by mrhbj** [comment]
I had use elasticsearch in our sofeware.Elasticsearch is so faster to search data. I know elasticsearch use lucence to make it faster.I am very interested in this and enjoy read lucence source code.



---Original---
From: "Michael ***@***.***&gt;
Date: Fri, Sep 20, 2024 07:26 AM
To: ***@***.***&gt;;
Cc: "Jason ***@***.******@***.***&gt;;
Subject: Re: [apache/lucene] Reduce number of calculations in FSTCompiler (PR#13788)




  
@mikemccand You are welcome. I am a ream human. no an AI. -_-
  
Ahh thanks for the reply.  Could you describe how you got involved / interested in open source development?  How about specifically Apache Lucene?

**Pull request merged**
