### PR TITLE
LUCENE-10146: Add VectorSimilarityFunction.COSINE

### PR DESCRIPTION
**Pull request by jtibshirani**
This PR adds support for using cosine similarity with kNN vector fields.

It takes a simple approach and doesn't attempt optimizations like normalizing
the query vector in advance, or performing loop unrolling. The thinking is that
users who prioritize efficiency can normalize all vectors in advance and use
`VectorSimilarityFunction.DOT_PRODUCT`.

### CODE REVIEW

**Review by mayya-sharipova — APPROVED** [review]
@jtibshirani This change LGTM! Thanks for your work. I just left a suggestion for an extra test.

**Comment by jtibshirani** [comment]
Thanks for the review!

**Review by msokolov — COMMENTED** [review]
Thanks, looks good to me, although I do wonder if this might be a trap for the unwary in terms of performance. Do we know how it performs relative to dot_product?

**Comment by jtibshirani** [comment]
@msokolov @mayya-sharipova following up: I ran benchmarks and it's indeed significantly slower (around 20% on some of the datasets we've been using). Here's what I've done:
* Added a note to `VectorSimilarityFunction#COSINE` explaining that `DOT_PRODUCT` is the preferred option when you don't need to preserve the original vectors: https://github.com/apache/lucene/pull/400
* Opened https://issues.apache.org/jira/browse/LUCENE-10191 with ideas to speed up cosine similarity

Happy to hear other feedback/ ideas!

**Pull request merged**
