### PR TITLE
Add JAVA_OPTS to download the gradle-wrapper jar behind proxy.

### PR DESCRIPTION
**Pull request by balmukundblr**
# Description
Lucene uses a custom WrapperDownloader to download the gradle-wrapper jar file. The call is made via a script here: https://github.com/apache/lucene/blob/main/gradlew#L117. The problem is if we are behind proxy, the JVM will not be able to download the file.

# Solution

This simple PR fixes the issue by introducing a JAVA_OPTS variable in the downloader script. Users who are behind proxy may then use this variable to set their proxy settings.

JAVA_OPTS="-DproxySet=true -Dhttps.proxyHost=&lt;host&gt; -Dhttps.proxyPort=&lt;port&gt;"

# Tests

We have run the ./gradlew check.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/lucene/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Lucene maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.

### CODE REVIEW

**Comment by balmukundblr** [comment]
> Thanks for this patch! Can you please also update gradlew.bat?

Done required changes in gradlew.bat file.

**Comment by rmuir** [comment]
Is this not instead a bug in the `WrapperDownloader.java`, that it doesn't respect the conventional environment variables for proxy support (e.g. `http_proxy=`) when downloading? Other tools all do this.

I would consider setting `-Djava.net.useSystemProxies=true` to fix this, so that users environment vars are respected, and they don't need to mess with jvm arguments for things to work? just a thought.

**Comment by dweiss** [comment]
I don't live behind a proxy so I have no way of verifying this. What are "other tools", Rob? Is this really a convention?

**Comment by dweiss** [comment]
I looked it up. It does seem to be a widespread (and old) convention indeed. I think it'd be good to take it into account. Would it work for you to pass proxy settings via environment variables, @balmukundblr ?

**Pull request closed without merging**
