### PR TITLE
[9.12] Add support and compat testing for 8.11.4

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit adds support and compat testing for 8.11.4, to 9.12.

relates #13821

### CODE REVIEW

**Comment by HoustonPutman** [comment]
So I'm looking at the last time I did this for 8.11.3 (https://github.com/apache/lucene/commit/521c26e4fb547bb0aeafdbea838aec038ceb1538), and it looks like there were more things added. Is that not needed anymore? (I know the back compat testing was changing a lot around that time, so I'm not sure what is actually needed now)

**Comment by ChrisHegarty** [comment]
> So I'm looking at the last time I did this for 8.11.3 ([521c26e](https://github.com/apache/lucene/commit/521c26e4fb547bb0aeafdbea838aec038ceb1538)), and it looks like there were more things added. Is that not needed anymore? (I know the back compat testing was changing a lot around that time, so I'm not sure what is actually needed now)

The list of versions has been moved from a string in source to a separate versions file.

**Review by HoustonPutman — APPROVED** [review]
Awesome, thanks again!

**Review by uschindler — COMMENTED** [review]
looks fine.
This also applies to branch_9x, right?

**Pull request merged**
