### PR TITLE
Lazy initialize ForDeltaUtil and ForUtil in Lucene912PostingsReader

### PR DESCRIPTION
**Pull request by original-brownbear**
Lazy initialize these fields. They consume/cause a lot of memory/GC because they are allocated frequently (~7% of all allocations in luceneutil's wikimedia medium run for me). This does not cause any measurable slowdown as far as runtime is concerned and since these are not even needed for all instances (in fact they are rarely used in the queries the benchmark explores) save quite a few CPU cycles for collecting and allocating them.

@jpountz I know we talked about reusing these instances, but as far as I can tell this deals with the problem much more fundamentally, we simply often do not need these?

### CODE REVIEW

**Comment by jpountz** [comment]
Even if it doesn't show up in benchmarks it's disappointing to have these conditions in hot code paths. Could we instead initialize these objects in reset() if `docFreq >= BLOCK_SIZE`?

**Comment by jpountz** [comment]
If you're looking at this sort of allocation, you may also want to specialize BlockDocsEnum into one class that decodes only doc IDs and another one that decodes docs and freqs. The former wouldn't need the long[] freq array and the `PForUtil` helper.

**Comment by original-brownbear** [comment]
Hmm I tried and failed miserably to find a solution to initialize in `reset()` that I fully understand :) It's quite hard to reason about all the possible paths here for me, but I see your point.
As far as specialization goes, that one I could find a version that didn't show runtime regressions (because callsites + polymorphism).
Maybe do a little cleanup along the lines of https://github.com/apache/lucene/pull/13892 first then get back to this? :)
It's hard to fix this without complicating the code, this is the simplest version I could find but I see your points. I bet if we clean up all the duplication that we can cleanup without runtime overhead, we'll find an easier fix here :) wdyt?
(this one also isn't so urgent, it's very few cycles runtime, mostly a p100 thing for JVMs under GC pressure probably)

**Comment by jpountz** [comment]
I would expect putting something like `if (forUtil == null && termState.docFreq >= BLOCK_SIZE) { /* initialize forUtil */ }` in reset() to work (untested).

**Review by jpountz — APPROVED** [review]
This looks good, you should be able to save the PForUtil instantiation on EverythingEnum by checking totalTermFreq against BLOCK_SIZE.

**Comment by original-brownbear** [comment]
Thanks Adrien!

**Comment by jpountz** [comment]
It's almost certainly this change that sped up TermTitleSort on October 12th, since TermTitleSort is the task that creates the most `PostingsEnum` objects. I pushed an annotation.

**Pull request merged**
