### PR TITLE
Change to versions.toml after running ./gradlew tidy

### PR DESCRIPTION
**Pull request by slow-J**
I ran ./gradlew tidy and I noticed that it reformatted versions.toml. There was a change yesterday https://github.com/apache/lucene/pull/13484 so it is possibly related.

### CODE REVIEW

**Comment by dweiss** [comment]
I think it's just end-of-line markers?

**Comment by dweiss** [comment]
Please pull the changes on main - I've added line ending normalization there, I missed it in #13484.

**Comment by slow-J** [comment]
Thanks for the fix. Will close this PR then.

**Comment by dweiss** [comment]
Thank you for reporting, @slow-J !

**Pull request closed without merging**
