### PR TITLE
Add tidy after addVersion is called.

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

**Comment by dweiss** [comment]
I believe something like this is needed to make the add-new-version step pass after code changes.

**Review by msokolov — APPROVED** [review]
Thanks for this, Dawid, I was just looking at it too. I'm a little afraid to test though! This script is crazy powerful. Looks OK to commit though

**Comment by dweiss** [comment]
Yeah... I kind of hope it's going to work - I don't know if there's a way to test it anyhow.

**Comment by dweiss** [comment]
Jan (@janhoy), do you know if this is the right syntax/ way to format code after an automatic addition of a new version?

**Comment by janhoy** [comment]
> Jan (@janhoy), do you know if this is the right syntax/ way to format code after an automatic addition of a new version?

Please use `{{ gradle_cmd }}`, Else it looks good. It might be more efficieny to do godt only on the affected module?

**Comment by dweiss** [comment]
Thanks, Jan! I missed it somehow. I'll leave tidy to run on an entire project - it's fast enough and if anything ever changes, it prevents accidental regressions.

**Pull request merged**
