### PR TITLE
This fixes immutability of clauseSets (broken by #13950)

### PR DESCRIPTION
**Pull request by uschindler**
This fixes immutability of `BooleanQuery` caused by PR #13950.

See comment: https://github.com/apache/lucene/pull/13950#pullrequestreview-2508662206

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
Thanks @uschindler !

**Comment by uschindler** [comment]
P.S.: I added the `Collections.immutableCollection` only in the getter, because making `EnumMap clauseSets` does not work:
- The inner values of the map are custom classes. As we have no unmodifiable Multiset, we cant wrap it without breaking equals (If we map it as unmodifiableCollection, the resulting equals/hashCode inspects all elements and respects order.
- we can make the outer map immutable, but as this one is not exposed, I don't care. I just added another warning.

For the future: If people submit PRs about making private members which are collections public, always check if the immutability could be violated. This is a major problem in Java where collections are by default mutable!

**Comment by mikemccand** [comment]
> For the future: If people submit PRs about making private members which are collections public, always check if the immutability could be violated. This is a major problem in Java where collections are by default mutable!

+1

Is this something a static checker could catch?

**Comment by gsmiller** [comment]
Ah great catch. Thanks @uschindler!

**Comment by shubhamvishu** [comment]
Thanks for fixing this @uschindler !

**Pull request merged**
