### PR TITLE
LUCENE-10561 Reduce class/member visibility of all normalizer and stemmer classes

### PR DESCRIPTION
**Pull request by shahrs87**
# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/lucene/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [ ] I have given Lucene maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.

### CODE REVIEW

**Comment by shahrs87** [comment]
```
 apache-lucene % ./gradlew check
> Task :lucene:analysis:common:generateClassicTokenizerChecksumCheck FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/Users/rushabh.shah/apache-lucene/gradle/generation/regenerate.gradle' line: 184

* What went wrong:
Execution failed for task ':lucene:analysis:common:generateClassicTokenizerChecksumCheck'.
> Checksums mismatch for derived resources; you might have modified a generated resource (regenerate task: generateClassicTokenizer):
  Current:
    lucene/analysis/common/src/java/org/apache/lucene/analysis/classic/ClassicTokenizerImpl.java=c825a8b8d0d0d893b4914e7161bcd119e7b07b40
  
  Expected:
    lucene/analysis/common/src/java/org/apache/lucene/analysis/classic/ClassicTokenizerImpl.java=381a9627fd7da6402216e3279cf81a09af222aaf
```

When I am running `./gradlew check`, I am getting the above error. Looks like I need to update checksum in some file. Do we have any graddle target to achieve that ?

**Comment by mocobeta** [comment]
Hi @shahrs87.
First of all, thanks for the great PR! As for the failed checksum check for `ClassicTokenizerImpl`, please refer to Robert's comment in Jira - I think you can omit `ClassicTokenizerImpl` for now and we can improve it in another issue/PR.

**Comment by shahrs87** [comment]
@mocobeta Thank you the reply. I have removed the classes that are generated via jflex. I also ran all the workflow test mentioned in Contributors guide and all seems to pass. Can you please review the PR ? Thank you.

**Comment by mocobeta** [comment]
> Couldn't change for StempelStemmer since PolishAnalyzer depends on some member variable of StempelStemmer

`StempelStemmer` is supposed to be used from other packages/modules (according to the javadocs), I think it's fine.

**Comment by mocobeta** [comment]
I feel it's a bit confusing that package-private classes have `public` members. Should we also change all public variables/methods to package-private (in other words, remove the `public` access modifier from those classes)? 
cc @rmuir

**Comment by shahrs87** [comment]
@mocobeta Thank you for your review. Addressed your review comment in latest revision. Please review again.

**Comment by shahrs87** [comment]
@mocobeta Can you please suggest some starter jiras which will give me overview on Lucene and will be helpful to community also. Thank you.

**Comment by mocobeta** [comment]
@shahrs87 Looks good to me. Can you please add a [CHANGES](https://github.com/apache/lucene/blob/main/lucene/CHANGES.txt) entry to "API changes" section in 10.0.0? Also, we need a [MIGRATE](https://github.com/apache/lucene/blob/main/lucene/MIGRATE.md) entry; I'll add it later.

I think we can merge this with CHANGES and MIGRATE entries. Will keep it open till tomorrow to let others give time for another review.

**Comment by mocobeta** [comment]
> Can you please suggest some starter jiras which will give me overview on Lucene and will be helpful to community also. 

We have a couple of Jira issues with `newdev` label for new developers but I don't think the list is well maintained, sorry :/
https://issues.apache.org/jira/browse/LUCENE-9303?jql=(project%3DLUCENE)%20AND%20resolution%3DUnresolved%20AND%20labels%3Dnewdev

Apart from `newdev` label, there are many small (minor) issues that are non-controversial, you could browse unresolved and well-described Jira issues and then pick ones for starters.

**Comment by shahrs87** [comment]
> Can you please add a [CHANGES](https://github.com/apache/lucene/blob/main/lucene/CHANGES.txt) entry to "API changes" section in 10.0.0?
@mocobeta  Done ! Thank you for the review.

**Review by mocobeta — APPROVED** [review]

**Pull request merged**
