### PR TITLE
LUCENE-10241: Updating OpenNLP to 1.9.4.

### PR DESCRIPTION
**Pull request by jzonthemtn**
# Description

Updating OpenNLP dependency to 1.9.4.

#11277

# Solution

Updated OpenNLP dependency version.

# Tests

Tests passed.

# Checklist

Please review the following and check all that apply:

- [X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/lucene/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [X] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Lucene maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [X] I have developed this patch against the `main` branch.
- [X] I have run `./gradlew check`.
- [ ] I have added tests for my changes.

### CODE REVIEW

**Comment by epugh** [comment]
It would be nice if this was updated to the awesome new OpenNLP 2.x line!

**Comment by epugh** [comment]
@jzonthemtn  not sure I have the knowledge or chops to do this upgrade...

**Comment by jzonthemtn** [comment]
> @jzonthemtn not sure I have the knowledge or chops to do this upgrade...

I'll push an update!

**Review by cpoerschke — APPROVED** [review]
LGTM if we wanted to upgrade to latest 1.9.x ahead of an upgrade to 2.x

* https://opennlp.apache.org/news/release-192.html
* https://opennlp.apache.org/news/release-193.html
* https://opennlp.apache.org/news/release-194.html

**Comment by cpoerschke** [comment]
> > @jzonthemtn not sure I have the knowledge or chops to do this upgrade...
> 
> I'll push an update!

I'm also interested in this -- #12674 so far, work-in-progress.

**Comment by cpoerschke** [comment]
If there are no objections or concerns I'll aim to merge this sometime next week.

(And the upgrade to 2.x can happen as a follow-up pull request.)

**Pull request merged**
